openshift-assisted/assisted-installer-ui

src/api/axiosClient.ts
src/api/clusters.ts
src/api/events.ts
src/api/versions.ts
src/config/constants.ts

Add possibility to pass custom axios instance
UHC portal can call `setClient(customClient)`. The `customClient` instance will have a proper interceptors set (adding auth/altering url). Standalone Facet app, does not have to do anything, just use the default client.

Use interceptor for axios instance

---

.eslintrc
package.json
src/api/index.ts
src/index.ts
yarn.lock

Components can be imported directly. The rest of code is wrapped into namespaces.
In addition, potential circular dependencies cause build failure.

Wrap re-exports into namespaces

---

src/components/ui/SimpleDropdown.tsx

A minor wording tweak to include the noun in the prompt similar to what we do if this were a PatternFly form field, like [this example](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#validation-on-submission).

Tweak role selection text

---

src/components/hosts/HostsTable.tsx

This PR attempts to rename the `Created At` column heading to `Discovered At`. The word "created" may match what's happening in the backend, but from the user's perspective these hosts are "Discovered" at a certain time, and "Discovering" is [the first status](https://docs.google.com/document/d/1jxNMTlotmJ0GFZ1GUEQ3hfOOVLzMT6mvY8Ufo5RdErY/edit#heading=h.gptlbp92g8lj) a user sees when the host appears in the table. WDYT @romfreiman @avishayt?
I see some references to `createdAt` in the code but don't want to break anything by renaming those too. 🙂 Feel free to close this PR and tweak it elsewhere if we generally agree with this proposed change.

Relabels Created At column heading to Discovered At

---

src/components/clusterConfiguration/discoveryImageModal.tsx

Adds three sentences to the ISO modal to clarify the boot order requirements that have been confusing folks. We can do better than this eventually, but this should help a little for now.

Add boot order instructions to ISO modal

---

src/components/ui/table/sortable.tsx

Given that I didn't test this locally and don't know React, I would be shocked if this is correct. Feel free to close and fix elsewhere. 🙂
This PR tries to remove two button-related classes on `.pf-c-table__button-content` that aren't needed, fixing the styling to go from this:
To this:

Fix the cluster table header styling

---

src/api/axiosClient.ts
src/api/clusters.ts
src/components/clusters/Clusters.tsx
src/components/clusters/newClusterModal.tsx
src/components/ui/AlertsSection/index.tsx

- fix axios client export
- fix getClusters url
- hide alerts section when empty
Delete button is now clickable (not hidden behind empty AlertsSection

Fix new cluster modal redirect

---

src/api/clusters.ts
src/components/clusterConfiguration/DiscoveryImageForm.tsx
src/components/clusterConfiguration/DiscoveryImageSummary.tsx
src/components/clusterConfiguration/discoveryImageModal.tsx

This changes the discovery modal behavior - after the download is ready
the modal does not close and provides an ISO URL to be coppied and a button
to trigger a download via browser.

Add ISO link to ISO download dialog

---

src/components/clusterConfiguration/NetworkConfiguration.tsx

Emphasize on 'Base DNS Domain' help text that its value can
be changed until invoking the cluster installation flow.

update base dns helper text

---

src/components/hosts/HostsTable.tsx
src/components/hosts/utils.ts

- Whitelist states on host actions
- Don't show host actions on expanded row
- Consider cluster status when determining host action availability

Don't show host actions on expended row

---

src/components/clusterConfiguration/ClusterConfigurationForm.tsx
src/components/clusterDetail/ClusterDetail.tsx
src/components/hosts/HostsTable.tsx

Tweaks:
- Removes the word "History" to be more concise but still clear (and align with OCP's wording a bit, even though those events are different)
- Rephrases `Events for the X host` to `Host Events: X` to be more concise, clear, and align with `Cluster Events`

Update events wording

---

src/components/clusterConfiguration/NetworkConfiguration.tsx

Based on some feedback we received:
> nit: I would change from Red Hat DNS service to "Temporary OpenShift POC domain name"?
I tweaked this suggestion a bit to avoid saying POC (which we would have to spell out) while still emphasizing even further that this option should only be used for temporary clusters.

Adjust DNS checkbox label

---

src/components/clusterConfiguration/ClusterSshKeyField.tsx
src/components/clusterConfiguration/DiscoveryImageForm.tsx
src/components/ui/formik/CheckboxField.tsx
src/components/ui/formik/InputField.tsx
src/components/ui/formik/SelectField.tsx
src/components/ui/formik/TextAreaField.tsx
src/components/ui/formik/TextAreaSecretField.tsx
src/components/ui/formik/types.ts
src/components/ui/formik/utils.ts

Fixes conflicting IDs in case of a modal rendered over a form, both containing the same element ID.
Example for the SSH public key:
- `form-input-sshPublicKey-discovery-field` in the Disccovery ISO modal
- `form-input-sshPublicKey-field` - on the Cluster configuration page
Prior this patch, these two element IDs were equal.

Make html element IDs unique

---

src/components/clusterConfiguration/ClusterConfigurationForm.tsx

Breaks data-type conversion (number is expected)

Do not pass clusterNetworkHostPrefix as empty string

---

src/components/clusters/ClusterStatus.tsx
src/components/hosts/HostStatus.tsx

Typescript will fail if new cluster/host status is added to the API
but list of icons does not reflect that.
Cluster in "finalizing" is fixed.

Let typescript guard missing status icons

---

src/components/clusterConfiguration/ClusterConfigurationForm.tsx
src/components/ui/formik/validationSchemas.ts

Backend provides defaults for them.
In addition, new `.requiredOnceSet()` validation schema is introduced and used for the `baseDNS` and both VIPs fields.

CIDR fields are required

---

src/components/clusterDetail/ClusterProgress.tsx
src/components/ui/DetailList.tsx

With this patch the cluster status HTML element on the cluster detail page looks like:
```
<dd id="cluster-progress-status-value" data-pf-content="true" class="">Installing</dd>
````

Add HTML IDs to cluster progress status info

---

src/api/utils.ts
src/components/clusterConfiguration/ClusterValidationSection.tsx
src/components/clusterConfiguration/clusterValidations.ts
src/types/clusters.ts

The validation messages are taken directly from the backend and need polishing. Ideally we define validation messages on the client side and map them to backend validation id+status combination. This will allow easy i18n.

Add backend-based cluster validations

---

src/components/clusterConfiguration/BasicNetworkFields.tsx
src/components/clusterConfiguration/ClusterConfigurationForm.tsx
src/components/clusterConfiguration/NetworkConfiguration.tsx
src/components/clusterConfiguration/utils.ts
src/components/ui/formik/SwitchField.tsx
src/components/ui/formik/index.tsx
src/components/ui/formik/types.ts
src/components/ui/formik/validationSchemas.ts

Just a simple switch to enable VIP DHCP allocation
DHCP off - user has to specify api and ingress VIP
DHCP on - api and ingress VIP fields are hidden
JIRA https://issues.redhat.com/browse/MGMT-1751
@andybraren I guess we will want to add some help text and possibly rename the switch too.

Add VIP DHCP configuration

---

src/components/clusterConfiguration/ClusterSshKeyField.tsx

Changes `a` to `an`. That's it.

Tweak SSH key description wording

---

src/components/clusterConfiguration/NetworkConfiguration.tsx

Adjusts the wording of the DNS-related fields:
- Makes it clear that the temporary domain is only good for ~60 days (discussed in #97, FYI @ohadlevy)
- Renames `Base DNS Domain` to just `Base Domain` because that's how the [4.5 documentation](https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-bare-metal.html) refers to it and @nirfarkas' [fresh eyes](https://github.com/mareklibra/facet-lib/pull/97#issuecomment-664795981) are a treasure
- Attempts to add a line break so that the full address is always on a new line (let me know if I did it wrong)
- Less text to read which is good

Adjust DNS-related field text

---

src/config/constants.ts
src/hacks.ts

In addition to this, we can add facet-lib version to the OCM About modal dialog.

Log facet-lib version

---

src/components/clusterConfiguration/BasicNetworkFields.tsx
src/components/clusterConfiguration/utils.ts

Depends on https://github.com/mareklibra/facet-lib/pull/196
- if DHCP enabled, populate hostSubnet initial value from machine-network-cidr
- display requestedHostname in list of hostnames in available subnets select
- don't populate vip initial values if DHCP is on. When user disables DHCP
they need to set the VIPs manually

Fix machine cidr dhcp

---

src/components/clusters/Clusters.tsx

The current title of `Managed Clusters` is easy to confuse with OCM's regular `Clusters` page, which could make it seem like the other clusters "disappeared" from the user's list.
This PR changes the title to `Assisted Bare Metal Clusters` to more clearly distinguish our list from the regular/full one (until we can be fully integrated 🙂).

Change clusters list title

---

src/components/clusterConfiguration/ProxyFields.tsx
src/components/ui/formik/validationSchemas.ts

Based on: https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-configure-proxy_installing-restricted-networks-bare-metal
In addition, a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1877486 is provided.

MGMT-1962 Accept network CIDR as noProxy

---

src/api/clusters.ts
src/components/hosts/HostsTable.tsx

No need to re-fetch cluster to get the data up to date

Enable/Disable actions API return cluster resource

---

src/api/utils.ts

This change ensures that objects in error message get stringified
to ensure correct formating in Sentry UI
This is how the messages look without this change:

Fix error message in Sentry

---

src/components/clusters/NewClusterPage.tsx
src/components/clusters/PullSecret.tsx
src/components/ui/PopoverIcon.tsx
src/components/ui/formik/InputField.tsx
src/components/ui/formik/SelectField.tsx
src/components/ui/formik/SwitchField.tsx
src/components/ui/formik/TextAreaField.tsx
src/components/ui/formik/UploadField.tsx
src/components/ui/formik/types.ts
src/config/constants.ts

With this patch, the OCM user can edit pull-secret. Since this is expected to be a rare case, the field is not visible by default. Prior this patch, this field was hidden in OCM.
The pull-secret is not visible by default (is collapsed) but the user canexpand an area to edit it.
If pull-secret automatic fetch fails, the area is expanded by default (plus error message is shown).
Outside of the OCM, the pull-secret filed is always rendered.

MGMT-1917 Make pull secret editable in OCM

---

src/components/hosts/HostsTable.css

The HostsTable height is not recalculated after collapsing a row which is causing "blowing" all the row heights.
The issue was observed in Firefox but not in Chrome.
I will try to reproduce that without AI context and report to Patternfly.

OCPBUGSM-17672 Hotfix HostsTable height after collapsing detail

---

src/components/clusters/ClustersTable.tsx

The state of filters on the Cluster list page stays persistent
unless the application is opened in a new tab.
The state survives page refresh (F5) or navigatino within the application.

MGMT-1822 Make Cluster list filters persistent

---

src/components/hosts/HostValidationGroups.tsx

Display only failing validations in host status popover. Display pending
validations only if there are no failing ones (should not really ever happen).
The reason for this is that pending validations are always pending due to
another validation being failed.
The validation group status is 'Pending input' if there are any pending validations.
This is to better communicate that validations are failing due to us waiting for
user input.

Don't display pending validations in the host status popover

---

src/api/utils.ts
src/components/clusterConfiguration/ClusterConfigurationForm.tsx
src/sentry.ts

The event is falsely marked as an error since it is result of an user's action - clicking on Cancel during long-running task of generating an ISO image. So far we want to track these actions, so marking it by Info level only.

Fix strict error sentry logging for canceled requests

---

src/api/swagger.yaml
src/api/types.ts
src/components/clusters/ClusterStatus.tsx
src/components/hosts/HostStatus.tsx
src/config/constants.ts

Updated swagger.
In addition, basic support for new host's `added-to-existing-cluster` and cluster's `adding-hosts` statuses is provided to unblock development of other feature. This needs to be revisited in a follow-up.

Update API + new host/cluster statuses

---

src/components/clusters/ClusterStatus.tsx
src/components/hosts/HostStatus.tsx
src/config/constants.ts

Follow-up for added host's `added-to-existing-cluster` and cluster's `adding-hosts` statuses.
If the host is in `added-to-existing-cluster` status:
- status icon is `InProgressIcon`
- status detail text: `Host is added to existing cluster`
If the cluster is in `adding-hosts` status:
- icon: `InProgressIcon`
- Status label: `Adding hosts`
I do not see effect of these new states on our `canDo...()` UI checks atm.
Depends on:

Review new host-adding states

---

src/components/hosts/HostStatus.tsx
src/components/hosts/HostValidationGroups.css
src/components/hosts/HostValidationGroups.tsx
src/components/hosts/Hostname.tsx
src/components/hosts/HostsTable.tsx

The first user action is the hostname change in case of 'hostname-unique' or 'hostname-valid' host state.

OCPBUGSM-18591 Host status alerts can be extended for user actions

---

src/components/clusters/Clusters.tsx
src/components/clusters/ClustersListToolbar.tsx
src/components/clusters/ClustersTable.tsx
src/components/ui/ClusterEventsToolbar.tsx

Depends on https://github.com/mareklibra/facet-lib/pull/255
Move the cluster list toolbar actions above the table
To align to OCM cluster list the botton toolbar is removed in clusters list and actions are put into clusters table toolbar.
Add 'refresh' button to cluster list toolbar

Move the cluster list toolbar actions above the table to align with OCM

---

src/components/ui/ClusterEventsToolbar.tsx

Add a single checkbox with both functionalities - clear all and select all

Bug 1890504: Add select-all and clear-all checkbox for cluster events

---

src/components/clusters/ClusterBreadcrumbs.tsx
src/components/clusters/Clusters.tsx

In OCM, the AI list newly contains breadcrumbs `Clusters > Assisted Bare Metal Clusters`.
In stand-alone application, the AI list stays without breadcrumbs (make no sense there and look weird).
All other occurrences of breadcrumbs have these two items instead of former single `Clusters`.
The breadcrumb items newly:
- `Clusters`        --> OCM cluster list
- `Clusters > Assisted Bare Metal Clusters `         --> "our" AI list
- `Clusters > Assisted Bare Metal Clusters > New cluster`
- `Clusters > Assisted Bare Metal Clusters > my-cluster-name`

MGMT-2339 Breadcrumb navigates to OCM list

---

src/components/ui/formik/validationSchemas.ts

MGMT-2631: Change cluster name length limit to 54

---

.github/workflows/release.yaml

Avoid use of set-env in GitHub actions

---

src/components/clusters/ClusterPage.tsx

Day 2 cluster has constant status 'adding-hosts'. This change makes the
decision making on what to display on ClusterPage by cluster.status.

Decide the ClusterPage content by cluster.status

---

src/api/clusters.ts
src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
src/components/AddBareMetalHosts/utils.ts

Since API has been extended for openshift_cluster_id, we do not need to assume
that the Day 2 cluster is stored with the AI ID equal to the OpenShift ID
but rather look-up it based on the ID value.
---
The look-up requires https://github.com/openshift/assisted-service/commit/6eac158645777354c302f9658be45b2d0cc78ec2, which is expected to be deployed to prod on Nov 30th. Anyway, the code is working even without this patch.

Use query to look-up Day 2 cluster

---

src/components/clusterConfiguration/discoveryImageModal.tsx

Use 'generate-discovery-iso-modal' instead of former 'pf-modal-part-XY'.

Discovery ISO modal has stable ID

---

src/components/clusterConfiguration/AdvancedNetworkFields.tsx
src/components/clusterConfiguration/ClusterConfigurationForm.tsx
src/components/clusterConfiguration/NetworkConfiguration.tsx
src/components/clusterConfiguration/utils.ts
src/components/hosts/HostRowDetail.tsx
src/components/hosts/HostStatus.tsx
src/components/hosts/HostValidationGroups.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NtpValidationStatus.tsx
src/components/ui/formik/validationSchemas.ts
src/components/ui/table/utils.ts
src/config/constants.ts

- Add NTP source input field in advanced network configuration
- Add support for ntp-synced backend network validation
- Add NTP status to host detail
Depends on https://github.com/openshift/assisted-service/pull/675
Failing validation + NTP status unreachable:
Configuring NTP source:
NTP synced:

MGMT-3077 Add support for NTP configuration

---

src/components/hosts/HostPropertyValidationPopover.tsx
src/components/hosts/HostValidationGroups.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NtpValidationStatus.tsx
src/config/constants.ts

Depends on: https://github.com/mareklibra/facet-lib/pull/327
- Introduces HostPropetyValidationPopover component which wraps host property in a Popover based on a validation status
- Adds validation popovers for host memory, cpu and disk properties
- Converts existing NtpValidationStatus to use HostPropertyValidationPopover

MGMT-1614 Report failed validation on host HW fields

---

src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
src/components/AddBareMetalHosts/utils.ts
src/config/constants.ts

Might happen during cluster upgrade.

BZ 1905558: Handle missing openshift_version from OCM

---

src/components/hosts/HostsTable.tsx

Some minor capitalization tweaks based on OCM conventions, and adding the word `host` to Reset/Deleteto for extra clarity.

Tweak Day 2 host action labels

---

src/components/hosts/HostsTable.tsx
src/components/hosts/utils.ts

Backend support needs more time to land in production. Will be re-enabled in a week.

Tentatively disabled day2 Install Host

---

src/components/clusterConfiguration/AdvancedNetworkFields.tsx
src/components/ui/formik/types.ts
src/components/ui/formik/validationSchemas.ts
src/config/constants.ts

Depends on https://github.com/openshift/assisted-service/pull/801
- Add spellCheck prop to TextareaField
- Set additionalNtpSource default to undefined to match the backend

OCPBUGSM-21366 Support comma-separated NTP sources list

---

src/components/clusterConfiguration/utils.ts

This is just a suggestion, feel free to close the PR / make changes.
Instead of:
Show `fe70::/64 (fe80::-fe80::ffff:ffff:ffff:ffff)`
The subnet, along with the full start and end address, look rather awkward inside the dropdown because they form a very long string.

MGMT-3487 - Use IPv6 short form in subnet selection dropdown

---

src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
src/components/Router.tsx
src/components/ui/AssistedUILibVersion.tsx
src/components/ui/index.ts

The library version is stored in the DOM:
```
<div data-test-id="assisted-ui-lib-version" hidden="">1.5.2-1</div>
```
Can be used by Cypress CI for better reporting.

Add AssistedUILibVersion component

---

src/api/axiosClient.ts
src/api/versions.ts
src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
src/components/OpenshiftVersionsContextProvider.tsx
src/components/Router.tsx
src/components/clusterDetail/ClusterInstallationError.tsx
src/components/clusters/NewClusterPage.tsx
src/config/constants.ts
src/types/versions.ts

MGMT-3382: Retrieve OCP versions from API

---

src/components/hosts/HostRowDetail.tsx
src/components/hosts/utils.ts

Addresses an issue where the "Hardware Type" value in physical hosts was missing.

BZ 1910402:  missing "Hardware Type" value in physical hosts

---

src/components/clusterConfiguration/NetworkConfiguration.tsx

- Removes NTP mention from Advanced Networking section

Bug 1919626 - [Assisted-4.7] [UI] NTP should not be included in Advanced Networking description

---

README.md

This PR adds an explanation to the main README file about how to troubleshoot the `inotify` watchers limit issue.

docs: How to troubleshoot `inotify` watchers error

---

src/components/ui/formik/validationSchemas.ts

Yup.url() does not allow ipv6 based URLs
Before:
After:

Fix HTTP Proxy URL validation

---

src/components/clusterWizard/ClusterDetails.tsx
src/components/clusterWizard/ClusterWizardStep.tsx
src/components/clusterWizard/NewClusterWizard.tsx
src/components/clusterWizard/wizardTransition.ts
src/components/clusters/NewClusterPage.tsx
src/components/ui/formik/validationSchemas.ts
src/types/clusters.ts

- NewClusterPage now renders NewClusterWizard instead of NewClusterForm
- ClusterDetails wizard step is capable of creating/updating the cluster
- single node, openshift version and pull secret are not allowed to be
updated
Next steps:
- use ClusterWizardToolbar in ClusterDetails
- validate cluster name + dns domain for uniqueness rather than just cluster name
- explore possibility to edit pull secret?
- align to wireframes

MGMT-3234 Convert NewClusterPage to use wizard

---

src/components/clusterDetail/ClusterDetail.tsx

- Adds a missing warning when the cluster is in `installing-pending-user-action` (e. g. wrong boot order).

MGMT-2632 Adds missing warning

---

src/components/clusterConfiguration/ClusterValidationSection.tsx
src/components/clusterConfiguration/NetworkConfigurationForm.tsx
src/components/clusterWizard/BaremetalDiscovery.tsx
src/components/clusterWizard/ClusterWizardStep.tsx
src/components/clusterWizard/ClusterWizardToolbar.tsx
src/components/clusterWizard/wizardTransition.ts
src/components/clusterWizard/wizardTransitions.test.ts
src/components/hosts/HardwareStatus.tsx
src/components/hosts/HostStatus.tsx
src/config/constants.ts
src/types/clusters.ts
src/types/hosts.ts

- Use validation map to calculate cluster/host validationInfo and
status
- Use calculated status to determine transition to next step
- Adjust ClusterWizardToolbar to display validations toggle properly
- Simplify 'canNext' functions
- Enable 'Next' button in case when form is dirty and valid to allow
user saving the changes regardless of backend validations

Introduce wizard step validation mapping

---

package.json
src/components/ui/formik/validationSchemas.ts

Previously the message bellow couldn't be displayed because we were validating the input is a valid IP address (v4 or v6) but not a valid CIDR string.

BZ-1877838 CIDR fields display wrong validation message

---

src/components/clusterDetail/FailedHostsWarning.tsx

- Removes the timeout message when a master node has a wrong boot order

BZ-1922810 wrong message displays: node has 30 minutes timeout

---

src/components/clusterConfiguration/OpenShiftVersionSelect.tsx
src/components/clusters/NewClusterPage.tsx
src/components/ui/formik/SingleNodeCheckbox.tsx
src/config/constants.ts

- If user enables SNO, the list of available OCP versions is reduced to 4.8 and higher
- SNO option will be hidden if there is no version which supports it available

MGMT-4110 SNO is only available in selected OCP versions

---

src/components/ui/formik/validationSchemas.ts

Fixes a bug related to the validation of the CIDR fields that occurs when the value is expressed in IPv6 short form (e.g. 2002:db8::/53).

MGMT-4272 Fixes CIDR validation for IPv6

---

src/components/clusters/NewClusterPage.css

When the window height is too small the pull secret text area gets squished down to height 0 and it's impossible/hard to interact with it.
Not sure if this is the correct way to fix it (and also not sure how to test it, it worked locally in my browser dev window). 
Feel free to modify the PR / fix it / close it / recreate it however you see fit

Min height 200 pull secret text area

---

src/components/clusterConfiguration/OpenShiftVersionSelect.tsx
src/components/clusterWizard/ClusterDetails.tsx

It is not possible to update openshiftVersion once the cluster has been created.
This change disables the version select field if cluster exists

OCPBUGSM-25836 Disable version select if cluster exists

---

src/components/hosts/BaremetalDiscoveryHostsTable.tsx
src/components/hosts/NetworkingHostsTable.tsx

Since host tables can show validations from several validation groups (Hardware, Network, ...), labeling the status column as 'Hardware Status' and 'Network Status' is misleading. This rolls back to 'Status' label on all tables.

OCPBUGSM-25659 Rename Hardware and Network status column to 'Status'

---

src/components/clusterConfiguration/ProxyFields.tsx

Configure HTTP Proxy" string should change to "Configure Proxy"
Reported in: assisted-ui-lib version:  0.0.8-wizard
**MUST be merged into `wizard` branch for QE validation.**

BZ-1934610 Updates the Configure HTTP Proxy label

---

src/components/hosts/HostStatus.tsx

Installed hosts should show progress in the status popover rather than
validations info

Show host progress on installed host

---

src/components/clusterConfiguration/ClusterConfiguration.tsx
src/components/clusterConfiguration/ClusterDefaultConfigurationContext.tsx
src/components/clusters/ClusterPage.tsx
src/components/clusters/NewClusterPage.tsx

If the `clusters/default-config` API endpoint is not available the provider will render an "error" UI and a "loading" UI while it is fetching data.
The end goal is to prevent the form to be initially filled with empty data and then updated with default values coming from the API; that is what is enabling the checkbox.

BZ-1936360 Advanced networking checkbox is enabled when creating new cluster

---

src/components/clusterConfiguration/ClusterValidationSection.tsx
src/components/clusterWizard/BaremetalDiscovery.tsx
src/components/clusterWizard/ClusterWizardToolbar.tsx

when validationsInfo is not available.
That might happen right after cluster's creation.

BZ 1938969: Disable Back button on BareMetalDiscovery

---

src/components/hosts/VMRebootConfigurationInfo.tsx

Prior this patch, the message was marked as warning.

BZ 1934198: Change the reboot config text to info-level

---

src/components/ui/formik/validationSchemas.ts

- Cover the case when the user enters only numbers (BZ-1934752)
- Implements the validation for the minimal allowed format: { "auth": {} }

BZ-1934591 No helper message for invalid pull secret is displayed

---

src/components/clusters/ClusterStatus.tsx
src/components/clusters/ClustersTable.tsx
src/components/hosts/BaremetalDiscoveryHostsTable.tsx
src/components/hosts/HardwareStatus.tsx
src/components/hosts/HostStatus.tsx
src/components/hosts/Hostname.tsx
src/components/hosts/HostsCount.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NetworkingHostsTable.tsx
src/components/hosts/NetworkingStatus.tsx
src/components/hosts/RoleCell.tsx
src/components/hosts/RoleDropdown.tsx
src/components/ui/SimpleDropdown.tsx
src/selectors/clusters.tsx

This PR adds `data-testid` attributes to the ClustersTable:
and the *HostsTable:
1. As can be seen in the screenshot, each row in the host table has appended its row number (obeying the table's sort value), so the first row will always have `data-testid="host-row-0"` and the second will have `data-testid="host-row-2"` (why? because the rows with odd numbers correspond to the host details. BTW haven't deal with it as part of this PR) no matter the sorting value of the table. Unfortunately, these test-id's cannot be based on the hosts' names because after being discovered they're all called the same (localhost) and only after changing them their names' uniqueness is enforced. 
2. I haven't removed any `id`s, intentionally, to prevent breaking the existing automated tests. We can encourage …

BZ-1917423 Table elements should be identifiable by ID

---

src/components/clusterWizard/ClusterDetails.tsx
src/components/clusterWizard/ClusterWizardToolbar.tsx

The `ClusterWizardToolbar` has gotten too complex which is completely unnecessary. The toolbar should be a simple presentational component (or a set of components for buttons for example) and the individual step components should define its behaviour for each step separately.

Disable Next button and show 'Saving changes' when creating cluster

---

src/components/clusterWizard/BaremetalDiscovery.tsx

Just the Next button is disabled in that case.
A descriptive info message is rendered.
Follow-up for: #512

BZ1938969: Do not disable back button if validationsInfo is missing

---

src/components/clusterDetail/ClusterDetail.tsx

Clusters which don't have monitored_operators will display credentials
once the cluster gets to 'installed' state

BZ 1945119 Maintain backwards compatibility for cluster credentials

---

src/components/clusters/ClusterStatus.tsx
src/components/hosts/HardwareStatus.tsx
src/components/hosts/HostRowDetail.tsx
src/components/hosts/HostStatus.tsx
src/components/hosts/Hostname.tsx
src/components/hosts/HostsCount.tsx
src/components/hosts/HostsDiscoveryTable.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NetworkingHostsTable.tsx
src/components/hosts/NetworkingStatus.tsx
src/components/hosts/RoleCell.tsx
src/components/hosts/RoleDropdown.tsx
src/components/ui/DetailList.tsx
src/components/ui/SimpleDropdown.tsx
src/custom.d.ts
src/selectors/clusters.tsx

Adds `data-testid` attrs to missing elements in the host detail subtable.

BZ-1917423 - Table elements should be identifiable by ID

---

src/api/clusters.ts
src/components/clusterConfiguration/HostInventory.tsx
src/components/clusterConfiguration/utils.ts
src/components/clusterWizard/HostDiscovery.tsx
src/config/constants.ts
src/features/featureGate.tsx
src/types/clusters.ts

TODO:
Just temporarily placed on the BM Discovery step until we have profiles.

MGMT-4752: Add CNV operator

---

src/components/hosts/DiskRole.tsx
src/components/hosts/HostRowDetail.tsx

1. When calling BE with disks_selected_config use the disk ID as the disk ID and not Name
2. When identifying the disks in the list - use Id and not path (/dev/Name)

MGMT-4051 Use disk ID as disk identifier in UI

---

src/components/clusterConfiguration/NetworkConfigurationForm.tsx
src/components/clusterWizard/wizardTransition.ts
src/components/clusterWizard/wizardTransitions.test.ts
src/types/hosts.ts

Important:
We still keep `container-images-available` among soft-validations until https://issues.redhat.com/browse/MGMT-5265 lands in production.

MGMT-5433 Add support for disabled validations

---

src/components/AddHosts/AddHosts.tsx
src/components/hosts/HostsCount.tsx
src/components/hosts/HostsDiscoveryTable.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NetworkingHostsTable.tsx
src/components/hosts/utils.ts
src/selectors/clusters.tsx

Instead of processing Cluster.hosts directly.
For optimization purpose, the API does not populate Cluster.hosts
when querying a list of clusters.

MGMT-4659: Use Cluster.*host_count

---

src/components/clusterConfiguration/HostInventory.tsx
src/components/clusterConfiguration/NetworkConfigurationForm.tsx
src/components/clusterConfiguration/ReviewStep.tsx
src/components/clusterWizard/ClusterDetails.tsx
src/components/clusterWizard/ClusterWizardStep.css
src/components/clusterWizard/ClusterWizardStep.tsx
src/components/clusterWizard/ClusterWizardStepHeader.tsx

The button floating did not work well with Stack and Grid used in wizard step
content. The button prevented grid from spanning full width. This change
puts the button into the grid next to wizard step title.

Fix positioning of Events Dialog in Wizard steps

---

src/components/clusterDetail/AssistedInstallerDetailCard.tsx
src/components/clusters/ClusterPage.tsx
src/components/clusters/clusterPolling.ts
src/features/clusters/currentClusterSlice.ts

Just a small improvement - we dont have to use `useSelector` anymore because `useClusterPolling` returns the data we need.

Cluster polling hook returns data, state and error

---

src/components/clusters/ClusterPage.tsx
src/components/clusters/clusterPolling.ts

This PR modifies the polling mechanism so it doesn't continues fetching
when there is an API error.
Also, the 'try again' action in the `ErrorState` component will trigger a full page reload only when the received HTTP status code is 401 Unauthorized, this is done in order to force OCM to send the users to the login page so they can renew their token.

BZ-1928653 Fixes flooding sentry when there is and API error

---

src/components/clusterDetail/ClusterProgress.tsx
src/components/clusterDetail/OperatorsProgressItem.tsx
src/components/hosts/utils.ts

This PR tweaks the progress bar calculation in a way that the hosts progress account for 75% of the overall progress and the operators for the remaining 25%

MGMT-5382 Include operators' installation progress as part of the total installation progress

---

src/components/AddHosts/InventoryAddHost.tsx
src/components/clusterDetail/ClusterDetail.tsx
src/components/clusterDetail/ClusterInstallationProgressCard.tsx
src/components/clusters/ClusterStatus.tsx
src/components/hosts/ClusterHostsTable.tsx
src/components/hosts/HardwareStatus.tsx
src/components/hosts/HostRowDetail.tsx
src/components/hosts/HostStatus.tsx
src/components/hosts/HostValidationGroups.tsx
src/components/hosts/Hostname.tsx
src/components/hosts/HostsDiscoveryTable.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NetworkingHostsTable.tsx
src/components/hosts/NetworkingStatus.tsx
src/components/hosts/index.ts
src/components/ui/DetailList.tsx
src/custom.d.ts
src/types/index.ts

This PR changes HostsTable to make it reusable for other environments.
The table now accepts callbacks for all actions so the consumer can use its own way of opening modals.
If no callback for the action is provided, then its not shown (the table becomes read-only)
Example of consuming the table is here https://github.com/rawagner/dynamic-cim/blob/infra_hosts/src/components/Agent/AgentTable.tsx#L24
The `AgentTable` fetches Agent CR from k8s, maps the fields of the CR to format expected by `HostsTable` (we will need some util method to do this in the future). And passes the mapped hosts to `HostsTable`. Since no callbacks for the actions are provided, the table is in read-only mode.
`HostsTable` in OpenShift Console
Expanded state

Make HostsTable more generic

---

src/components/clusterConfiguration/NetworkConfiguration.tsx

The radio buttons are removed temporarily until the BE implements
support for non-SNO

MGMT-6608 Do not allow the user to select user-managed networking in non-SNO installations

---

src/components/clusterWizard/ClusterDetails.tsx

Before this PR we were calling the PATCH API on every transition from the "Cluster Details" to the "Host Discovery" (first to second step) even though the form remains pristine.
For the rest of the steps there is no PATCH API call when the form is pristine. This PR prevents calling the PATCH API when the form is pristine during the first transition only.

BZ-1953528 Don't call PATCH API if the form hasn't changed

---

scripts/sync-dist.sh

`rsync` fails if the `dist` folder doesn't exist, this happens normally after setting up a local fork of the project. This PR creates an empty `dist` folder only if it doesn't exist already.

chore: do not fail if dist folder doesn't exist yet

---

src/components/ClusterDeployment/ClusterDeploymentDetails.tsx
src/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx
src/components/ClusterDeployment/ClusterDeploymentHostsTable.tsx
src/components/ClusterDeployment/ClusterDeploymentNetworking.tsx
src/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
src/components/ClusterDeployment/ClusterDeploymentWizard.tsx
src/components/ClusterDeployment/ClusterDeploymentWizardNavigation.tsx
src/components/ClusterDeployment/constants.ts
src/components/ClusterDeployment/types.ts
src/components/clusterConfiguration/ClusterDefaultConfigurationContext.tsx
src/components/clusterConfiguration/NetworkConfiguration.tsx
src/components/clusterConfiguration/NetworkConfigurationForm.tsx
src/components/clusterConfiguration/NetworkConfigurationFormFields.tsx
src/components/clusterConfiguration/SNOControlGroup.tsx
src/components/clusterConfiguration/SNODisclaimer.tsx
src/components/clusterConfiguration/networkConfigurationValidation.ts
src/components/clusterConfiguration/utils.ts
src/components/clusterWizard/ClusterDetailsFormFields.tsx
src/components/clusterWizard/networkingSteps/AvailableSubnetsControl.tsx
src/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
src/components/hosts/ClusterHostsTable.tsx
src/components/hosts/HostsCount.tsx
src/components/hosts/HostsTable.tsx
src/components/hosts/NetworkingHostsTable.tsx
src/components/hosts/RoleCell.tsx
src/components/ui/formik/validationSchemas.ts

Depends on:
Required by:
- https://github.com/rawagner/dynamic-cim/pull/17
TODO:

MGMT-6447 Add Networking step to the ClusterDeployment wizard

---

src/components/hosts/EditHostForm.tsx

Changed 'Requested hostname' to 'Requested Hostname' for keeping consistency.

Capital letter for Hostname in edit host

---

package.json
yarn.lock

Will be replaced by @openshift-console/dynamic-plugin-sdk once
openshift-console SDK [changes](https://github.com/rawagner/console/tree/cim) get merged.

Add console-sdk-ai-lib dependency

---

src/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx
src/components/clusterConfiguration/HostInventory.tsx
src/components/ui/PopoverIcon.tsx
src/components/ui/formik/PullSecretField.tsx

[BZ-1975228](https://bugzilla.redhat.com/show_bug.cgi?id=1975228)
Before:
https://user-images.githubusercontent.com/77008341/125964772-b639dad7-4c5d-4730-9249-651ac8e300ce.mp4
After:
https://user-images.githubusercontent.com/77008341/125964506-03e57eb8-6121-46bc-bc8c-aa8e8eaeb209.mp4

BZ-1975228: CNV help popover arrow is misplaced

---

src/cim/types/k8s/index.ts
src/cim/types/k8s/infra-env-k8s-resource.ts
src/common/api/swagger.yaml
src/common/api/types.ts

*Merge last!*
This PR syncs everything in the swagger.yaml with the one from assisted-service.
Please be aware that the BE API declares now a type called **InfraEnv**. We also had such a type in the CIM folder which wasn't being consumed by anything (please double-check me). In order to pass CI, I had to rename our type to **CIMInfraEnv**, hope this will be good enough.

NO-ISSUE: Updates swagger.yaml

---

src/common/components/ui/eventsModal.tsx

Fixes an issue introduced in #714 
According to PF, when using a Modal component with `hasNoBodyWrapper` we must add an `aria-label` as well.

NO-ISSUE: Adds missing aria label

---

src/common/components/ui/ClusterEventsToolbar.tsx

Restores missing `cluster-events-toolbar` id, the issue was introduced in #714

NO-ISSUE: Update ClusterEventsToolbar.tsx

---

src/common/components/ui/formik/validationSchemas.ts

https://issues.redhat.com/browse/MGMT-6644
Before, the base domain name length validation in the UI gave an error when the Base Domain length was greater than 255, but this doesn't match the BE validation. 
I omitted this validation as we agreed on Standup.

MGMT-6644: The validation of the Base Domain length was omitted

---

src/common/components/clusterConfiguration/NetworkConfiguration.tsx

Related to #611
[MGMT-2754](https://issues.redhat.com/browse/MGMT-2754)
Signed-off-by: jkilzi <jkilzi@redhat.com>

MGMT-2754: Allow users to select "user-managed" networking for non-SNO clusters.

---

src/common/components/hosts/EditHostForm.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1898550
Both localhost and localhost.localdomain host names are not be allowed:

BZ-1898550: Fix validation of forbidden host names in UI

---

src/ocm/components/hosts/use-hosts-table.tsx

The Generate Discovery ISO button is not supposed to be a part of the empty host table according to the new designs.

NO-ISSUE - Remove the Generate Discovery ISO button from the host table

---

.gitignore
.idea/.gitignore
.idea/assisted-ui-lib.iml
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/jsLibraryMappings.xml
.idea/jsLinters/eslint.xml
.idea/modules.xml
.idea/prettier.xml
.idea/swagger-settings.xml
.idea/vcs.xml

This PR allows sharing the IDE's configuration (VSCode and Jetbrains).
In case some specific files or folders need to be excluded, there's also a specific `.gitignore` file inside each corresponding folder.
(Inside the .idea folder, the code-styling settings are produced automatically from our Prettier rules)

NO-ISSUE: Adds .idea folder

---

src/cim/components/Agent/AgentsSelectionHostCountAlerts.tsx
src/cim/components/Agent/AgentsSelectionHostCountLabelIcon.tsx
src/cim/components/Agent/AgentsSelectionTable.tsx
src/cim/components/Agent/AgentsSelectionUtils.ts
src/cim/components/Agent/BMCForm.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelection.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionAdvanced.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionBasic.tsx
src/cim/components/ClusterDeployment/ClusterScaleUpAutoHostsSelection.tsx
src/cim/components/ClusterDeployment/LabelsSelector.tsx
src/cim/components/ClusterDeployment/LocationsSelector.tsx
src/cim/components/ClusterDeployment/ScaleUpForm.tsx
src/cim/components/ClusterDeployment/label-selector.css
src/cim/components/ClusterDeployment/locations-selector.css
src/cim/components/ClusterDeployment/types.ts
src/cim/components/helpers/agentClusterInstall.ts
src/cim/components/helpers/agents.ts
src/cim/components/helpers/clusterDeployment.ts
src/cim/components/helpers/index.ts
src/cim/components/modals/ScaleUpModal.tsx
src/cim/components/modals/index.ts
src/common/components/ui/formik/NumberInputField.tsx
src/common/components/ui/formik/types.ts

- Introduce Modal and Form for adding hosts to the cluster
- Replicate Basic/Advanced functionality from Host selection wizard step
- Refactor Host selection code to allow for reusability in scale up process
- Enhance NumberInputField

Add cluster scale up functionality to CIM

---

src/cim/components/helpers/versions.ts

Changes:
- sorted (descending)
- version label aligned with ACM wording
- non-available versions are filtered out
- fixed channel to support level mapping
Idea for future enhancement:
Add descriptions (sublabels) with full image name. To do so, the `FormSelect` and it's `FormOption` will need to be replaced by the PF's `Dropdown` component. Such change has wider impact on other existing flows.

Improve OCP versions listing in the ACM

---

src/ocm/adapters/LocalStorageBackedCache.ts
src/ocm/api/InfraEnvService.ts
src/ocm/api/clusters.ts
src/ocm/api/domains.tsx
src/ocm/api/versions.ts
src/ocm/components/clusterWizard/ClusterDetails.tsx

[MGMT-7719](https://issues.redhat.com/browse/MGMT-7719)
Implements Create cluster with v2 APIs only
Migrated:
- GET /v2/default-config
- GET /v2/domains/
- GET /v2/openshift-versions

MGMT-7719: New cluster page v2 API migration

---

src/common/components/hosts/tableUtils.tsx

https://issues.redhat.com/browse/MGMT-7489
before:
after:

MGMT-7489: fixed behavior of a long hostname in hosts table to become multiline like in cluster table

---

src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
src/cim/components/ClusterDeployment/LabelsSelector.tsx

- Fix host selection error handling
- Don't use the agent-infraenv matching label to filter out cluster agents
Fixes https://github.com/open-cluster-management/backlog/issues/16738

Fix edit cluster label saving as annotation

---

src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx

URL https://bugzilla.redhat.com/show_bug.cgi?id=1980801
Root caused by formik invoking validation on the initialValues prop when the intialTouched prop changes. The fix is to memoise the initialTouched prop

BZ-1980801: fixed disappearing error messages for invalid fields in network form

---

src/common/components/clusterDetail/ConsoleModal.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1995038
resolved typo in "Launch Openshift console" dialog: resolve.conf - > resolv.conf

BZ-1995038: Typo: resolve.conf

---

src/common/components/hosts/HostStatus.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1927737
When a new day2 host completes the installation, the instruction should explicitly state that the join request can take some time to appear in the Nodes section.
**Previous instruction:**
> To finish adding it to the cluster, approve its request to join in the Nodes section of the OpenShift console. It might take a few minutes till the node request gets available.
**New instruction (as suggested by UX):**
> To finish adding it to the cluster, approve its request to join. Note that it may take a few minutes for the join request to appear in the Nodes section.

BZ-1927737: Fixes a confusing instruction when adding host to an OS cluster

---

src/common/components/hosts/DiskRole.tsx
src/common/hooks/index.ts
src/common/hooks/useStateSafely.ts
src/ocm/components/clusterConfiguration/ReviewStep.tsx

This new hook is a drop-in replacement for `React.useState`.
Should be used when:
- The internal state of a component is altered by delegating the operation to a nested component.
- The internal state changes inside an async operation.
In general, this hook prevents changing the state of an unmounted component.

useStateSafely

---

src/common/components/clusterConfiguration/NetworkConfigurationTable.tsx
src/common/components/clusterConfiguration/utils.ts
src/common/components/hosts/RoleCell.tsx
src/common/components/hosts/RoleDropdown.tsx
src/common/components/hosts/tableUtils.tsx
src/common/components/hosts/utils.ts
src/common/types/clusters.ts
src/ocm/components/clusterConfiguration/HostInventory.tsx
src/ocm/components/clusterWizard/HostDiscovery.tsx
src/ocm/components/hosts/ClusterHostsTable.tsx
src/ocm/components/hosts/HostsDiscoveryTable.tsx

https://issues.redhat.com/browse/MGMT-4551
Added 'Run workloads on control plane nodes' switch
When there are less than 5 hosts - the switch is on and disabled
When there are 5 hosts and up - the switch is enabled and off by default
In the hosts table - if the switch is on, the role label is 'Control Plane, Worker' for master nodes
3 hosts:
5 hosts, switch is off:
5 hosts, switch is on:

MGMT-4551: Add 'Run workloads on control plane node' switch

---

src/common/components/hosts/Hostname.tsx
src/common/components/hosts/tableUtils.tsx
src/common/components/hosts/types.ts
src/common/components/hosts/utils.ts
src/ocm/components/hosts/ClusterHostsTable.tsx
src/ocm/components/hosts/HostsDiscoveryTable.tsx
src/ocm/components/hosts/use-hosts-table.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2000646
If the cluster is installed or in the process of installation the hostname won't be clickable and won't open the EditHostModal.

Removing EditHostModal after cluster installation

---

src/common/components/hosts/NtpValidationStatus.tsx

[BZ-1978297](https://bugzilla.redhat.com/show_bug.cgi?id=1978297)
The NTP status is not checked after the installation begins. Therefore the BE can no longer provide its status.
The UI hardcoded the pending value which is incorrect since it will never be changed to anything else.

BZ-1978297: Shows N/A NTP status after the installation begins

---

src/common/components/hosts/utils.ts

[BZ-1973249](https://bugzilla.redhat.com/show_bug.cgi?id=1973249)
Reads the hosts' installation progress from the `host.progress.installationPercentage` field
This is common code, so please take into consideration if the fix may not apply for CIM.

BZ-1973249: read hosts progress from API

---

src/common/components/hosts/utils.ts

- We checked only the hosts, but the controller logs might be available even though the hosts logs are not.

BZ-1978297: Fix for disabled "Download installation logs" button

---

src/ocm/components/hosts/VMRebootConfigurationInfo.tsx

https://issues.redhat.com/browse/MGMT-7406
When using virt-install the user needs to run: **virt-install --wait -1 <rest of the command>**
Otherwise, machines will not be able to reboot in the middle of installation, and will stay shut down. 
I added a warning for the user that tells him to do so (in the host discovery step):

MGMT-7406: Add virt-install usage warning when discovering libvirt hosts

---

package.json
scripts/esbuild/common-config.js

This allows importing the CIM and OCM modules directly as
`import { SomeComponent } from 'openshift-assisted-ui-lib/cim';`
and improves developer experience as it correctly infers types
in consuming application editor when 'yarn link'ing the library.

Add CIM and OCM exports to the build

---

src/common/components/clusterConfiguration/UploadSSH.tsx
src/common/components/ui/formik/UploadField.tsx
src/common/components/ui/formik/types.ts

https://bugzilla.redhat.com/show_bug.cgi?id=1937518
The `trimSshPublicKey()` function was only called on the `blur` event which doesn't occur when the Drag&Drop feature is used. I opted to pass the transformation function with props in case we wanted to use the `UploadField` component for something different than SSH keys.

BZ1937518 - Generating Discovery ISO fails using Drag&Drop feature

---

src/common/components/hosts/HostsTable.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2015471
The hosts in the cluster object have a random order. Sorting them by `id` will prevent them from changing their order in the AITable until their name is changed.

BZ-2015471: The rows in the discovery table move up and down randomly every few seconds

---

src/common/components/clusterConfiguration/networkConfigurationValidation.ts
src/common/components/clusterConfiguration/utils.ts
src/common/components/hosts/tableUtils.tsx
src/ocm/components/clusterConfiguration/ReviewCluster.tsx
src/ocm/components/clusterDetail/ClusterProperties.tsx
src/ocm/selectors/clusterSelectors.ts
src/ocm/selectors/index.ts

- The selector for the new fields fallback to the old fields for backwards compatibility
- The old fields should be removed once they are deprecated in the REST API  
- [MGMT-7527](https://issues.redhat.com/browse/MGMT-7527) sets the context for this task

MGMT-7447: UI Step 2: Consume cluster network data from the new fields

---

src/ocm/selectors/clusters.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2000142
The displayed host count is either from the `enabledHostCount` or `totalHostCount` field. Sorting value is now consistent with this.
Before:
After:

BZ-2000142 - Sorting by Host in Assisted Cluster does not work as expected

---

src/common/components/hosts/AITable.tsx
src/common/components/hosts/HostRowDetail.tsx
src/ocm/components/hosts/ClusterHostsTable.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=1978297
The NTP status of the host will not appear after the installation starts but remains before that.

BZ-1978297: Removing "NTP status" field after the cluster installation begins

---

src/common/components/featureSupportLevels/FeatureSupportLevelBadge.tsx
src/common/components/ui/PreviewBadge.tsx
src/ocm/components/clusters/ClusterPage.tsx
src/ocm/components/clusters/NewClusterPage.tsx

Small improvements to tech/dev preview badges:
1. Added an 'i' icon to the badge
2. Added the tech preview badge to the new cluster page title
3. Added a popover to the tech preview badge in the cluster page title
Before:
After:

preview badge improvements

---

src/common/components/ui/table/wrappable.css

https://issues.redhat.com/browse/MGMT-8412
Screenshots from Firefox:
before:
after:

MGMT-8412 - The events modal is not correctly formatted in Firefox

---

package.json
yarn.lock

chore: removes http-proxy-middleware

---

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
src/ocm/services/DiscoveryImageFormService.ts

https://bugzilla.redhat.com/show_bug.cgi?id=1986596
Default values for the `DiscoveryImageConfigForm` are taken from the infraEnv. Loading or Error components will get displayed in corresponding states.
Also, let's not set the `pullSecret` to an empty string, it causes too many issues. :slightly_smiling_face:
https://user-images.githubusercontent.com/87187179/144851877-3540b0ba-1aec-4f7b-a4e2-1c06b9302ad8.mp4

BZ-1986596 - SSH Key does not show up in active 'Generate Discovery ISO' modal after Generating Discovery ISO, followed by Edit ISO Configuration

---

src/cim/components/helpers/clusterDeployment.ts

Fixes: https://github.com/open-cluster-management/backlog/issues/17275

Bug 17275 ACM: Console/Api URLs are shown for installed clusters only

---

src/cim/components/InfraEnv/AgentAlerts.tsx
src/cim/components/InfraEnv/EnvironmentErrors.tsx
src/cim/components/InfraEnv/index.ts
src/cim/components/common/constants.ts

Add detection for metal3 operator configuration
.
the alert message got updated to 
```
It seems the Metal3 operator is missing configuration which will prevent it to find bare metal
hosts in this namespace. Please refer to the documentation for the first time setup steps.
```

Fix link to ACM docs.

---

src/common/components/hosts/HostRequirements.tsx

The word "host" is singular in this sentence, so the apostrophe should
go before the "s".

minor fix to grammar

---

src/ocm/hooks/usePullSecret.ts

root cause: loading state didn't apply while pull secret was requested since the default was an empty string instead of undefined

MGMT-8565: "Edit pull secret" checked by default in OCM

---

src/ocm/components/clusterWizard/ClusterDetailsForm.tsx

https://issues.redhat.com/browse/MGMT-8537
A cluster with managed domains made the base domain field in the cluster details page to be rendered as an empty dropdown list.
The `managedDomains` data wasn't being passed down to the component.

Add managedDomains prop to the ClusterDetailsFormFields

---

src/common/components/featureSupportLevels/FeatureSupportLevelBadge.tsx
src/common/components/ui/PreviewBadge.tsx
src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx

Following discussion with PM we agreed to treat developer preview features as technology preview in the UI

MGMT-8678: Deprecate the "Developer Preview" badge in assisted installer

---

src/common/components/hosts/utils.ts

https://issues.redhat.com/browse/MGMT-8521
bug caused by the progress field of the host not being empty but not containing the currentStage.
this happens in the beginning of installation.
this fix is just to return to behavior before v2.
the proper behavior is that the popover doesn't appear at all in this case, which will take longer to implement.

MGMT-8521: Host progress step popover displays 'undefined' in beginning of installation

---

src/common/components/clusterConfiguration/NetworkConfigurationFormFields.tsx
src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx

https://issues.redhat.com/browse/MGMT-8497
Changed source of image ssh key to come from infra-env API
Requires adjustment in CIM, common component NetworkConfigurationFormFields should receive the infraEnv

MGMT-8497: Networking page SSH key checkbox doesn't exist

---

src/cim/components/Agent/tableUtils.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
src/cim/components/ClusterDeployment/helpers.ts
src/cim/components/ClusterDeployment/types.ts
src/cim/components/InfraEnv/AgentAlerts.tsx
src/cim/components/InfraEnv/utils.ts
src/cim/components/helpers/agentClusterInstall.ts
src/cim/components/helpers/agents.ts
src/cim/components/helpers/index.ts
src/cim/components/helpers/infraEnv.ts
src/cim/components/helpers/status.ts
src/cim/components/helpers/toAssisted.ts
src/common/components/hosts/HostStatus.tsx
src/common/components/hosts/tableUtils.tsx
src/common/components/hosts/types.ts
src/common/config/constants.ts

MGMT-8160: Add onUnbindHost action

---

src/common/components/clusterConfiguration/ClusterSshKeyFields.tsx

[BZ-1987340](https://bugzilla.redhat.com/show_bug.cgi?id=1987340)
When trying to edit the cluster ssh key in the networking tab, if user clears it first to enter a new value, the text area disappears and reappears as false.
the root cause is that the UI unnecessarily responds to cluster polling

BZ-1987340: issue with editing cluster ssh key

---

src/ocm/components/clusterDetail/ClusterProperties.tsx

https://issues.redhat.com/browse/MGMT-8077
I added info about the disk encryption in the cluster details. 
***Please note** I had to make a small change in comparison to the mock (image of the mock can be found in the jira link above). 
In the mock, in case the diskEncyription is enabled for workers and masters the information is divided into two lines. 
In the project file trying to use <br> converts '<' to &lt and '>' to &gt, separating DetailsItem creates too big of a gap and using '\n' is not possible.
I'll be happy to hear if that's OK or other suggestions.

MGMT-8077: Add "disk encryption" to cluster details

---

src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
src/common/components/clusterConfiguration/SNOControlGroup.tsx
src/common/components/clusterWizard/ClusterDetailsFormFields.tsx

Reverts openshift-assisted/assisted-ui-lib#1037
Reverting due to a bug introduced by this PR when dealing with an existing cluster. Details are included in the Jira issue.

Revert "MGMT-8463: SNO checkbox and OpenShift version misbehavior"

---

.vscode/tasks.json

Some tasks related to OCM development that enable launching 3 terminals with the `start`, `sync-dist` and `start:assisted-ui` or `start:uhc-portal` target with one command

NO-ISSUE: Tasks for VSCode

---

src/ocm/components/clusterConfiguration/ReviewCluster.tsx
src/ocm/components/clusterDetail/ClusterProperties.tsx
src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
src/ocm/components/featureSupportLevels/index.ts
src/ocm/components/featureSupportLevels/utils.tsx

https://issues.redhat.com/browse/MGMT-8392
added feature support levels data to cluster details shown during/after installation
includes small change in order of info in cluster details to make room for new info

MGMT-8392: Feature support level indications in cluster details

---

src/cim/components/ClusterDeployment/ClusterDeploymentProgress.tsx
src/cim/components/helpers/agents.ts
src/cim/components/helpers/toAssisted.ts
src/cim/types/k8s/agent-cluster-install.ts
src/cim/types/k8s/agent.ts

Cluster and agent progress properties are now available from k8s resources
(agentClusterInstall and agent). This change replaces original client side
progress calculation with these newly available properties.

[CIM] Use progress from k8s resources

---

src/cim/components/helpers/agents.ts
src/cim/components/helpers/status.ts
src/common/components/hosts/HostStatus.tsx
src/common/components/hosts/types.ts
src/common/config/constants.ts

- Rename `Discovered` host status to `discovered` to align the status naming
- Add unbinding and discovering status to states valid for host selection
Depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/1017

Rename Discovered host status to discovered to align the status naming

---

src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
src/common/components/clusterConfiguration/SNOControlGroup.tsx
src/common/components/clusterConfiguration/SNODisclaimer.tsx
src/common/components/clusterConfiguration/utils.ts
src/common/components/clusterWizard/clusterDetailsValidation.ts
src/common/components/ui/formik/SingleNodeCheckbox.tsx
src/common/components/ui/utils.ts
src/ocm/components/clusterWizard/ClusterDetailsForm.tsx

This code breaks CIM. Requires adding a FeatureSupportLevelContextProvider in CIM that'll implement the sno support level information hard coded
Related to #1014

NO-ISSUE: Replaces hard-coded SNO support level with feature support level API

---

src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
src/common/components/clusterConfiguration/DiscoveryInstructions.tsx
src/common/components/clusterConfiguration/DownloadIso.tsx
src/ocm/components/AddHosts/InventoryAddHost.tsx
src/ocm/components/clusterConfiguration/HostInventory.tsx
src/ocm/components/clusterConfiguration/discoveryImageModal.tsx

[MGMT-8478](https://issues.redhat.com/browse/MGMT-8478)
- We don't differentiate anymore between SNO and multi-node instructions (WLG).

MGMT-8478: Change Add hosts instructions

---

src/common/components/clusterConfiguration/DownloadIso.tsx

MGMT-8478: Removes to boot instructions at the bottom of the modal

---

src/common/api/types.ts
src/common/components/hosts/HostStatus.tsx
src/common/components/hosts/HostValidationGroups.tsx
src/common/components/hosts/tableUtils.tsx
src/common/components/hosts/types.ts
src/common/components/ui/formik/validationSchemas.ts
src/common/config/constants.ts
src/ocm/components/hosts/ClusterHostsTable.tsx
src/ocm/components/hosts/ModalDialogsContext.tsx
src/ocm/components/hosts/UpdateDay2ApiVipDialogToggle.tsx
src/ocm/components/hosts/UpdateDay2ApiVipForm.tsx
src/ocm/components/hosts/UpdateDay2ApiVipModal.tsx
src/ocm/components/hosts/use-hosts-table.tsx

https://issues.redhat.com/browse/MGMT-8735
Includes separation of alerts with an action and alerts without actions. For example, the alert on invalid host names in separated form the rest because it has an action "Change host name"

MGMT-7987: Add an option to update day2 api vip for a host failing to connect

---

src/common/config/constants.ts
src/ocm/components/clusterDetail/ClusterDetail.tsx
src/ocm/selectors/clusterSelectors.ts

https://issues.redhat.com/browse/MGMT-8297
The following message appears when _cluster.status === 'installed'_ and the cluster is not an SNO:
**"Add new hosts by generating a new Discovery ISO under your cluster's "Add hosts" tab on console.redhat.com/openshift"**

MGMT-8297: Add a message about adding workers after cluster is installed

---

src/common/components/clusterDetail/KubeconfigDownload.tsx

https://issues.redhat.com/browse/MGMT-8949
Determining whether to use "kubeconfig" or "kubeconfig-noingress" has been moved to the backend.

MGMT-8949 - Enable downloading kubeconfig when it is available

---

src/cim/components/InfraEnv/EnvironmentDetails.tsx
src/cim/components/InfraEnv/InfraEnvFormPage.tsx
src/cim/components/modals/EditNtpSourcesModal.tsx
src/cim/components/modals/types.ts
src/cim/types/k8s/infra-env-k8s-resource.ts
src/common/components/hosts/AdditionalNTPSourcesDialog.tsx
src/common/components/ui/formik/AdditionalNTPSourcesField.tsx
src/common/components/ui/formik/RadioField.tsx
src/common/components/ui/formik/index.tsx
src/common/components/ui/formik/types.ts

I've made some changes so @ShiranHi let me know if you agree or not
1. sources are separated via comma, not via new line. This is how we do it on OCM so I think it would be good to align
2. I've added a help text under TextArea to make clear what format we expect (we do the same on OCM)
3. TextArea is not aligned with checkbox content, we do not do it on other places

Add NTP sources configuration for CIM

---

src/common/config/constants.ts
src/ocm/components/clusterDetail/ClusterDetail.tsx

https://issues.redhat.com/browse/MGMT-9061
The constant used to indicate installation hasn't started/finished yet is different than the `TIME_ZERO` constant. This was causing the calculated number of days until the kubeconfig file is deleted to be negative which prevented the button from rendering.

MGMT-9061 - Download kubeconfig button doesn't exist

---

src/common/config/constants.ts
src/ocm/components/clusterConfiguration/HostInventory.tsx

https://issues.redhat.com/browse/MGMT-9048
Modified popover in the Host discovery step:
The links in the "Review and create" and "Installation" steps now point to https://access.redhat.com/solutions/6677901

MGMT-9048 - Enhance vSphere usability

---

src/common/components/hosts/RoleCell.tsx
src/common/components/hosts/tableUtils.tsx
src/common/components/hosts/utils.ts
src/ocm/components/hosts/HostsDiscoveryTable.tsx

https://issues.redhat.com/browse/MGMT-9067

MGMT-9067: Implement the UI for auto-select control plane nodes

---

src/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx

This causes the AI FE to fail completely, and in version 2.9 to not show any feature support level information

MGMT-9146: No feature support level provider in Overview of OCM

---

src/common/components/ui/PreviewBadge.tsx

Currently, [OCM](https://console.redhat.com/openshift) consumes assisted-ui-lib in minified dist/ form from npm.
These 2 components cause churn in OCM's snapshot tests on every ui-lib release, for example:
```diff
--- src/components/tokens/__tests__/__snapshots__/Tokens.test.jsx.snap
+++ src/components/tokens/__tests__/__snapshots__/Tokens.test.jsx.snap
@@ -76,7 +76,7 @@ exports[`<Tokens /> Renders loading screen 1`] = `
ocm command-line tool
</ExternalLink>
-                  <cl
+                  <Oa
position={1}
/>
</ListItem>
```
A more systematic solution could be to export it non-uglified to npm, but unless you know how to do that quickly, I'd be happy if you can merge this band-aid.

set displayName on DeveloperPreview, TechnologyPreview

---

src/ocm/hooks/useOpenshiftVersions.tsx
src/ocm/services/apis/SupportedOpenshiftVersionsAPI.ts

root cause: following [this PR](https://github.com/openshift/assisted-service/pull/3254) in backend sorting by keys is incorrect, it should be sorted by displayName
includes fix of return value type of openshift-versions discovered during debugging

MGMT-9095: version 4.9.9 appeared before 4.9.17

---

src/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx

https://issues.redhat.com/browse/MGMT-9029
OCM was using two different components and only one of them (`AssistedUIRouter`) had a feature gate list passed down.
Related: https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/3070
From AI list: 
From OCM list before: 
From OCM list after:

MGMT-9029: Platform integration is shown only in the Assisted cluster list

---

src/cim/components/ClusterDeployment/ClusterDeploymentWizardFooter.tsx
src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
src/common/components/clusterConfiguration/DiskEncryptionFields/TangServers.tsx
src/common/components/clusterWizard/clusterDetailsValidation.ts
src/common/config/constants.ts
src/ocm/components/clusterWizard/ClusterWizardFooter.tsx
src/ocm/selectors/clusterSelectors.ts
src/ocm/services/DiskEncryptionService.ts

The different scenarios can be seen in the video (https://youtu.be/sfgRzMkisJA). 
For example, if the user fills the url and/or thumbprint fields of the tang server and then regrets and cancel the encryption, those fields will be reset to their initial values. Same thing will happen if he switches from SNO to a regular cluster. 
As long as on of the "enable on masters" and "enable on workers" is on, the tang servers' fields will maintain their current values. 
Relates to #1114

NO-ISSUE: Reset tang servers' fields in different scenarios

---

src/common/components/clusterConfiguration/DownloadIso.tsx

We dont want to show static ip info in OCM.

MGMT-9228: Show Static IP info only if hasDHCP is false

---

src/ocm/components/clusterConfiguration/HostInventory.tsx

* Change Platform integration texts to be specific to vSphere
* vSphere switch tooltip text change
* Remove vSphere 'learn more' link

MGMT-8975: Text updates for the Platform integration popover (#1151)

---

src/ocm/hooks/useClusterSupportedPlatforms.ts

Post assisted-service v2.0.11 the `supported-platforms` API will send ["none"] when no hosts have been discovered yet.
https://issues.redhat.com/browse/MGMT-9028

MGMT-9028: Platform integration missbehavior

---

src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx

https://issues.redhat.com/browse/MGMT-9389
root cause: Form section in NetworkConfigurationFormFields component was replaced with Grid
before:
after:

MGMT-9389: wrong form styling for networking step

---

src/common/components/hosts/MassChangeHostnameModal.tsx

Bug [2052117]:  Bulk option "Change hostname" is able to address more than one number allocation using {{n}} pattern in the infraenv page.

UI bulk option change hostname allows more than one number allocation using {{n}} pattern

---

src/common/hacks.ts

The version is already included in[ html tree](https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/ocm/components/Router.tsx#L21)

Remove AI lib logging through console.log.

---

src/common/components/clusterWizard/ClusterDetailsFormFields.tsx

Enable disc encryption should not be present in the CIM
Related to issue: https://bugzilla.redhat.com/show_bug.cgi?id=2059609

Enable disc encryption should not be present in the CIM

---

src/common/components/clusterDetail/ConsoleModal.tsx

https://issues.redhat.com/browse/MGMT-9510
this issue happens when there are multiple host interfaces, cluster SNO and the first interface doesn't have an IP.
the solution is that ingress and api vips should be taken from the cluster and not from the hosts.

MGMT-9510: UI shows undefined api/ingress vips in console troubleshooting

---

src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx

MGMT-8599 suggests to use tooltip for disabled fields, but all fields are disabled so @nirfarkas agreed to just use the alert. IIRC there was some text proposal but I dont remember. Is the current one ok ? @nirfarkas

MGMT-8599: Add info that Cluster details cannot be edited

---

src/cim/components/helpers/clusterDeployment.ts

The problem: When user removes all location filters in host selection screen
the location annotation is not updated in clusterdeployment resource.
Fix: If no location filters are specified, delete the location annotation
from the clusterdeployment resource.

Delete location annotation when no location is set

---

src/common/components/hosts/HostStatus.tsx

Host status 'installing' is more of a 'starting installation'. At that
point the installation progress and stages are not reported.
The progress reporting starts with 'installing-in-progress' status.

Don't show host progress popover when starting installation

---

src/cim/components/helpers/versions.ts

Fixes the double `OpenShift OpenShift` in version field

Fix openshift version label in cluster deployment wizard

---

src/cim/components/ClusterDeployment/ClusterDeploymentKubeconfigDownload.tsx

Related to https://bugzilla.redhat.com/show_bug.cgi?id=2060447

Bug 2060047: AI provisioning - Download kubeconfig should have yaml file extension

---

src/ocm/components/clusterDetail/ClusterDetail.tsx

https://issues.redhat.com/browse/MGMT-9340
The button and alert aren't shown if the file cannot be downloaded.

MGMT-9340: Kubeconfig download button and inline notification are shown even when the file is not available

---

src/common/api/types.ts
src/common/components/hosts/hardwareInfo.ts

Related to https://bugzilla.redhat.com/show_bug.cgi?id=2061741

Bug 2061741: Host details shows clock speed at 0MHz in the cluster installation screen

---

src/common/components/clusterConfiguration/NetworkConfigurationTable.tsx
src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx
src/ocm/components/hosts/use-hosts-table.tsx
src/ocm/reducers/clusters/currentClusterSlice.ts

https://issues.redhat.com/browse/MGMT-9411
After investigating the issue, I found out that this might be a performance problem on slower computers.
This PR avoid unnecessary re-rendering of complex components, such as the Host table.
. On NetworkConfigurationForm, on form submit, only update the "base" cluster data, and not the `hosts` property. This prevents the hosts table being re-rendered.
- Avoid rendering all modals, even when they are not open.
- Memoized `ExpandComponent` on `NetworkConfigurationTable` based on profiling results.
These changes should improve the performance of the Network config page.

MGMT-9411: Fix host re-render

---

src/common/components/ui/formik/FormikAutoSave.tsx

backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1241

CIM2.5: Revert autosave logic to use the `dirty` prop again

---

src/ocm/api/utils.ts
src/ocm/components/clusterConfiguration/ClusterDefaultConfigurationContext.tsx
src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx
src/ocm/components/clusterDetail/utils.tsx
src/ocm/components/clusterWizard/ClusterDetails.tsx
src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
src/ocm/components/clusters/ClustersListToolbar.tsx
src/ocm/components/clusters/utils.test.ts
src/ocm/reducers/clusters/currentClusterSlice.ts
src/ocm/services/ClusterDetailsService.ts

Changed the imports of specific `lodash` functions to avoid loading the entire `lodash` module and reduce build time / bundle size.
This PR changes only the usages within `ocm` code.
More details in https://github.com/openshift-assisted/assisted-ui-lib/pull/1250

Use import to lodash functions not the entire module - OCM

---

src/common/api/utils.ts
src/common/components/clusterWizard/ClusterWizardStepValidationsAlert.tsx
src/common/components/clusterWizard/ReviewValidations.tsx
src/common/components/clusterWizard/validationsInfoUtils.ts
src/common/components/ui/ClusterEventsToolbar.tsx
src/common/components/ui/formik/FormikAutoSave.tsx
src/common/components/ui/table/utils.ts
src/common/hooks/useDeepCompareMemoize.ts
src/common/selectors/clusterSelectors.ts

Changed the imports of specific `lodash` functions to avoid loading the entire `lodash` module and reduce build time / bundle size.
This PR changes only the usages within `common` code.
More details in https://github.com/openshift-assisted/assisted-ui-lib/pull/1250

Use import to lodash functions not the entire module - Common

---

package.json

This is required since v2.3.3 and CIM-2.5 are a different branch in comparison to master.

Merge CIM-2.5 into master

---

src/common/components/clusterConfiguration/AdvancedNetworkFields.tsx
src/common/components/clusterConfiguration/NetworkConfiguration.tsx
src/common/components/clusterConfiguration/networkConfigurationValidation.ts
src/common/components/clusterConfiguration/utils.ts
src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
src/common/config/constants.ts
src/common/selectors/clusterSelectors.ts
src/ocm/components/clusterDetail/ClusterProperties.tsx
src/ocm/services/ClusterDetailsService.ts

https://issues.redhat.com/browse/MGMT-9176
This PR makes sure that Assisted Installer sets valid configurations for "networkType" .
- SNO clusters and Multi-node clusters using ipV6, they must use `OVNKubernetes` as its Network Type.
- Multi-node clusters using ipV4 can use either `OVNKubernetes` or `OpenShiftSDN`. However, when a cluster is created, its default Network Type must be `OpenShiftSDN`. Users can modify this to OVN by toggling the Advanced network options and selecting it.
The fix includes:
- Setting the default Network Type on the API call to create a new cluster. This will depend on the cluster type as explained above.
- Disabling the SDN option when the cluster type does not allow it.
- Updating the Network Type of a cluster when the subnets are selected and it changes from …

MGMT-9176 Network type selection rules

---

src/ocm/services/apis/ClustersAPI.ts

https://issues.redhat.com/browse/MGMT-6468
In order to improve the performance of the Cluster list in UHC Portal, we need to be able to query for the Clusters, passing a new parameter called `ams_subscription_ids`.
This will be used in UHC Portal, see https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/3239

MGMT-6468 Adding Batch request for clusters by subscription ID

---

src/common/sevices/DateAndTime.tsx
src/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx
src/ocm/components/clusterDetail/ClusterDetail.tsx
src/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx
src/ocm/components/clusterDetail/ClusterDetailStatusVarieties.tsx
src/ocm/components/clusterDetail/ClusterProperties.tsx
src/ocm/components/clusterDetail/index.ts

https://issues.redhat.com/browse/MGMT-9795
Is used by https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/3248
To be able to show all details for AI clusters,
- A new component `AssistedInstallerExtraDetailCard` is created, which displays the AI cluster properties (IP, etc)
- Made the warnings that appear during the installation process also visible in the `AssistedInstallerDetailCard`, as well as in the Installer as up until now. See the code moved from  `ClusterDetail` to  `ClusterDetailStatusVarieties`

MGMT-9795 Export ClusterDetails extra component

---

src/cim/components/Agent/BMCForm.tsx
src/cim/components/Agent/tableUtils.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
src/cim/components/ClusterDeployment/types.ts
src/cim/components/InfraEnv/InfraEnvAgentTable.tsx
src/cim/components/common/constants.ts
src/cim/components/helpers/toAssisted.ts
src/cim/components/modals/EditBMHModal.tsx
src/cim/components/modals/MassDeleteAgentModal.tsx
src/cim/components/modals/types.ts

- update AGENT_BMH_HOSTNAME_LABEL_KEY to AGENT_BMH_NAME_LABEL_KEY
- set correct nmstate value for agent bmh label key (bmh name instead of hostname)
- set infraenv label on nmstate to allow BMO to correctly apply it
- use nmStates from recoil state instead of fetching them explicitly
- when mass-deleting BMHs, delete also related nmstates
Fixes BZ2071750

Bug 2071750: Fix labeling to correctly assign nmstate to infraEnv

---

src/cim/components/Agent/BMCForm.tsx
src/cim/components/Agent/tableUtils.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
src/cim/components/ClusterDeployment/types.ts
src/cim/components/InfraEnv/InfraEnvAgentTable.tsx
src/cim/components/common/constants.ts
src/cim/components/helpers/toAssisted.ts
src/cim/components/modals/EditBMHModal.tsx
src/cim/components/modals/MassDeleteAgentModal.tsx
src/cim/components/modals/types.ts

- update AGENT_BMH_HOSTNAME_LABEL_KEY to AGENT_BMH_NAME_LABEL_KEY
- set correct nmstate value for agent bmh label key (bmh name instead of hostname)
- set infraenv label on nmstate to allow BMO to correctly apply it
- use nmStates from recoil state instead of fetching them explicitly
- when mass-deleting BMHs, delete also related nmstates
Fixes BZ2071750
Cherry-picked from 68053b9c

Bug 2071750: CIM 2.5 Fix labeling to correctly assign nmstate to infraEnv

---

src/common/components/clusterDetail/FinalizingProgress.tsx

https://issues.redhat.com/browse/MGMT-10158

MGMT-10158: capitalize initialization status

---

src/common/components/ui/formik/CodeField.tsx
src/common/components/ui/formik/InputField.tsx
src/common/hooks/useFieldErrorMsg.tsx

https://issues.redhat.com/browse/MGMT-10171
Right now we show errors on an input field if it was touched.
This causes required array fields new items to become invalid right away.
Instead I propose the following:
If the value is empty - show the error only if it was previously none empty
If the value is not empty - show the error 
This change effects all input fields across the lib

MGMT-10171: Form fields get invalidated immediately before entering information

---

.eslintrc

Unused variables will make our GH actions fail because we don't tolerate warnings in PR builds or while releasing new versions. Marking this rule as "error" will make our IDEs prompt about the error sooner instead of just display a warning.

chore: enforce @typescript-eslint/no-unused-vars": "error"

---

src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx

https://issues.redhat.com/browse/MGMT-10212
Avoid partial version matches resulting in wrong support data identification.
Eg. If we received versions `4.1` and `4.10`, the previous code would match to version `4.1`.
The regular expression would allow only `4.10`, `4.10.`, `4.10.123` etc.

MGMT-10212: Avoid false positives checking version features

---

package.json
src/common/components/ui/formik/SwitchField.tsx

https://issues.redhat.com/browse/MGMT-8946
The most recent update of PatternFly added the option to have both a label and a checkmark in the switch component. The checkmarks are now set to appear globally in AI.

MGMT-8946: UI switches must display the variant containing the "V" mark

---

src/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx
src/ocm/components/clusterDetail/ClusterDetailStatusVarieties.tsx
src/ocm/components/clusterDetail/ClusterInstallationProgressCard.tsx

https://issues.redhat.com/browse/MGMT-9477
Removed from Cluster detail card in OCM:
Still showing when viewed through assisted installer (unless it's on-prem single cluster mode):

MGMT-9477: Link to day2 cluster is irrelevant for non cloud AI

---

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

The UI was forcing advanced networking on SNO clusters. There is no scenario in which the `Network type` needs to be automatically set to OVN like this, so the code for that was removed.

Fix: Do not set network type automatically

---

src/common/selectors/clusterSelectors.ts
src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/AvailableSubnetsControl.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx

https://issues.redhat.com/browse/MGMT-10058
- Dual-stack will not be offered if the hosts aren't using IPv6.
- I've also added filtering to the machine network options (IPv4 for single stack and first subnet in dual-stack, IPv6 for second subnet in dual-stack):
- Added more specific field titles for Cluster and Service networks in dual stack:

MGMT-10058: Dual Stack should not be offered when hosts have only IPv4 addresses

---

src/ocm/components/hosts/HostRequirementsContent.tsx

https://issues.redhat.com/browse/MGMT-9892
Before:
After:

MGMT-9892: Change copy in CNV popover from "supervisors" to "control-plane node"

---

src/ocm/components/clusterWizard/wizardTransition.ts

https://issues.redhat.com/browse/MGMT-10402
The hosts validationInfo of type `media-connected` was not being displayed in the Host Discovery phase. For the next steps, the message was being shown because they show all failed validations.
After the fix:
.

MGMT-10402 Show media-connected warning in Discovery step

---

src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx

https://issues.redhat.com/browse/MGMT-10388
Changed the condition so that the "IPv4" / "IPv6" suffix is only displayed for Dual Stack.
After the change:

MGMT-10388 Do not add suffix to network fields in Single Stack

---

src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionValues.ts
src/common/components/clusterWizard/clusterDetailsValidation.ts
src/common/components/clusterWizard/types.ts
src/ocm/components/clusterWizard/ClusterDetailsForm.tsx

https://issues.redhat.com/browse/MGMT-10392
The issue is happening because when the form mounts, it runs the effect where I made the changes was setting the  `touched` value for field `diskEncryptionTangServers`.
I have assumed that the empty object  is the same as {url: '', thumbprint: ''} so if the value is either of those, we are not updating the cluster to avoid the dirty form.

MGMT-10392 Do not patch if no changes happened

---

src/ocm/components/clusterWizard/wizardTransition.ts
src/ocm/components/hosts/HardwareStatus.tsx

https://issues.redhat.com/browse/MGMT-10226
There were 2 reasons why it wasn't showing:
- The new signal "ignition-downloable" was not listed in the Host discovery step.
- The host status in Host Discovery did not have the needed component.
I simulated it with the e2e, as unfortunately I don't have a Day 2 cluster with the issue.

MGMT-10226 Show ignition-downloadable message

---

src/ocm/components/hosts/HostsDiscoveryTable.tsx

https://issues.redhat.com/browse/MGMT-9431
**part of:** https://github.com/openshift-assisted/assisted-ui-lib/pull/1395
I removed the "force role" function, so now the roles are determined only by the BE:

MGMT-9431: Discovered hosts forced to master role instead of auto-assign

---

package.json

Before:
```
ls: cannot access 'dist': No such file or directory
$ yarn clean && node ./scripts/esbuild/dev.js
$ rimraf dist
Build succeeded and started watching { errors: [], warnings: [], stop: [Function: stop] }
Package content has not changed, skipping publishing.
^C
```
You can see that the `src` directory with emitted types is not included
After:
```
$ run-s clean esbuild:dev
$ rimraf dist
$ node ./scripts/esbuild/dev.js
Build succeeded and started watching { errors: [], warnings: [], stop: [Function: stop] }
openshift-assisted-ui-lib@2.4.0 published in store.
Pushing openshift-assisted-ui-lib@2.4.0 in /root/assisted-ui
Package openshift-assisted-ui-lib@2.4.0 linked ==> /root/assisted-ui/node_modules/openshift-assisted-ui-lib
Pushing openshift-assisted-ui-lib@2.4.0 in …
```

NO_ISSUE: Fix build scripts to correctly emit types

---

src/ocm/components/clusterWizard/wizardTransition.ts
src/ocm/components/hosts/HardwareStatus.tsx

The 'ignition-downloadable' validation is not available in day 1 so reverted change does not really fix [MGMT-10226 problem](https://github.com/openshift-assisted/assisted-ui-lib/pull/1391).
When [checking the host validations for a wizard step](https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/common/components/clusterWizard/validationsInfoUtils.ts#L99) we're comparing the length of the required validations from validations map with the length of required validations from real host validations info. We should probably replace this with a debug console warning as part of this change to prevent unwanted behaviour in case when validations info does not include some validation which is defined in validations map. (For example in case when some validation is removed from …

Revert "MGMT-10226 Show ignition-downloadable message (#1391)"

---

src/common/components/hosts/MassChangeHostnameModal.tsx

https://issues.redhat.com/browse/MGMT-10596
Before:
After:

MGMT-10596: Hostname validations won't allow for numbering in mass-actions [BACKPORT]

---

src/cim/components/helpers/status.ts
src/common/components/clusterWizard/validationsInfoUtils.ts
src/common/components/hosts/HostStatus.tsx
src/common/components/hosts/HostValidationGroups.tsx
src/common/components/hosts/status.tsx
src/common/components/hosts/tableUtils.tsx
src/common/components/hosts/utils.ts
src/ocm/components/hosts/HardwareStatus.tsx
src/ocm/components/hosts/NetworkingStatus.tsx

Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1413
Host status sublabel has been leaking into unwanted places because
it was set by modifying the original host status definition object.

[releases/v2.4] MGMT-10579 Fix host status and validations

---

src/common/components/ui/formik/constants.tsx
src/common/components/ui/formik/validationSchemas.ts

https://issues.redhat.com/browse/MGMT-10642
Added hostname validation regex. Hostnames must be valid (maximum of 62 characters between dots).
Before:
After:

MGMT-10642: Hostname in UI chars limit is 253 (BE limit is 63) [BACKPORT]

---

src/common/components/ui/formik/constants.tsx
src/common/components/ui/formik/validationSchemas.ts

https://issues.redhat.com/browse/MGMT-10642
Added hostname validation regex. Hostnames must be valid (maximum of 62 characters between dots).
Before:
After:

MGMT-10642: Hostname in UI chars limit is 253 (BE limit is 63)

---

src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
src/common/components/clusterWizard/ClusterDetailsFormFields.tsx

Related to https://bugzilla.redhat.com/show_bug.cgi?id=2059609
Solving the problem with disc encryption that disappeared from the stand-alone UI (in OCM is ok)

[release/v2.4]: Enable disk encryption should not be present in CIM

---

src/common/components/clusterConfiguration/SNODisclaimer.tsx

https://issues.redhat.com/browse/MGMT-10674
The wording changed from "Adding additional machines to your cluster is currently out of
scope." to "Adding additional machines to your cluster is currently not supported."

MGMT-10674: Change the wording of the SNO notification

---

src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
src/common/components/ui/formik/RadioFieldWithTooltip.tsx

Now:
Before:
Sample scenario: Multi-node cluster w/dual-stack won't allow UMN

NO-ISSUE: Fixes the tooltips for disabled CMN/UMN controls

---

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx

https://issues.redhat.com/browse/MGMT-10636
- Enable the StackType selector when the cluster is an SNO
- Patch netwokType when changing the stackType to the default for that cluster's configuration:
* If the cluster is an SNO (Single Stack or Dual Stack), OVNKubernetes is mandatory .
* If the cluster is a multi-cluster using Dual Stack, the default value is OVNKubernetes.
* If the cluster is a multi-cluster using Single Stack, the default value is SDN.
Installed cluster using SNO + Dual Stack:

MGMT-10636 Allow to set-up an SNO with Dual-Stack

---

.eslintrc.js
src/common/components/ui/formik/CodeField.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx
src/ocm/components/clusterWizard/ClusterWizardFooter.tsx

- Added Eslint rule for `unused vars`
This would catch both unused imports in our code, as well as unused variables.
Currently there were 3 unused imports which were reported as errors and fixed.

NO_ISSUE: Generate errors for eslint - unused vars

---

src/ocm/components/AddHosts/AddHosts.tsx
src/ocm/components/clusterDetail/ClusterDetail.tsx
src/ocm/components/clusterDetail/ClusterDetailStatusVarieties.tsx
src/ocm/components/clusters/ClusterPage.tsx
src/ocm/reducers/clusters/clustersSlice.ts
src/ocm/services/apis/ClustersAPI.ts

https://issues.redhat.com/browse/MGMT-9454
**Installation page**:
- Added "Add hosts" button that transforms the cluster to AddHosts kind. (Only visible if cluster is multinode, installed and environment is in on-prem.)
**Add hosts page**:
- Shows the same console information like the Installation page.
- Shows all hosts in the cluster (including the day1 hosts)
- Allows to download ISO and install ready hosts
---
Note: I couldn't successfully install a day2 host because of failing validations.

MGMT-9454: Allow transforming day1 to day2 in on-prem environment

---

.eslintrc.js
src/common/components/clusterDetail/ClusterProgress.tsx
src/common/components/clusterDetail/KubeconfigDownload.tsx
src/common/components/hosts/AdditionalNTPSourcesDialog.tsx
src/common/components/hosts/HostProgress.tsx
src/common/components/ui/EventsList.tsx
src/common/components/ui/formik/NumberInputField.tsx
src/common/hooks/useFormikHelpers.ts
src/ocm/components/SingleCluster.tsx
src/ocm/components/clusterConfiguration/staticIp/components/StaticIpViewRadioGroup.tsx
src/ocm/components/clusterConfiguration/staticIp/data/machineNetwork.ts
src/ocm/components/clusterDetail/ClusterDetailStatusVarieties.tsx
src/ocm/components/clusterDetail/utils.tsx
src/ocm/components/hosts/DeleteHostModal.tsx
src/ocm/components/hosts/ModalDialogsContext.tsx
src/ocm/components/hosts/ResetHostModal.tsx
src/ocm/components/hosts/utils.ts
src/ocm/hooks/useInfraEnv.ts
src/ocm/hooks/useInfraEnvId.ts
src/ocm/hooks/useInfraEnvImageUrl.ts
src/ocm/hooks/useOpenshiftVersions.tsx
src/ocm/hooks/useUsedClusterNames.ts
src/ocm/selectors/clusters.tsx
src/ocm/services/Day2ClusterService.ts
src/ocm/services/apis/ClustersAPI.ts
src/ocm/services/apis/InfraEnvsAPI.ts

Fixes a few ESlint warnings from the following rules:
Completely removed:
`@typescript-eslint/restrict-plus-operands`
`@typescript-eslint/require-await`
Partially fixed from `@typescript-eslint/restrict-template-expressions` and similar rules where TS sees the variable as potentially undefined. We will need to fix them individually so they have not been dropped entirely.
Drops about 50 errors.

NO_ISSUE: reduce eslint warnings

---

src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx
src/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx

https://issues.redhat.com/browse/MGMT-10918
When opening the Discovery ISO modal, the default selection should be the Minimal ISO.
Made the first option in the modal the one for "Minimal iso", and moved the text saying "Recommended option" from "full-iso" to "minimal-iso" tooltips.

MGMT-10918 Discovery ISO to use minimal-iso by default

---

src/common/api/swagger.yaml
src/common/api/types.ts
src/common/config/constants.ts

https://issues.redhat.com/browse/MGMT-11036
This patch updates the OpenAPI specification and the code generated from
it, so that it will be possible to use the new `compatible-agent`
validation.

MGMT-11036: Update API for upgrade agent feature

---

src/ocm/components/AddHosts/utils.ts

https://issues.redhat.com/browse/MGMT-11009
For SNO clusters, we were using Day1's cluster version to determine if hosts could be added to it.
But if the cluster is upgraded, the version in Day1 remains unchanged. We must look at Day2's version instead.
Before: Add hosts tab missing
After: Same cluster - Add hosts tab displayed

MGMT-11009 Allow adding hosts to upgraded clusters

---

src/common/hooks/use-translation-wrapper.ts

Don't override a default translation namespace in case when
process.env.TRANSLATION_NAMESPACE is not defined.

NO_ISSUE: Remove default translation namespace override

---

src/common/components/clusterDetail/ClusterProgressItem.tsx
src/common/components/clusterDetail/ClusterProgressItems.tsx
src/common/components/clusterDetail/FinalizingProgress.tsx
src/common/components/clusterDetail/OperatorsProgressItem.tsx
src/common/components/clusterDetail/ProgressBarTexts.tsx
src/ocm/components/clusterDetail/ProgressBarAlerts.tsx
src/ocm/components/clusterDetail/getProgressBarAlerts.tsx

https://issues.redhat.com/browse/MGMT-10420
I have slightly decreased the spacing in and around the cluster progress item and also between the alerts. It's not exactly by half as the design says in the following image but this is the best that can be achieved without overwriting Patternfly variables.
**Before:**
**After:**
---
**Before:**
**After:**
---
**Before:**
**After:**

MGMT-10420: Extra spaces in installation page

---

src/common/components/clusterConfiguration/SNODisclaimer.tsx

Clicking on the SNO checkbox results in an error due to Disclaimer missing the `t` prop.

Fix SNO Disclaimer display

---

src/cim/components/ClusterDeployment/LabelsSelector.tsx

This PR fixes issue where parsed labels do not have value due to restricting `split` to just 1 element

Fix label selector

---

src/common/components/clusterConfiguration/SNODisclaimer.tsx

Removing extra bullet if the conditions do not apply to the selected OpenShift version

Do not display bullet if conditions dont apply

---

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx

https://issues.redhat.com/browse/MGMT-11345
The SSH key was not displayed as the configuration was generated before the infraEnv was received.
After the infraEnv is loaded, we will show the "generating" button while the image is being generated
https://user-images.githubusercontent.com/829045/181450050-80b1c0f0-b818-49f2-8316-79da68d79758.mp4

MGMT-11345 Wait until infraEnv is received to display Image config

---

package.json
src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
src/ocm/components/clusterConfiguration/DiscoveryImageSummary.tsx
src/ocm/components/clusterConfiguration/discoveryImageModal.tsx
src/ocm/hooks/useInfraEnvImageUrl.ts

https://issues.redhat.com/browse/MGMT-11344
After we update the cluster to generate the new ISO download URL, we retrieve the URL from the infraEnv.
Until we receive the infraEnv URL, we must stay in the initial page showing the "generating" button, and not move to the "download ISO is ready" page.
This PR fixes that by making sure the action for "Generating" waits until the infraenv image is received.

MGMT-1344 iso download timing

---

package.json

This reverts commit 60397cb071f7810a3c1333c9415a9a1fe8a77257.
v2.7.1  was created by mistake on top of `master` instead of `releases/v2.7` branch

Revert "Version v2.7.1"

---

src/ocm/hooks/useOpenshiftVersions.tsx

https://issues.redhat.com/browse/MGMT-11392

MGMT-11392: New cluster creation failed when OCP v4.11 is selected by default (#1551)

---

src/common/components/storage/StorageUtils.tsx
src/ocm/components/hosts/HostsStorageTable.tsx

https://issues.redhat.com/browse/MGMT-11545
- The column for memory was shown instead of disk size. It was likely a rebase conflict.
- The ODF column was being sorted based on the number of disks, now it's sorted by the ODF status instead.
Result:

MGMT-11545 show correct disk storage

---

src/cim/components/Agent/AgentsSelectionTable.tsx
src/cim/components/Agent/tableUtils.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelection.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionAdvanced.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
src/cim/components/ClusterDeployment/types.ts
src/cim/components/helpers/toAssisted.ts
src/cim/types/k8s/agent.ts
src/common/components/hosts/DiskRole.tsx
src/common/components/hosts/HostsTableDetailContext.tsx

Host discovery and host selection wizard steps now allow user to set
installation disk in the disks list on expanded host detail
Fixes BZ2081597

Enable seting host installation disk

---

src/common/components/hosts/utils.ts

Related to https://issues.redhat.com/browse/MGMT-11522
If cluster is installed host role selection should be blocked once it's not possible to change it anymore.

MGMT-11522: Host role is editable after install

---

locales/en/translation.json
src/common/config/constants.ts

Related to https://issues.redhat.com/browse/MGMT-11722

MGMT-11722: In the validation message looks like there is a missing space in between the words

---

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTable.tsx

Related to https://issues.redhat.com/browse/MGMT-11559
Not allow role editing in the "Storage" or "Networking" step (need to remove this capability from there) to prevent misclicks and wrong configurations dead ends.

MGMT-11559: Not allow role editing in the Networking step

---

src/common/components/storage/StorageUtils.tsx

The column had the same data-testid as the host-role column.

Use a unique test-id for the number of disks

---

src/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx
src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/formViewNetworkWideValidationSchema.tsx

Related to https://issues.redhat.com/browse/MGMT-11626
Add new validation in default gateway to validate that address is not broadcast or network address
New validation:

MGMT-11626: can't accept broadcast IP and network address for defaul gateway

---

src/ocm/components/AddHosts/HostsClusterDetailTab.tsx

https://issues.redhat.com/browse/MGMT-11796, backport for #1604 
Providing FeatureSupportLevelContext to the Add Hosts component fixes the issue bellow.

MGMT-11796 - Day2 screen shows errors [BACKPORT]

---

src/ocm/components/AddHosts/HostsClusterDetailTab.tsx

https://issues.redhat.com/browse/MGMT-11796
Providing FeatureSupportLevelContext to the Add Hosts component fixes the issue bellow.

MGMT-11796 - Day2 screen shows errors

---

src/ocm/components/AddHosts/HostsClusterDetailTab.tsx
src/ocm/services/Day2ClusterService.ts

https://issues.redhat.com/browse/MGMT-11577
Follow up on #1583, backport of #1606

MGMT-11577: Take OCP version from OCM when creating day-2 infraenv/cluster [BACKPORT]

---

src/ocm/components/clusterWizard/ClusterDetailsForm.tsx

Putting back the RichTextValidation removed on 77dc5cbd574717c31c13809a029e31c5d1b30730 so that all validations of the cluster name are displayed

Solving problems with cluster name validation

---

src/common/components/hosts/MassChangeHostnameModal.tsx

https://issues.redhat.com/browse/MGMT-11537
**Before:**
**After:**

MGMT-11537 - Mass host-name change helper text is not correct

---

src/common/components/hosts/MassChangeHostnameModal.tsx
src/common/components/ui/formik/constants.tsx
src/common/components/ui/formik/validationSchemas.ts

https://issues.redhat.com/browse/MGMT-11340
`localhost4` and `localhost6` are forbidden host names. The UI will show an error and prevent such name change.
**Before:**
**After:**

MGMT-11340 - Mass host rename - UI shows localhost4 as valid name

---

package.json
src/common/components/hosts/HostRowDetail.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTableBase.tsx
src/ocm/components/hosts/HostsDiscoveryTable.tsx
src/ocm/reducers/clusters/clustersSlice.ts

https://issues.redhat.com/browse/MGMT-11571
Added back the Storage disk section in Host Discovery and Networking steps (so they are all the same).
Actions are NOT included (eg. selecting installation disks, etc is not part of this block).

MGMT-11571 storage table in host discovery

---

locales/en/translation.json
src/cim/components/Agent/BMCForm.tsx
src/ocm/components/clusterConfiguration/staticIp/components/YamlView/MacIpMapping.tsx
src/ocm/components/clusterConfiguration/staticIp/components/YamlView/YamlViewFields.tsx

https://issues.redhat.com/browse/MGMT-11681
- "Add another mapping" → "Add another MAC to interface name mapping"
- "Mac to interface name mapping" → "MAC to interface name mapping"
**Before:**
**After:**

MGMT-11681 - Static IP flow - yaml form - "Add another mapping" should be renamed to "Add another MAC to interface name mapping"

---

package.json
src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx
src/common/components/clusterConfiguration/DiskEncryptionFields/TangServers.tsx
src/common/components/ui/formik/utils.ts
src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx

When using `validate={getRichTextValidation}` in a form, messages from FielArray were not displaying correctly. 
The problem is that `getRichTextValidation` generates an object where the paths are the individual fields, whereas `validate` is looking for the format of the parent field.
For example, for `diskEncryptionTangServers`, it needs the structure:
```
{diskEncryptionTangServers: [
{ url: 'Url error for Tang Server', thumbprint: 'Thumbprint error for Tang Server' }
]}
```
but it is seeing
`{ 'diskEncryptionTangServers[0].thumbprint': 'Some error}`
Now we are detecting the subfields and generating the needed format from the `diskEncryptionTangServers[0].thumbPrint` etc errors.
The PR also includes some clean-up of the Disk Encryption and other components.

MGMT-11814 Display FieldArray errors with getRichTextValidation

---

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx

https://issues.redhat.com/browse/MGMT-11858
When users switched DHCP on or off, the cluster and form were out of sync and this triggered unnecessary PATCH requests.
In particular, switching to DHCP `on` made three separate PATCH requests:
1. PATCH to set DHCP  `on`
2. PATCH to unset `apiVip` and `ingressVip`
3. PATCH to set `apiVip` and `ingressVip`. This request is completely unnecessary, because it was patching back the `cluster` with the values it received in the previous polling. But the form was out of sync with the cluster, and that's why the PATCH was being sent.
Now, when the user switches DHCP on / off we make sure to sync the form values at once, so only 1 PATCH request will be triggered. This avoids issues, since all requests send a few of the networking fields.

MGMT-11858 Avoid separate requests when toggling DHCP

---

src/ocm/hooks/useInfraEnv.ts
src/ocm/reducers/clusters/currentClusterSlice.ts
src/ocm/services/ClustersService.ts
src/ocm/services/DiscoveryImageFormService.ts
src/ocm/services/HostsService.ts
src/ocm/services/apis/ClustersAPI.ts
src/ocm/services/apis/HostsAPI.ts
src/ocm/services/apis/InfraEnvsAPI.ts

https://issues.redhat.com/browse/MGMT-11962
We need to make sure our applications ( assisted-ui and uhc-portal) use a compatible axios version.
**PR for assisted-ui: https://github.com/openshift-assisted/assisted-ui/pull/605**
**PR for uhc-portal: https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/3586**
**Description of the problem**
-A continuous polling of the cluster is running: getting the cluster and the hosts. This polling does a cluster and hosts fetch which that can take a while
-If while this fetch is running, we do a PATCH in the middle with some hosts changes, this ends earlier than the previous GET request
-After that. if the previous polling ends, the page is updated with the old values
-And then the other polling of the cluster is executed again and …

MGMT-11962 Fix problems with polling

---

src/common/components/clusterDetail/ProgressBarTexts.tsx

WHen a host is added to a cluster after the cluster is installed, it's final state is not installed but 'added-to-existing-cluster'. This change ensures that such hosts are not considered 'in progress' in ClusterProgressItems
Fixes BZ2118545

Bug 2118545: Hosts in added-to-existing-cluster are considered installed

---

src/common/components/clusterDetail/ProgressBarTexts.tsx

When a host is added to a cluster after the cluster is installed, it's final state is not installed but 'added-to-existing-cluster'. This change ensures that such hosts are not considered 'in progress' in ClusterProgressItems
Fixes BZ2118545
Cherry-picked from 5d3697fc
Co-authored-by: Celia Amador <camadorg@redhat.com>

[2.6-cim] Bug 2118545: Hosts in added-to-existing-cluster are considered installed

---

src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/formViewNetworkWideValidationSchema.tsx
src/ocm/components/clusterConfiguration/staticIp/data/emptyData.ts
src/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts

Related to https://issues.redhat.com/browse/MGMT-11643
In a cluster with static IP and vlan, tried to use letters and underscore for VLAN ID value - no validation is running.
The problem is the InputField with type="Number" that is  not working well in Firefox (accepting letters) and in Chrome is not working in some cases (accepting some letters like 'e').
I've changed the field type and add a message to be more clear.
1. Validation that value is not string
2. Validation that value is a number >= 1
3. Validation that value is a number <= 4094

MGMT-11643: Problems with validations in Vlan ID field in a cluster with static IP and vlan configuration

---

src/cim/components/InfraEnv/InfraEnvHostsTabAgentsWarning.tsx

Fixes BZ2126047
Cherry-picked from 429b63bb

[2.6-cim] Bug 2126047 Use host/bmh status to determine infra env hosts tab warning

---

src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx

Fixing a typo, we were displaying this instead of the actual values:

Fix: typo in VIP Control Group 

---

src/ocm/components/clusterConfiguration/staticIp/components/StaticIpViewRadioGroup.tsx

https://issues.redhat.com/browse/MGMT-11548
Added a message for the configuration method in Static IP. It is displayed in both subpages of the Form View (Network-wide and Host specific configurations)

MGMT-11548: Add inline info message for Static IP view chooser

---

package.json
src/common/components/ui/formik/validationSchemas.ts

- When running the e2e, a test failed because the validation error message of blank API / Ingress IP is different if it's the first time setting it. Now the message will be the same in the two cases, "Required. Please provide an IP address"
- Also noticed we had two almost identical functions to generate the Address for a CIDR value, and removed the dupication.
- Removed a few Eslint warnings and fixed a typo.

NO_ISSUE consistent validation message

---

src/cim/components/helpers/versions.ts

* Enhance the version calculation from release image url
* fall back to clusterImageSet name when the version is not retrieved from release image url
Fixes BZ2131292
Cherry-picked from 3a9568e1
Signed-off-by: Jiri Tomasek <jtomasek@redhat.com>

[2.6-cim] Bug 2131292: Enhance version calculation from releaseImage

---

locales/en/translation.json
src/common/config/constants.ts
src/ocm/components/clusterWizard/Operators.tsx
src/ocm/services/OperatorsService.tsx

https://issues.redhat.com/browse/MGMT-9246
The only traces of OCS left in the code should be in validations ids and labels.

MGMT-9246: Removing traces of OCS

---

package.json
src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx
src/ocm/services/ClusterDetailsService.ts

https://issues.redhat.com/browse/MGMT-11294
The UI should not set the `network_type` when a cluster is created, it's the Backend's responsability based on many different rules.
- Stop sending `networkType` when a cluster is created
- Do not modify `networkType` for the user, unless the existing choice is not valid for the changes they are doing (eg. SDN cannot be used for DualStack clusters)
- NetworkType has been move outside the "advanced settings" section. The current behaviour of the block is to reset the settings to their default values if the section is unselected, meaning the UI would need to know the default networkType for the cluster.
This avoid duplicating the backend logic for the default networkType also in the UI.
NetworkType moved outside "advanced settings"
PR for e2e tets …

MGMT-11294 default network type on creation

---

src/common/types/clusters.ts
src/ocm/hooks/useClusterSupportedPlatforms.ts

https://issues.redhat.com/browse/MGMT-12275
The logic to determine when the platform integrations are possible was wrong because it was expecting a different API response.
For a cluster with Vsphere hosts, we are receiving 
```
"supported-platforms": ['vsphere', 'none', 'metal']
```
So we should filter out `none` and `metal` and apply the same algorithm as before with those reduced values.

MGMT-12275 Fix logic to determine platform integration

---

src/common/components/hosts/SkipFormattingCheckbox.tsx

When I was working with integration tests i've found that the id of skip formatting disks checkboxes is not well generated.

Fix id generation for skip formatting disks checkboxes

---

src/common/components/clusterWizard/validationsInfoUtils.ts
src/common/components/hosts/FormatDiskCheckbox.tsx
src/common/components/hosts/SkipFormattingCheckbox.tsx
src/common/components/storage/DisksTable.tsx
src/common/components/storage/StorageDetail.tsx
src/common/components/ui/WizardNavItem.tsx
src/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
src/ocm/components/clusterWizard/ClusterWizardNavigation.tsx
src/ocm/components/clusterWizard/wizardTransition.ts
src/ocm/components/hosts/use-hosts-table.tsx
src/ocm/services/HostsService.ts

Related to https://issues.redhat.com/browse/MGMT-12328
New behavior:
1. Move the validation error to the storage tab
2. For disks that are installation disks and are also in the "skip formatting" list, show an empty non-disabled checkbox that the user can tick. This will allow the user to fix the validation error. The checkbox would immediately become disabled but ticked just like installation disks usually appear, and the validation would disappear because the installation disk is no longer in the skip list
3, For disks that are not in the candidate list for formatting, show a disabled empty checkbox to indicate to the user that the disk is safe. It's not going to be formatted. Currently we only show nothing - no check box, and that is a bit ambiguous and might make the user worry …

Problems in SNO clusters when changing role to installation disk on formattable disks

---

src/cim/components/helpers/versions.ts

* Enhance the version calculation from release image url
* fall back to clusterImageSet name when the version is not retrieved from release image url
Fixes BZ2133771
Cherry-picked from 3a9568e1
Signed-off-by: Jiri Tomasek <jtomasek@redhat.com>

Enhance version calculation from releaseImage

---

src/ocm/components/clusterConfiguration/HostInventory.tsx
src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx

https://issues.redhat.com/browse/MGMT-12347
https://issues.redhat.com/browse/MGMT-12386
`make deploy_nodes PLATFORM=nutanix` with test-infra creates a cluster with `cluster.platform.type: "nutanix"` (but no hosts). This resulted in a checked and enabled Platform integration checkbox in the UI.
This PR changes it so that the only thing that determines if the platform integration switch is enabled is whether platform integration is supported for this cluster or not. Regardless of whether cluster.platform.type is set. If `clusters/{id}/supported-platforms` is correct, I don't think we need to check the host number or against `/feature-support-levels`.
As for the "is checked" part, I'm afraid there is not much the UI can do. `cluster.platform.type` is set by test-infra and any attempt to …

MGMT-12347 "Integrate with platform" is enabled and checked while no discovered hosts in cluster

---

src/common/components/hosts/utils.ts
src/ocm/components/hosts/ClusterHostsTable.tsx

Quixk fix to solve https://issues.redhat.com/browse/OCPBUGS-3043 / https://issues.redhat.com/browse/MGMT-12420
Now we can edit disk role and skip formatting disks in hosts added in day2 cluster:
We need to change day2 flow to add storage step

Fix: Unable to select Boot drive when adding a new node

---

src/ocm/components/clusterDetail/ClusterDetail.tsx

Fix to solve bug https://issues.redhat.com/browse/MGMT-12414
SNO expansion is supported since OCP v4.11 the UI must follow the response sent through features-support-level 
To test:
1. Create and install an SNO cluster with AI deployed on-prem.
2. Check there's "Add Hosts" button on the cluster details page

Fix: Adding Hosts is disabled for SNO clusters when AI deployed on-prem.

---

src/ocm/components/hosts/HostRequirementsContent.tsx

Related to : https://issues.redhat.com/browse/MGMT-12308
Minimum hardware modal does not mention additional requirements in case when operators are selected

MGMT-12308: Adding additional requirements in minimum hardware modal

---

src/common/components/hosts/AITable.tsx
src/common/components/hosts/HostsTable.css

https://issues.redhat.com/browse/MGMT-11369
A scrollbar will appear under the table if the parent container is too small. Applies to all tables.
**Before:**
https://user-images.githubusercontent.com/87187179/200327018-c3b2a01a-ef70-4e4e-b553-1cb190def5c7.mp4
After:
https://user-images.githubusercontent.com/87187179/200327047-f28c10c9-717a-46c1-ba8b-4bf6d4e3ca2b.mp4

MGMT-11369 - Hosts table overflows from its container's space

---

src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx
src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/index.ts
src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/types.ts

Motivation: Fix preserving values on Back in the Create Cluster wizard
Backport of #1717 for ACM 2.6

BZ2119586: Hypershift NetworkStep accepts initialValues as props (ACM 2.6)

---

src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx

Related to https://issues.redhat.com/browse/MGMT-11476
Elements under advanced networking should be slightly indented:

MGMT-11476: elements under advanced networking should be slightly indented

---

src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx

Related to https://issues.redhat.com/browse/MGMT-11432
Add spaces between fields in advanced networking:
1. No dual-stack cluster:
2. Dual-stack cluster:

MGMT-11432 : Add new line in use advanced networking before " Cluster network host prefix" text

---

src/ocm/components/clusters/ClusterPage.tsx

Related to: https://issues.redhat.com/browse/MGMT-11562
New message when cluster is not found:

MGMT-11562: Better message when an infraenv cannot be retrieved

---

.github/workflows/on-release.yaml

Fix for  25540e761512a8498fadf650c7e17ec193096791 and 65789370f80d6dab8d808bdcbceee13bb8dd8172

MGMT-12536: Skip sending a PR to assisted-ui when a new CIM release is created (Fix)

---

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx

https://issues.redhat.com/browse/MGMT-12272
Stop overwriting the pull secret when patching to get the discovery ISO.

Do not patch pull secret in discovery ISO modal

---

src/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
src/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
src/ocm/components/clusterWizard/Operators.tsx
src/ocm/components/featureSupportLevels/featureStateUtils.ts
src/ocm/services/OperatorsService.tsx

https://issues.redhat.com/browse/MGMT-12311
Fixes related to operators CNV and LVM:
- The detection of LVM being automatically added on the API after selecting CNV on a 4.12 SNO was not working. It's fixed now
- The detection of when to disable CNV and which message to show was not 100% accurate, now:
* For an SNO with version 4.11 or below --> If CNV is selected, LVM cannot be. Similarly, if LVM is selected, CNV cannot be.
* For an SNO with version 4.12 or above --> If CNV is selected, LVM becomes enabled on the API. CNV must be enabled, and LVM must be disabled as it's a requisite for CNV.
* For an SNO with version 4.12 or above --> If LVM is selected, CNV can optionally be selected by the user. So CNV must not be disabled.
See video with all possible cases. …

MGMT-12311: LMV + CNV fixes

---

src/common/config/constants.ts
src/ocm/components/clusterConfiguration/ReviewCluster.tsx
src/ocm/components/clusterWizard/ClusterPlatformIntegrationHint.tsx

Related to https://issues.redhat.com/browse/MGMT-12597
The link for Nutanix is added in this page ("Review and create"):
When platform.type='vsphere' the link "Learn more" is: 
https://access.redhat.com/solutions/6677901
and when platform.type='nutanix' the link "Learn more" is: 
https://access.redhat.com/solutions/6983944

MGMT-12597: Update the user instructions link in the UI for Nutanix post deployment

---

src/common/components/hosts/AITable.tsx
src/common/components/hosts/HostsTable.css

Related to https://issues.redhat.com/browse/MGMT-11636
To keep all the tables with same appearance in the different steps we delete the compact option in tables and delete also the height auto style.
Hosts discovery table:
Storage table:
Networking hosts inventory table:

MGMT-11636: Align the styles for tables in different pages (host discovery, storage, networking)

---

src/ocm/components/clusterWizard/Operators.tsx

https://issues.redhat.com/browse/MGMT-12323
This bug initially appeared as fixed by #1701 but after further investigation I learned that it still reproduces if the user stays on the original tab where the cluster was created (which QE/their tests were doing and I wasn't) because we still had `"new"` inside the location state.
https://github.com/openshift-assisted/assisted-ui-lib/blob/2fb10afc9b23a58627476eb00bb33f78c221b87a/src/ocm/components/clusterWizard/wizardTransition.ts#L40-L42
So in this PR, I'm removing the `"new"` location state when the users click Next on the "Operators" step. With that, the initial step they land on after reloading the page will not be "Operators" but one of "Host discovery", "Networking", etc.
If we want a different condition for "is the first step …

MGMT-12323 - In UI - installation starts and after ~1 min UI "jumps" back to operators page

---

locales/en/translation.json
scripts/i18n.sh
src/common/components/ui/formik/constants.tsx
src/common/components/ui/formik/validationSchemas.ts

BZ2120954 https://bugzilla.redhat.com/show_bug.cgi?id=2120954 Cherry-picked from 263dfdff
2.6-cim Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1786

[2.6-cim] Bug 2120954: Don't allow using dots in cluster name

---

src/common/components/hosts/MassChangeHostnameModal.tsx
src/common/components/hosts/MassDeleteHostModal.tsx
src/ocm/components/hosts/ModalDialogsContext.tsx
src/ocm/components/hosts/use-hosts-table.tsx

https://issues.redhat.com/browse/MGMT-11370
The [changes done to the BE](https://issues.redhat.com/browse/MGMT-11536) seem to have fixed the majority of this bug. I'm adding a reload of the cluster after hosts are deleted (or renamed) so that the changes are immediately visible. Whereas before we would have to wait for the next polling cycle to see the changes.
**Before:**
https://user-images.githubusercontent.com/87187179/207077971-be41027b-a02b-4633-8110-928169c2a988.mp4
**After:**
https://user-images.githubusercontent.com/87187179/207078026-3d9b194d-f055-41d8-9f07-f6408cea3bfb.mp4

MGMT-11370 -  After discovery, if deleting all discovered hosts UI still allows to continue to networking and R&C pages

---

src/cim/components/helpers/versions.ts

- update getVersionFromReleaseImage to use the same regex as other ACM wizards, return undefined if there is no match
- getOcpVersions uses clusterImageSet name if there is no match ^
Cherry-picked from 2c252c71
Fixes MGMT-12917

[2.6-cim] MGMT-12917 Fix listing of versions from clusterimageset releaseImage

---

src/cim/components/helpers/versions.ts

- update getVersionFromReleaseImage to use the same regex as other ACM wizards, return undefined if there is no match
- getOcpVersions uses clusterImageSet name if there is no match ^
Fixes MGMT-12917
Cherry-picked from 2c252c71

[2.7-cim] MGMT-12917 Fix listing of versions from clusterimageset releaseImage

---

src/ocm/components/clusterConfiguration/HostInventory.tsx
src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx

https://issues.redhat.com/browse/MGMT-12386
Follow up on  #1708
BE doesn't seem to take feature support levels into account for `/cluster/${id}/supported-platforms`. I don't know if it should, but in any case, let's check the feature support levels before we enable the Platform integration button in the UI.

MGMT-12386 - Can create Nutanix 4.10 cluster with "Integrate with platform" enabled and checked

---

src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx

https://issues.redhat.com/browse/MGMT-12658
Made the label generic. The current tooltip is specific to the supported virtualization platform when all hosts are originated from the same one.
No platform supported yet:
Vsphere integration supported:
Nutanix integration supported:

MGMT-12658 Change platform integration label

---

src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
src/cim/components/ClusterDeployment/types.ts
src/common/components/hosts/EditHostForm.tsx
src/common/components/hosts/EditHostModal.tsx
src/common/components/hosts/MassChangeHostnameModal.tsx
src/common/types/index.ts
src/ocm/api/utils.ts
src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
src/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
src/ocm/components/clusterDetail/ClusterUpdateErrorModal.tsx
src/ocm/components/clusterWizard/ClusterDetails.tsx
src/ocm/components/clusterWizard/HostDiscovery.tsx
src/ocm/components/clusterWizard/Operators.tsx
src/ocm/components/clusters/ClusterPage.tsx
src/ocm/components/clusters/Clusters.tsx
src/ocm/components/clusters/clusterPolling.ts
src/ocm/components/hosts/use-hosts-table.tsx
src/ocm/reducers/clusters/clustersSlice.ts
src/ocm/reducers/clusters/currentClusterSlice.ts

https://issues.redhat.com/browse/MGMT-12072
Currently, when an error 500 is received on a PATCH request, we show an error but allow the user to continue using the applcation.
With these changes, we'll show a modal with a message to the user to reload the page in the cases below:
- Cluster Wizard: Details step (cluster creation and update)
- Cluster Wizard: Operators step
- Cluster Wizard: Host Discovery step
* Main form submission
* Generate ISO
* Rename host and Mass rename hosts
* Editing role 
- Cluster Wizard: Storage step
* Main form submission
* Updating "skip formatting disks"
- Cluster Wizard: Networking step
The video shows most of the cases where we'll show this modal.
https://user-images.githubusercontent.com/829045/207855880-6e8dca3c-05fc-4801-ae53-a38b6a05ed5e.mp4

MGMT-12072: handle unkown server errors

---

package.json
src/common/components/clusterConfiguration/utils.ts
src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
src/ocm/components/clusterConfiguration/OcmOpenShiftVersion.tsx
src/ocm/components/clusterDetail/OpenShiftVersionDetail.tsx
src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
src/ocm/components/clusters/ClustersTable.tsx
src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx
src/ocm/selectors/clusters.tsx

https://issues.redhat.com/browse/MGMT-12993
Fixes problems related to "multi" OpenShift version releases:
1. The SNO disclaimer wasn't appearing for version `4.12-multi` because the format didn't match the one we were checking. Changed the way we do the matching, so that it finds the proper version in feature-support-level.
2. Created a common function that can be used to display the OpenShift version. It can be configured to append "multi" for multi versions which don't contain the text ("multi") in the version name.
https://user-images.githubusercontent.com/829045/208673196-34592952-6198-4243-af68-8b8806561535.mp4

MGMT-12993 multi issues

---

package.json
src/common/components/ui/formik/constants.tsx
src/common/components/ui/formik/validationSchemas.ts

https://issues.redhat.com/browse/MGMT-12756
Prevent cluster name to contain "dot" character
Similar to https://github.com/openshift-assisted/assisted-ui-lib/pull/1786/files
plus some Eslint fixes

MGMT-12756 cluster name cannot use dot

---

src/ocm/components/clusterConfiguration/HostInventory.tsx
src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx

Backport of #1801 
> https://issues.redhat.com/browse/MGMT-12386
>
> Follow up on https://github.com/openshift-assisted/assisted-ui-lib/pull/1708
> 
> BE doesn't seem to take feature support levels into account for `/cluster/${id}/supported-platforms`. I don't know if it should, but in any case, let's check the feature support levels before we enable the Platform integration button in the UI.

MGMT-12386 - Can create Nutanix 4.10 cluster with "Integrate with platform" enabled and checked [BACKPORT]

---

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx

Backport of #1821 
> https://issues.redhat.com/browse/MGMT-12382
> 
> DHCP allocation is not supported for nutanix hosts (even if platform integration was not enabled). We need to check the supported-platforms instead of cluster.platform.type to determine whether to hide the DHCP checkbox or not.
> 
> Note that it takes a second to get the `supported-platforms` and check for nutanix. So for that second the DHCP checkbox might appear and then disappear. I figured not-hiding it initially was better than hiding it and having it appear after a second (I assume there will be more people with non-nutanix hosts than vice versa).
> 
> If anyone has any ideas for how to avoid this flashing, they are welcome.

MGMT-12382 - Nutanix cluster - Trying to enable DHCP for vips returns "The DHCP server failed to allocate the IP" [BACKPORT]

---

src/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx

I've extracted from https://github.com/openshift-assisted/assisted-ui-lib/pull/1826 the part that's about the actual bugfix for https://issues.redhat.com/browse/MGMT-13037
Now is PR is equivalent to the Backport for v2.13 https://github.com/openshift-assisted/assisted-ui-lib/pull/1833/files
I'll update the other PR to remove that part, so that it's only about putting back the "Platform integration" details in the "Review & Create" page. I'll create a separate ticket for that.

MGMT-13037 Make link generic based on PlatformType

---

src/ocm/components/clusterConfiguration/review/ReviewPreflightChecks.tsx
src/ocm/components/clusterConfiguration/review/ReviewStep.tsx
src/ocm/components/clusterConfiguration/review/ReviewSummary.tsx
src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx

Extracted from https://github.com/openshift-assisted/assisted-ui-lib/pull/1826 everything except the new design for the Platform Integration note.
-   The section "validations" had been renamed to "preflight checks" although the design was not updated
-   Increased the spacing in the "preflight checks" section titles.

MGMT-9722 Preflight validations with better spacing

---

src/ocm/components/clusterDetail/ClusterProperties.tsx

Related to https://issues.redhat.com/browse/MGMT-11964
In multiarch clusters, change the text multi for "Multiple CPU architectures" in the Review&Create page:

MGMT-11964: Change text multi for "Multiple CPU architectures" 

---

src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx

- getNormalizedVersion function tries to get the version from releaseImage and if it fails it uses clusterImageSet name
Fixes MGMT-13054

MGMT-13054 Fix feature support in CIM

---

src/ocm/components/clusterWizard/ClusterPlatformIntegrationHint.tsx
src/ocm/components/clusterWizard/ClusterWizardFooter.tsx

Related to https://issues.redhat.com/browse/MGMT-13087
For OCP <= 4.10 ->  integration with Nutanix is unsupported -> We don't have to show the nutanix message in the host discovery step:

MGMT-13087: Not show nutanix message in host discovery step when nutanix is not supported

---

src/ocm/components/hosts/OdfDisksManualFormattingHint.tsx

Related to https://issues.redhat.com/browse/MGMT-13062
Change the inline alert in odf installations to tell the user that disks needs to be formatted:

MGMT-13062: Change alert in odf installations about formatting installation disks

---

src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx

- getNormalizedVersion function tries to get the version from releaseImage and if it fails it uses clusterImageSet name
Fixes MGMT-13054
Cherry-picked from fa97fa20

[2.7-cim] MGMT-13054 Fix feature support in CIM

---

locales/en/translation.json
src/common/config/constants.ts
src/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
src/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-12952
Change LVMO operator's text to LVMS operator's text:

MGMT-12952: LVMO operator is going to be renamed to LVMS  in 4.12

---

locales/en/translation.json
src/common/config/constants.ts
src/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
src/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-12952
Change LVMO operator's text to LVMS operator's text:

MGMT-12952: LVMO operator is going to be renamed to LVMS in 4.12 (master)

---

src/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-12952
Followup of #1846 
Change LVMO operator's text to LVMS operator's text:

MGMT-12952: LVMO operator is going to be renamed to LVMS in 4.12 - followup

---

.github/workflows/on-pull-request.yaml
.github/workflows/on-push.yaml
.github/workflows/on-release.yaml

https://issues.redhat.com/browse/MGMT-12825
Updated Github actions to remove deprecation warnings for Node 12.
New versions have been migrated to Node 16.
See:
https://github.com/redhat-actions/push-to-registry/releases/tag/v2.7
https://github.com/redhat-actions/buildah-build/releases/tag/v2.11

MGMT-12825 Use new Github actions updated to Node16

---

locales/en/translation.json
src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

Related to https://issues.redhat.com/browse/MGMT-13103
UI should block UMN in case of Nutanix platform:

MGMT-13103: Block UMN option in case we're in nutanix platform

---

.gitignore

the monorepo introduce this new folder called `apps`. Content in there is ignored by default in the monorepo dev branch but not in master. I'm adding this rule to the .gitignore in order to allow switching between branches faster.

NO_ISSSUE: Ignore everything inside apps dir but assisted-ui

---

package.json
src/common/components/hosts/HostValidationGroups.tsx
src/common/components/ui/formik/utils.ts
src/common/utils.ts
src/ocm/api/utils.ts
src/ocm/components/clusterDetail/FailedOperatorsWarning.tsx
src/ocm/components/clusterWizard/ClusterPlatformIntegrationHint.tsx
src/ocm/components/clusterWizard/wizardTransition.ts
src/ocm/components/clusters/Clusters.tsx
src/ocm/components/clusters/ClustersListToolbar.tsx
src/ocm/components/clusters/clusterPolling.ts
src/ocm/reducers/clusters/clustersSlice.ts
src/ocm/reducers/clusters/currentClusterSlice.ts
src/ocm/services/InfraEnvIdsCacheService.ts
src/ocm/services/OperatorsService.tsx

- More Typescript v4 fixes.
Added a typed equivalent to `Object.keys` which returns a type based on the object.
This makes the casting when accessing the values unnecessary.

Fix typescript 4 errors part 3

---

package.json

Solving issue with exports of translation files:
```
$ eslint src --ext js,jsx,ts,tsx && yarn  prettier
(node:318907) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./locales/" in the "exports" field module resolution of the package at /home/camadorg/dev/assisted-installer/uhc-portal/node_modules/openshift-assisted-ui-lib/package.json.
Update this package.json to use a subpath pattern like "./locales/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Depending on the node version, it can be an error
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './locales/en/translation.json' is not defined by "exports" in /home/user/workspace/uhc-portal/node_modules/openshift-assisted-ui-lib/package.json
Occurred while linting …
```

Correct deprecated translation exports

---

src/ocm/hooks/useInfraEnv.ts
src/ocm/hooks/useInfraEnvId.ts

In the new cluster flow, the clusterId does not exist. Called from `FeatureSupportLevelProvider`.

Fix useInfraEnv() for missing clusterId (new cluster flow)

---

src/common/components/featureSupportLevels/FeatureSupportLevelContext.tsx
src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
src/ocm/components/clusterConfiguration/review/ReviewClusterDetailTable.tsx
src/ocm/components/clusterDetail/ClusterProperties.tsx
src/ocm/components/featureSupportLevels/featureStateUtils.ts

Make the new `activeFeatureConfiguration` optional in FeatureSupportLevelData as it is being used in ACM.
Fixes Typescript 4 errors.

Make new info optional in common FeatureSupportLevelData

---

package.json
src/common/components/hosts/EditHostForm.tsx

https://issues.redhat.com/browse/MGMT-11073
After clicking on "change", the field for the host name was still editable, so users could keep typing on it even though it would have no effect.
We now disable the field while an action is in progress.
https://user-images.githubusercontent.com/829045/215818835-595ff6eb-e630-4e50-b414-bb8757f039e4.mp4

MGMT-11073: Block hostname field while action is in progress

---

src/ocm/components/clusterConfiguration/staticIp/components/StaticIpHostsArray.tsx

https://issues.redhat.com/browse/MGMT-13572
Allow deletion of the first Static IP host, but only if there is at least another one.
Meaning it must not be possible to not have at least one host.

MGMT-13572: Allow deletion of first Static IP host if not also last

---

locales/en/translation.json
package.json
src/common/components/clusterConfiguration/UploadSSH.tsx
src/common/components/ui/formik/validationSchemas.ts
src/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx

https://issues.redhat.com/browse/MGMT-13244
- SSH upload field now allows spaces and \n
- Spaces and empty lines get trimmed on blur
- Newlines are used as separators between SSH keys
- SSH public keys must be unique
These changes shouldn't affect uses of the UploadSSH component outside `/ocm`.

MGMT-13244 - Add host ssh keys does not allow space or \n for next key

---

src/common/components/ui/OpenShiftVersionDropdown.tsx
src/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx

https://issues.redhat.com/browse/MGMT-13677
The warning about the version not being production-ready has stopped being displayed.
The previous code relied on the matching of the labels, but for Beta version, it wasn't finding a version that matched, because the label had some extra text ("Developer Preview release"). 
What finally broke it is this change https://github.com/openshift-assisted/assisted-ui-lib/pull/1877/files#diff-e9b056fd8eab90b0a2096e8e64661a8cb4106723abb935e099cb9faa23b18117R43
but IMO if we don't find the match, we should not show the warning. There should always be a match, as the selected version must be on of the dropdown values.
Now we are matching on the value which is always the same, no matter if we append some text to the rendered item.

MGMT-13677: Fix non-production warning only for appropriate versions

---

src/ocm/components/clusterWizard/Operators.tsx
src/ocm/components/hosts/use-hosts-table.tsx

https://issues.redhat.com/browse/MGMT-13788
- In Operators page, if the cluster fails to update, we must show the detailed API error message.
- Fixed in `use-hosts-table` too.

MGMT-13788: Show API error message in actions

---

locales/en/translation.json
src/common/components/clusterConfiguration/FormatDiskWarning.tsx

Related to https://issues.redhat.com/browse/MGMT-13789
Before the changes:
The inline alert message says" “All bootable disks will be formatted during installation. Make sure to backup any sensitive data."
After the changes:

MGMT-13789: Inline alert message in storage step about bootable disks should include info about read-only disks

---

src/common/config/constants.ts
src/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx

https://issues.redhat.com/browse/MGMT-13700
For LVMS, starting in OpenShift 4.12 there is documentation about the operator configuration.
Added a link for the operator.
LVMS, link is shown
LVM, link not shown

MGMT-13700: Add learn more link for LVMS operator

---

src/common/components/ui/formik/validationSchemas.ts

Related to https://issues.redhat.com/browse/MGMT-13855
We change the validation of base domain field because causes problems in the UI.
The problem is related to https://javascript.info/regexp-catastrophic-backtracking
Changing the previous regex:
const BASE_DOMAIN_REGEX = /^([a-z0-9]+(-[a-z0-9]+)*)+$/;
To a new regex:
const BASE_DOMAIN_REGEX = /^([a-z0-9]+(-[a-z0-9]+)*)$/;
Solve this problem.
https://issues.redhat.com/secure/attachment/12921510/vokoscreenNG-2023-03-03_08-59-36.mp4

MGMT-13855: Base domain field validation causing the UI to get stuck

---

src/common/components/ui/formik/validationSchemas.ts

Related to https://issues.redhat.com/browse/MGMT-13855
We change the validation of base domain field because causes problems in the UI.
The problem is related to https://javascript.info/regexp-catastrophic-backtracking
Changing the previous regex:
const BASE_DOMAIN_REGEX = /^([a-z0-9]+(-[a-z0-9]+)*)+$/;
To a new regex:
const BASE_DOMAIN_REGEX = /^([a-z0-9]+(-[a-z0-9]+)*)$/;
Solve this problem.
https://issues.redhat.com/secure/attachment/12921510/vokoscreenNG-2023-03-03_08-59-36.mp4

MGMT-13855: Base domain field validation causing the UI to get stuck (2.16)

---

src/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-13856
LVMS should be enabled for SNO ARM cluster:
https://user-images.githubusercontent.com/11390125/223037368-c21ee41f-1f5d-4564-bf4e-228a65e08b1c.mp4

MGMT-13856: LVMS should be enabled for SNO+ARM clusters

---

src/ocm/components/featureSupportLevels/featureStateUtils.ts

Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1963

MGMT-13856: LVMS should be enabled for SNO+ARM clusters - 2.16

---

src/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx

Related to https://issues.redhat.com/browse/MGMT-14214
Disable and uncheck SNO checkbox when IBM Power or IBM Z archs are selected in "Cluster details" page:
https://user-images.githubusercontent.com/11390125/229786801-588003b0-94d4-4ed9-8686-f2856f1211c8.mp4

MGMT-14214: Disable and uncheck SNO checkbox when choose IBM Power or IBM Z archs 

---

src/ocm/components/HostsClusterDetailTab/utils.ts

Related to https://issues.redhat.com/browse/MGMT-14270
When cluster is in status 'installed' we need to show the 'Add hosts' tab.
Before the change:
After the change:

MGMT-14270: We need to show 'Add hosts' tab to cluster with  'installed' status

---

src/common/types/cpuArchitecture.ts
src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
src/ocm/services/Day2ClusterService.ts

Related to https://issues.redhat.com/browse/MGMT-14290
The CPU arhcitectures drop down list should be created by the release image architecture and not by the support-level supported architectures. With this change we avoid some errors that happens in day2 clusters.
Before the change:
After the change:

MGMT-14290: Filling CpuArchitectureDropdown from release image architectures

---

src/ocm/services/Day2ClusterService.ts

Related to https://issues.redhat.com/browse/MGMT-14320
For clusters wih Power/Z or s390 archs the  infraenvs are not created correctly because UI was not sending the day1 cpu architecture to get supported architectures. With this PR this bug will be fixed.

MGMT-14320: Problems in 'Add hosts' tab for Power/Z clusters 

---

src/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx

Related to: https://issues.redhat.com/browse/MGMT-14170
For s390 clusters only 'Minimal ISO' should be disabled in 'Add hosts' modal:

MGMT-14170: Allow ipxe script download for s390 clusters

---

apps/assisted-ui/vite.config.ts
libs/ui-lib/package.json

Using 'development' as the package exports condition clashes with the settings in the uhc-portal where Webpack is used and the default condition is 'development'. Since that project's Webpack config is poorly configured, we are not able to tell them to import from the default condition without triggering a major refactor on their side. This change settles the issue with minimal impact on their side.

Use custom resolve conditions ('source' instead of 'development')

---

libs/ui-lib/lib/ocm/services/apis/EventsAPI.ts

https://issues.redhat.com/browse/MGMT-14519
**Before:**
**After:**

New cluster events - adding "%" sign to search text field return all events instead of specific ones

---

package.json

Changes the lib name to `@openshift-assisted/ui-lib`
This PR is meant to allow publishing the lib, after the account owning `openshift-assisted-ui-lib` in npm got locked.
It is meant for `2.7.11-cim`.
We'll need to update the pkg name and import specifiers in solostron/console after bumping the lib version in the 2.7 branch.

NO-ISSUE: Changes the package name in order to allow publishing it under @openshift-assisted

---

src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/types.ts

Backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2120

[2.7-cim] Remove unused 'count' from NetworkStepProps

---

libs/ui-lib/lib/ocm/hooks/useInfraEnvId.ts
libs/ui-lib/lib/ocm/services/InfraEnvIdsCacheService.ts
libs/ui-lib/lib/ocm/services/InfraEnvsService.ts

https://issues.redhat.com/browse/MGMT-14640
`InfraEnvCache.getInfraEnvId()` is now returning `Error` instead of `null`, the condition in `InfraEnvsService` needs to be changed accordingly.
Otherwise the UI is stuck loading in case the infra env hasn't been cached previously.

MGMT-14640: Infra envs cache return types [BACKPORT]

---

libs/ui-lib/lib/ocm/hooks/useInfraEnvId.ts
libs/ui-lib/lib/ocm/services/InfraEnvIdsCacheService.ts
libs/ui-lib/lib/ocm/services/InfraEnvsService.ts

`InfraEnvCache.getInfraEnvId()` is now returning `Error` instead of `null`, the condition in `InfraEnvsService` needs to be changed accordingly.
Otherwise the UI is stuck loading in case the infra env hasn't been cached previously.

MGMT-14640: InfraEnvs cache return type hotfix

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx

New official names:
IBM zSystems (s390x)
IBM Power (ppc64le)

MGMT-14645: Change Power and z names in the UI

---

libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx

Related to https://issues.redhat.com/browse/MGMT-14679
On-prem AI day2 add host, after cluster is installed, trying to add day2 host, but getting "Error loading data".
Now this don't happen:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/1516f304-eb05-47ca-bf54-26dcd0438c16

MGMT-14679: Solve problems with Add hosts in onprem clusters

---

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts

PROXY_DNS_REGEX regex validation timeout.
The . (dot) in the group 1 of the old regex introduce an extremely large number of permutations. Moving the dot to the second group in the regex.
The wildcard regex is also not needed, because we already returned true if the value equals '*'.

MGMT-14197: Fix catastrophic backtracking in no proxy dns regex

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
libs/ui-lib/lib/ocm/hooks/useClusterCustomManifests.ts

Related to https://issues.redhat.com/browse/MGMT-14718
Previously, when uploading a manifest and choosing a file name , every time user add a char or remove it , a patch request was sent to BE, and a new manifest is added.
Now, this does not happen, see the video:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/885490b2-8d11-4651-a4cc-b795a0e89824

MGMT-14718: Problems renaming manifests file name

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx

MGMT-14727: Change error text when validate unique file names in custom manifests - 2.20

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx

Related to https://issues.redhat.com/browse/MGMT-14727
Change error text:

MGMT-14727: Change error text when validate unique file names in custom manifests

---

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts

Related to https://issues.redhat.com/browse/MGMT-14807
It reverts some changes done in #2133 
We need to change the base domain regexp because causes catastrophic backtracking in some cases:

MGMT-14807: Change base domain validation regexp to avoid catastrophic backtracking problems

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx

Related to https://issues.redhat.com/browse/MGMT-14972
We need to disable image dropdown when we use OCI (external partners):

MGMT-14972: Full iso should be blocked in case of OCI (external partners)

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-14543
Change texts for provisioning types:

MGMT-14543: Change  full/minimal/ipxe description texts

---

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetail.tsx

Related to https://issues.redhat.com/browse/MGMT-14833
After day1 cluster is installed, add hosts button is not clickable.

MGMT-14833: On-Prem Day2 - add hosts button is not clickable

---

libs/ui-lib/lib/ocm/components/AddHosts/types.ts
libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/utils.ts
libs/ui-lib/lib/ocm/components/index.ts
libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/index.ts
libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/types.ts
libs/ui-lib/lib/ocm/index.ts
libs/ui-lib/lib/ocm/services/CpuArchitectureService.ts
libs/ui-lib/lib/ocm/services/NewFeatureSupportLevelsService.ts
libs/ui-lib/lib/ocm/services/apis/NewFeatureSupportLevelsAPI.ts
libs/ui-lib/lib/ocm/services/apis/index.ts
libs/ui-lib/lib/ocm/services/index.ts

Related to https://issues.redhat.com/browse/MGMT-14996
Related to https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/4247
Before these changes we can not add hosts to SNO cluster with 4.14 version.
Now it works:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/84b6bdcf-ee48-4146-8fbd-47e7942b48a4

MGMT-14996:  Day 2 -Can't add hosts to SNO 4.14 cluster

---

libs/ui-lib/lib/common/features/featureGate.tsx

Related to https://issues.redhat.com/browse/MGMT-14827
Remove multi-arch-related code in the UI. 
To allow all users can use multi-arch we mark ASSISTED_INSTALLER_MULTIARCH_SUPPORTED feature true by default.

MGMT-14827: Remove multiarch capacity for UI

---

libs/ui-lib/lib/common/components/ui/ExternalLink.tsx

Related to https://issues.redhat.com/browse/MGMT-14842
In "Technology Preview" popover link doesn't open up URL. With these changes the link works well:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/c19d00fe-52d3-4e19-acca-856e0885b188

MGMT-14842: In "Technology Preview" popover link doesn't open up URL

---

docs/CONTRIBUTING.md
libs/ui-lib-tests/README.md
package.json

- Fixed some typos
- The command `yarn test:all` from main `package.json` was incorrect. I have modified it to be able to run the integration tests, or to open them. Or is there a preferred way to run them? In that case, we should drop the `yarn test:all` command.

Improve setup documentation

---

libs/ui-lib-tests/cypress/integration/ui-behaviour/events-modal.cy.ts

https://issues.redhat.com/browse/MGMT-14787
The spinner indicates that the UI is waiting for a response from the BE. So if it isn't present in the DOM, the new events should surely be loaded.
Fingers crossed.

MGMT-14787: Fix flaky event pagination tests

---

.eslintrc.json
.github/workflows/pull-request.yaml
docs/CONTRIBUTING.md
libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts
libs/ui-lib/tsconfig.eslint.json
libs/ui-lib/tsconfig.json
package.json
yarn.lock

[Vitest](https://vitest.dev/api/) is introduced. More tests will be added in follow-ups.
To run existing unit tests, call
```
yarn test:unit
```

Introduce vitest for unit-testing

---

libs/ui-lib-tests/cypress/integration/create-multinode/0-create-cluster.cy.ts
libs/ui-lib-tests/cypress/integration/create-multinode/1-host-discovery.cy.ts
libs/ui-lib-tests/cypress/integration/create-multinode/3-review.cy.ts
libs/ui-lib-tests/cypress/integration/create-sno/0-create-cluster.cy.ts
libs/ui-lib-tests/cypress/integration/create-sno/1-host-discovery.cy.ts
libs/ui-lib-tests/cypress/integration/create-sno/3-review.cy.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/1-create-cluster-with-custom-manifests.cy.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/4-view-custom-manifests-review-and-create-page.cy.ts
libs/ui-lib-tests/cypress/integration/dualstack/3-review.cy.ts
libs/ui-lib-tests/cypress/integration/features/disk-encryption.cy.ts
libs/ui-lib-tests/cypress/integration/static-ip/0-create-cluster.cy.ts
libs/ui-lib-tests/cypress/integration/static-ip/3-configure-static-ip-yaml.cy.ts
libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts
libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts
libs/ui-lib-tests/cypress/support/variables/storage-step.ts
libs/ui-lib-tests/cypress/views/bareMetalDiscovery.ts
libs/ui-lib-tests/cypress/views/bareMetalDiscoveryIsoModal.ts
libs/ui-lib-tests/cypress/views/clusterDetails.ts
libs/ui-lib-tests/cypress/views/clusterList.ts
libs/ui-lib-tests/cypress/views/common.ts
libs/ui-lib-tests/cypress/views/hostsTableSection.ts
libs/ui-lib-tests/cypress/views/installationPage.ts
libs/ui-lib-tests/cypress/views/networkingPage.ts
libs/ui-lib-tests/cypress/views/reviewCreate.ts
libs/ui-lib-tests/cypress/views/storagePage.ts

- When integration tests fail by doing text comparisons, sometimes we use the pattern `.should('contain')` which doesn't output the expected result. That makes debugging the issue harder.
We should use `.should('contain.text')` which prints what text it found instead of the expected one.
| before                                       | after                            |
|----------------------------------------------|----------------------------------|
| ![without-diff](https://github.com/openshift-assisted/assisted-installer-ui/assets/829045/9d7eb716-5c39-43b5-b622-96213921e35f) |![with-diff](https://github.com/openshift-assisted/assisted-installer-ui/assets/829045/6e44667a-4746-4697-afac-9dacc1b824d5)|
- In other cases, we were using `.contains(text)` to validate the text content. But …

Improve text assertions

---

libs/ui-lib-tests/cypress/@types/Cypress.d.ts
libs/ui-lib-tests/cypress/fixtures/custom-manifests/1-cluster-created.ts
libs/ui-lib-tests/cypress/fixtures/custom-manifests/index.ts
libs/ui-lib-tests/cypress/fixtures/custom-manifests/manifests.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/1-create-cluster-with-custom-manifests.cy.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/4-view-custom-manifests-review-and-create-page.cy.ts
libs/ui-lib-tests/cypress/support/interceptors.ts
libs/ui-lib-tests/cypress/support/utils.ts
libs/ui-lib-tests/cypress/views/common.ts
libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/constants.ts
libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts

https://issues.redhat.com/browse/MGMT-15152
- While writing Integration tests for Day2, I noticed some intermitent test failures.
Sometimes, the test would click on the nav wizard and it would not move to the expected step. This is due to the effect that loads the custom manifests, and sometimes it would jump to the customManifests / review step even if the user had selected a previous step.
- I also noted that some requests were not correctly intercepted (eg. delete of a custom manifest includes the folder and filename, and the POST was not mocked.
- Finally, did some changes in the custom manifests tests to align them to use the "lastWizardSignal" as the other tests do.

[MGMT-15152] Fix jump bug and adapt tests

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-15167
Change string for IBM Z (s390) CPU architecture:

MGMT:15167: Change IBM zSystems string to IBM Z

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx

Related to https://issues.redhat.com/browse/MGMT-14805
BEFORE:
If you have a cluster created and you go back to the cluster details page and click next, custom manifests are created even if the checkbox is not selected.
AFTER:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/9c0217b1-1372-48b4-8b52-5cef022b7c7f

MGMT-14805: Custom manifests are added when editing an existing cluster in Cluster Details Page

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

Remove old references to ARM64_ARCHITECTURE_WITH_CLUSTER_MANAGED_NETWORKING and other uses of deprecated feature support levels API.

MGMT-14187: Deprecate ARM64_ARCHITECTURE_WITH_CLUSTER_MANAGED_NETWORKING

---

libs/ui-lib/lib/common/config/constants.ts

Related to https://issues.redhat.com/browse/MGMT-14593
Update the link of "follow these steps" in  'Add hosts' modal for day2 clusters:

MGMT-14593: Update link to know if cluster supports multiarch

---

libs/ui-lib/lib/cim/components/ClusterDeployment/wizardTransition.test.ts

Adds unit tests for trasitions checks in the CLuster create wizard for CIM.
Depends on:
---
Similar set for the OCM transitions will follow, most probably with an e2e scenario (not possible in CIM).

Add CIM wizardTransition unit tests

---

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterInstallationProgressCard.tsx

Related to https://issues.redhat.com/browse/MGMT-14284
Before changes assisted installer detail card was collapsed by default:
After changes assisted installer detail card will be expanded by default:

MGMT-14284: Show the assisted installer detail card expanded by default

---

src/cim/components/Hypershift/modals/ManageHostsModal.tsx
src/cim/components/Hypershift/utils/nodepool.ts

ACM 2.7:
Backport of da86af7151d518c8c1d054e220711f52cdd361f9 (PR: #2157)

MGMT-14130: (ACM 2.7) Fix hypershift scaling and mapping of AgentMachines to HostedCluster

---

libs/ui-lib-tests/cypress/fixtures/infra-envs/feature-support.ts
libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts
libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
libs/ui-lib-tests/cypress/views/forms/ClusterDetailsForm.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx

Related to https://issues.redhat.com/browse/MGMT-15328
- Before the change:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/d03daeb5-60dd-425f-ae08-1846fdd3d422
- After the change:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/6107d5eb-fc73-4ed6-8b67-673330d1b839

MGMT-15328: External partners remains selected after OCP < v4.14 is selected

---

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
libs/ui-lib/lib/common/components/clusterWizard/types.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/HostsNetworkConfigurationControlGroup.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-15016
When user select OCI option, the hosts's network configuration should be disabled and we show a tooltip explaining what happens:

MGMT-15016:  Block static ip if oci is selected

---

libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/ExpandedManifest.tsx

https://issues.redhat.com/browse/MGMT-15330

MGMT-15330: Make the custom manifest YAML editor read-only

---

libs/locales/lib/en/translation.json
libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStepValidationsAlert.tsx

https://issues.redhat.com/browse/MGMT-13808
The blue alert will not be shown anymore.

MGMT-13808: Remove unnecessary cluster validations alert

---

libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx

Related to https://issues.redhat.com/browse/MGMT-15367
Custom manifest files should be unique as openshift folder files are merged to manifests.
Before changes you can have same file name in different folders for custom manifests:
After changes you custom manifests file names should be unique regardless folder:

MGMT-15367: Custom manifests names should be unique

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-15376
Before changes browser gets stuck:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/d0cf5b16-3735-4413-93ce-b1fc9cb4bd68
After changes:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/12c08979-b1ad-48b8-80aa-fe9d8152761f

MGMT-15376: Browser gets stuck after selecting OCP version 4.9

---

libs/ui-lib/lib/common/components/ui/ClusterEventsToolbar.tsx

https://issues.redhat.com/browse/MGMT-14774
The issue with different sessions showing different clusters should be resolved by https://github.com/openshift-assisted/assisted-installer-ui/pull/2292.
However, I noticed that if there are no active (non-deleted) hosts in the cluster, the hosts dropdown in the cluster events modal is disabled and the users cannot filter cluster-level and deleted-hosts events. I think we should keep the dropdown enabled at all times.

MGMT-14774: Add hosts cluster events - no events related to previous added hosts

---

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContext.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
libs/ui-lib/lib/ocm/components/hosts/ClusterHostsTable.tsx
libs/ui-lib/lib/ocm/components/hosts/use-hosts-table.tsx

https://issues.redhat.com/browse/MGMT-15075
The custom manifests requests were coming from the `ClusterWizardContext`. (Which is not needed in day2 as there is no wizard.)

MGMT-15075: Day2 - Do not request custom manifests

---

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
libs/ui-lib-tests/cypress/views/forms/ClusterDetails/ClusterDetailsForm.ts
libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/SnoField.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-15530
When SNO option is selected, we need to disable Nutanix and vSphere options in external platform integration dropdown:

MGMT-15530: external platform integration dropdown - disable Nutanix  and Vsphere when sno is selected

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationNote.tsx

Related to https://issues.redhat.com/browse/MGMT-15616
Until we have a correct link for OCI platform integration, we hide it.

MGMT-15616: Hide OCI platform integration "learn more" link until we have correct link

---

libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx

Related to https://issues.redhat.com/browse/MGMT-15666
We have some problems in cluster details form because we don't clear alerts correctly.
Workflow that didn't work previously:
1. Create new cluster with this values:
name: 123456
domain:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaa
2. Press next -> Works.
3. Press back
4. Changed name to 123456777  ---> next fails message
5. Revert to 123456  --> window passed but alerts appears in Operators page.

MGMT-15666: Clear alerts when user clicks next button in cluster details form

---

libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx

https://issues.redhat.com/browse/MGMT-13396
This pretty much only happens when users mess with the API and add another infraEnv to their Day1 cluster.
**Before:**
**After:**

MGMT-13396: Cluster with multiple infra-envs - UI throws "cluster not found error"

---

libs/ui-lib-tests/cypress/fixtures/custom-manifests/files/manifest_multiple.yaml
libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
libs/ui-lib-tests/cypress/views/common.ts
libs/ui-lib/lib/common/utils.ts

Related to https://issues.redhat.com/browse/MGMT-15714
We change the code of UI to allow users to load multi-yaml files in custom manifests page:

MGMT-15714: Allow to load multi-yaml files in custom manifests page

---

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-15708
UI should block the option to select power/z cpu arch + SNO + OCI platform.
After changes:

MGMT-15708:  cluster details page - block power/z + SNO + OCI platform

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-15816
Now, in Networking Page we disable/enable UMN or CMN depending calls of feature support levels API using new param platform_type:
1. For example, for 'Nutanix' cluster:
Then we can see this in Networking Page:

MGMT-15816: Use platform type to call support-levels API in Networking page - nutanix and vsphere leftovers

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

MGMT-15816: Use platform type to call support-levels API in Networking page - nutanix and vsphere leftovers -2.25

---

libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx
libs/ui-lib/lib/cim/components/ClusterDeployment/helpers.ts

The root cause was that the ACI got into a state where we are stop rendering `EventsModalButton`.
I've addressed this by:
- including `ready` state to `shouldShowClusterInstallationProgress` (thus even when cluster is `ready (which means ready to start installation)` we are still showing the progress installation & events button)
- not rendering the events modal next to `EventsModalButton` but higher up the tree. This way, even if Events modal btn is not rendered, the events modal still keeps showing

MGMT-15652 Fix disappearing events modal

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmBaseDomainField.tsx

Related to https://issues.redhat.com/browse/MGMT-13852
New helper text in base domain field in Cluster Details page:

MGMT-13852: Change base domain helper text

---

libs/locales/lib/en/translation.json
libs/ui-lib/lib/common/components/clusterWizard/ReviewValidations.tsx
libs/ui-lib/lib/common/config/constants.ts

Related to https://issues.redhat.com/browse/MGMT-15599
In R&C page,failed validations in preflight check shows only the validation ID but not the message itself.
We change it for platform-requirements satisfied validation:

MGMT-15599: Add  message when platform-requirements-satisfied validation fails

---

libs/ui-lib/lib/common/features/featureGate.tsx
libs/ui-lib/lib/common/types/cpuArchitecture.ts
libs/ui-lib/lib/ocm/components/AddHosts/AddHosts.tsx
libs/ui-lib/lib/ocm/components/AddHosts/InventoryAddHost.tsx
libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx

Related to https://issues.redhat.com/browse/MGMT-15062
After 2.21.7 we allow all users to use MultiArch capacity. We need to remove the references of ASSISTED_INSTALLER_MULTIARCH_SUPPORTED in the code of assisted-installer-ui.

MGMT-15062: Remove references to ASSISTED_INSTALLER_MULTIARCH_SUPPORTED feature

---

libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx
libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/TangServers.tsx

Related to https://issues.redhat.com/browse/MGMT-13220
After setting encryption on the cluster details screen and clicking "Next" and then "Back", we have to show the disabled tooltip:

MGMT-13220: Add disabled field tooltip on encryption type components

---

libs/ui-lib/lib/common/components/hosts/utils.ts

Related to https://issues.redhat.com/browse/MGMT-15974
The fact that the Day1 hosts keep displaying status "Finalizing" when you transform the cluster to Day2 could be confusing. The solution here is not do this override outside of OCM.
After changes:

MGMT-15974: [PSI / On-prem] - Day2 - After adding new host, day1 hosts move to Finalizing status

---

.github/workflows/on-push.yaml

Do not push assisted-ui quay.io images created after a new CIM release
backport of https://github.com/openshift-assisted/assisted-installer-ui/commit/a3014139bb92f168597e7e3e6ae5e6dc27b4f99d

[2.7] Update push-to-master.yaml

---

libs/ui-lib/lib/common/components/featureSupportLevels/FeatureSupportLevelBadge.tsx
libs/ui-lib/lib/common/components/newFeatureSupportLevels/NewFeatureSupportLevelBadge.tsx
libs/ui-lib/lib/common/components/ui/DeveloperPreview.tsx
libs/ui-lib/lib/common/components/ui/PreviewBadge.tsx
libs/ui-lib/lib/common/components/ui/TechnologyPreview.tsx
libs/ui-lib/lib/common/components/ui/index.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx

https://issues.redhat.com/browse/MGMT-16041
Extracts the tech and dev preview components from PreviewBadge.tsx and declares them in their own modules

MGMT-16041: Splits the preview badges into one component per module

---

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-16069
After changes:

MGMT-16069: OCI is enabled if SNO + OCP version < 4.14 - should be blocked

---

libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx

Related to https://issues.redhat.com/browse/MGMT-16151
Changes the way that UI is downloading installation logs (with file-saver library) because big files don't work in some browsers.

MGMT-16151: Failed to download installation logs form cluster with 103 nodes

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-15919
Before chages, when open the add hosts tab in arm cluster, default is still x86, although its disabled:
After changes, when open the add hosts tab in arm cluster, default is arm:

MGMT-15919: If day1 cluster is ARM cpu arch, then only ARM nodes can be added in Day2

---

libs/ui-lib/lib/common/config/constants.ts

Related to https://issues.redhat.com/browse/MGMT-16213
In Operators Page change the  "Learn more" link in MCE operator to: https://docs.openshift.com/container-platform/4.14/architecture/mce-overview-ocp.html

MGMT-16213: Change MCE learn more link to 4.14 version

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmBaseDomainField.tsx

Related to https://issues.redhat.com/browse/MGMT-16027
New info text for base domain field:

MGMT-16027: Base domain helper info should be updated

---

libs/ui-lib-tests/cypress/fixtures/create-mn/requests.ts
libs/ui-lib-tests/cypress/fixtures/create-sno/5-cluster-ready.ts
libs/ui-lib-tests/cypress/fixtures/day2-flow/day1-ai-cluster.ts
libs/ui-lib-tests/cypress/fixtures/dualstack/1-network-ready.ts
libs/ui-lib-tests/cypress/fixtures/dualstack/requests.ts
libs/ui-lib-tests/cypress/fixtures/storage/storage-cluster.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx

Related to https://issues.redhat.com/browse/MGMT-15125
UI to remove the Singular VIPs completely from the codebase and keep using plural VIPs.

MGMT-15125: Remove singular VIPs, continue to use the plural ones

---

libs/types/assisted-installer-service.d.ts
libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts
libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
libs/ui-lib/lib/common/types/clusters.ts

Related to https://issues.redhat.com/browse/MGMT-15125
We need to update our assisted-installer-service.d.ts with new changes of swagger.yaml from assisted-service to remove deprecated  api_vip and ingress_vip fields. (https://github.com/openshift/assisted-service/pull/5734)

MGMT-15125: Remove singular VIPs, continue to use the plural ones - followup

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-15919
If day1 cluster is ARM cpu arch, then only ARM nodes can be added in Day2:
Other options in dropdown are disabled:

MGMT-15919: If day1 cluster is ARM cpu arch, then only ARM nodes can be added in Day2 - followup

---

libs/ui-lib/lib/ocm/services/Day2ClusterService.ts

Related to https://issues.redhat.com/browse/MGMT-16354
Trying to add hosts in day2 throws an error when external_id of cluster is not none,baremetal,vsphere,nutanix or external.

MGMT-16354: Problem adding hosts when platform type is not none,baremetal,nutanix,vsphere,oci

---

libs/ui-lib/lib/common/components/ui/formik/AdditionalNTPSourcesField.tsx
libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts

Related to https://issues.redhat.com/browse/MGMT-16392
In the NTP dialog when we add an empty string we need to avoid browser freeze.

MGMT-16392: NTP text box allows to add empty string and browser freeze

---

libs/ui-lib/lib/common/components/clusterDetail/KubeconfigDownload.tsx
libs/ui-lib/lib/common/utils.ts
libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx

Related to https://issues.redhat.com/browse/MGMT-16197
Changes the way that UI is downloading kubeconfig logs (with file-saver library) because some files don't work in some browsers. The problem is that file-saver try to download logs open a popup and some browsers have popup blockers and then don't work. (Related to https://github.com/openshift-assisted/assisted-installer-ui/pull/2431)

MGMT-16197: Change the way to download kubeconfig logs

---

libs/ui-lib/lib/common/utils.ts

Related to https://issues.redhat.com/browse/MGMT-16197
Solves issue https://issues.redhat.com/browse/MGMT-16430
With last changes to download kubeconfig files, the browser was adding 'txt' extension to the downloaded file.
We need to change the type when we create the blob data to download.

MGMT-16197: Change the way to download kubeconfig logs - followup

---

libs/types/assisted-installer-service.d.ts
libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts
libs/ui-lib/lib/common/api/assisted-service/NewFeatureSupportLevelsAPI.ts
libs/ui-lib/lib/common/types/clusters.ts
libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
libs/ui-lib/lib/ocm/components/utils.ts
libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
libs/ui-lib/lib/ocm/services/ClustersService.ts
libs/ui-lib/lib/ocm/services/Day2ClusterService.ts

Related to https://issues.redhat.com/browse/MGMT-15692
To use OCI platform 
Instead of
```
platform: {
type: oci
}
```
we have to use:
```
platform: {
type: external
external: {
platformName: oci,
CloudControlerManager: External
}
}
```

MGMT-15692: Use the new API to define oci platform  - followup

---

libs/locales/lib/en/translation.json
libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx

BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2423

MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow [BACKPORT 2.8]

---

libs/ui-lib/lib/ocm/components/clusters/AssistedInstallerHeader.tsx

Related to https://issues.redhat.com/browse/MGMT-16480
What's new link is not working in OnPrem AI. We should remove it when we are outside OCM to avoid problems.

MGMT-16480: Remove what's new link outside OCM because does not work

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-16481
OCP 4.11 + nutanix integration should have dev-preview badge in UI.  We need to take into consideration the dev-preview from BE response in the external platform integration drodpdown.

MGMT-16481: Add developer preview badge in external platform integration dropdown when platform is dev-preview

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-16475
In case of x86 and SNO - UI shows integration box disabled because of "Platform integration is not supported when x86 is selected" and needs to show "Platform integration is not supported for SNO clusters":

MGMT-16475: Change reason for platform dropdown to be disabled

---

libs/ui-lib/lib/common/components/ui/PreviewBadge.tsx

Addresses https://issues.redhat.com/browse/OCMUI-1240
Visible in Chrome when clicking on the label

PreviewBadge: Disable focustrap

---

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/ClusterInstallationError.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx

Related to https://issues.redhat.com/browse/MGMT-16558
After changes:

MGMT-16558: Failed messages not cleaned after download cluster installation logs

---

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/ClusterInstallationError.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx

MGMT-16558: Failed messages not cleaned after download cluster installation logs - 2.30

---

libs/types/assisted-installer-service.d.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

Related to https://issues.redhat.com/browse/MGMT-16387
For clusters with OCP version > 4.15 the SDN option is unavailable.
- Cluster with OCP version 4.14:
- Cluster with OCP version >= 4.15:

MGMT-16387: Disable SDN option in OCP version > 4.15

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
libs/ui-lib/lib/ocm/components/utils.ts

Related to https://issues.redhat.com/browse/MGMT-16463
Enable multi-node LVMS OCP 4.15. 
The idea is to display in Operator page both ODF and LVM but the user can't choose both - if he chooses ODF - LVM should be disabled and viceversa.
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/245b00c0-d074-480a-bd2c-e72ebac9f7c7

MGMT-16463: Enable LVMS for OCP version 4.15 or above

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

MGMT-16776: DHCP checkbox should be removed as there is no sdn/ovn selection in OCP version 4.15 - 2.30

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

Related to https://issues.redhat.com/browse/MGMT-16776
DHCP checkbox should be removed as there is no sdn/ovn selectioRemove dhcp option in OCP version 4.15.

MGMT-16776: DHCP checkbox should be removed as there is no sdn/ovn selection in OCP version 4.15

---

libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

MGMT-16710: Operators page - LVMS and ODF are disabled once you turn on CNV+LVMS  - 2.30

---

libs/ui-lib/lib/common/api/utils.ts

This fix solves problems related with:
https://issues.redhat.com/browse/MGMT-16817
https://issues.redhat.com/browse/MGMT-16802
https://issues.redhat.com/browse/MGMT-16816

Fix problems with Sentry.Severity.Error using alternative way to send errors to Sentry

---

libs/ui-lib/lib/common/api/utils.ts

Fix problems with Sentry.Severity.Error using alternative way to send errors to Sentry -  2.30

---

libs/ui-lib/lib/cim/components/ClusterDeployment/NetworkConfiguration.tsx
libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts
libs/ui-lib/lib/common/components/clusterConfiguration/utils.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts

https://issues.redhat.com/browse/MGMT-15805
To my knowledge, SDN should not be used as the default networking type anymore. I've removed all of the related code.

MGMT-15805: OpenshiftSDN is the default SDN selected when installing a new cluster

---

libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx

Related to https://issues.redhat.com/browse/MGMT-17012
In networking page - use advanced networking conf text should be adjust to view:

MGMT-17012: Solving styling issues in Networking Page

---

libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx

Related to https://issues.redhat.com/browse/MGMT-17107
Replace history/location state when moving from the Operators step only when we are in Assisted Installer pages and not inside 'Overview' tab in OCM view.
How it works before change:
https://issues.redhat.com/secure/attachment/13147053/Screencast%20from%202024-03-03%2015-47-09.webm
And after changes:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/418b5af8-2bf2-4d27-ad4c-bb65ad89bb82

MGMT-17107: Update operators checkbox when cluster ready exits from cluster window when we are in 'Overview' tab inside OCM

---

libs/locales/lib/en/translation.json
libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsForm.tsx
libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx
libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/types.ts

https://issues.redhat.com/browse/MGMT-16982
Console PR:

MGMT-16982: Enable switching infra-availability-policy Single replica / HA

---

libs/ui-lib-tests/cypress/integration/static-ip/1-configure-static-ip-network-wide.cy.ts
libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/validations-new-cluster-page.cy.ts
libs/ui-lib-tests/cypress/support/variables/cluster-details.ts
libs/ui-lib-tests/cypress/views/clusterDetails.ts
libs/ui-lib/lib/common/components/clusterConfiguration/SecurityFields.tsx
libs/ui-lib/lib/common/components/ui/StaticTextField.tsx
libs/ui-lib/lib/common/components/ui/formik/CertificatesUploadField.tsx
libs/ui-lib/lib/common/components/ui/formik/CheckboxField.tsx
libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
libs/ui-lib/lib/common/components/ui/formik/InputField.tsx
libs/ui-lib/lib/common/components/ui/formik/LabelField.tsx
libs/ui-lib/lib/common/components/ui/formik/MultiSelectField.tsx
libs/ui-lib/lib/common/components/ui/formik/NumberInputField.tsx
libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx
libs/ui-lib/lib/common/components/ui/formik/SwitchField.tsx
libs/ui-lib/lib/common/components/ui/formik/TextAreaField.tsx
libs/ui-lib/lib/common/components/ui/formik/UploadField.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx

Related to https://issues.redhat.com/browse/MGMT-17130
Add correct id to <HelperItem> component when it's an error:

MGMT-17130: Add correct id to <HelperItem> components when shown errors

---

libs/ui-lib/lib/common/components/clusterConfiguration/SecurityFields.tsx

Related to https://issues.redhat.com/browse/MGMT-17155
- Before changes,  SSH key field in networking page - Error helper is duplicated:
- After changes, error helper is shown only once:

MGMT-17155: Remove error helper duplicated in SecurityFields in Networking Page

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx

Related to https://issues.redhat.com/browse/MGMT-17236
Add "aria-label" property to close button in host status popover to help cypress tests:

MGMT-17236: Add aria label property to close button in host status popover  to help cypress tests

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx

MGMT-17236: Add aria label property to close button in host status popover to help cypress tests - 2.31

---

libs/types/assisted-installer-service.d.ts
libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
libs/ui-lib/lib/common/utils.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx

Related to https://issues.redhat.com/browse/MGMT-15999
To change manifest "test1.yaml" users can create a manifest called "test1.yml.patch.1" with the contents:
---
- op: add
path: /spec/defaultNetwork
value:
ovnKubernetesConfig:
v4InternalSubnet: 100.65.0.0/16

MGMT-15999: Assisted Installer UI should allow patch manifests

---

libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-17475 and https://issues.redhat.com/browse/MGMT-17474
When custom OCP version selected the platform and cpu dropdowns needs to be updated:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/617b5c44-5e00-4c95-8cee-5e5c0919c88f

MGMT-17475: Updating CPU and platform dropdowns when OCP custom release is selected

---

libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx

Related to https://issues.redhat.com/browse/MGMT-17471 and https://issues.redhat.com/browse/MGMT-17472
Add maxLength to search input in OCP custom releases modal and not allow to select 'No results found' option:

MGMT-17471: Add maxLength to search input and not allow to select 'No results found' option

---

libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
libs/ui-lib/lib/common/components/ui/OpenshiftVersionDropdown.css

Related to https://issues.redhat.com/browse/MGMT-17473
Adding scrollbar to OpenshiftVersionDropdown component avoid problems about changing window layout.

MGMT-17473: Add scrollbar to OpenshiftVersionDropdown component

---

libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx

Related to https://issues.redhat.com/browse/MGMT-17501
Previously in OCP versions dropdown we don't show maintenance versions. With the latest changes in the API (that returns only latest releases in the cluster wizard page) we want to show all versions.
After changes:

MGMT-17501: Show all OCP versions in OpenshiftVersionDropdown (maintenance, production, beta, end-of-life

---

libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenShiftVersionModal.tsx

Related to https://issues.redhat.com/browse/MGMT-17504
In OpenshiftVersionModal add the correct behavior for every button:
- Select button: Select OCP version and add to the OpenshiftVersionDropdown
- Cancel button: Close the modal and don't change the OpenshiftVersionDropdown
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/2cab4b01-ec59-491b-9db9-a4ca1dcff8aa

MGMT-17504: Adjusting behavior of the OpenshiftVersionModal buttons

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts

Related to https://issues.redhat.com/browse/MGMT-17476
Solving problems with validations in Advanced Networking fields in Networking Page:

MGMT-17476: Solving problems with validations in Advanced Networking fields in Networking Page

---

libs/ui-lib/lib/common/components/hosts/MassChangeHostnameModal.tsx

Related to https://issues.redhat.com/browse/MGMT-17139
In  Mass host rename modal "Change" button needs to be disabled at start

MGMT-17139: Enable "Change" button in Mass Change Hostname Modal when hostname value is not empty

---

libs/ui-lib/lib/common/components/ui/DeveloperPreview.tsx
libs/ui-lib/lib/common/components/ui/PreviewBadge.tsx
libs/ui-lib/lib/common/components/ui/TechnologyPreview.tsx

Motivation: In OCM we have use case for showing dynamic badge content (https://issues.redhat.com/browse/OCMUI-1145) where we don't get separate "Learn More" URL but might render links in the text itself.
The existing `PreviewBadge` component supports this fine at run time, only the `popoverText: string` type was too restrictive at compile time.  
- Relaxed the type.
- Renamed `popoverText` -> `popoverContent` accordingly. Can drop this part if there is any concern?
_With the ongoing de-coupling of our codebases, I'm not sure we'll end up using this — but seems harmless enough?_

[OCMUI-1145] PreviewBadge: allow ReactNode content

---

apps/assisted-ui/Containerfile

We have an issue in Container file with nginx-1.20 image:
It's depecrated since March 2024. We change it to nginx-1.22 image.

NO-ISSUE: Fix Github actions to deploy Assisted UI lib

---

libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx
libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
libs/ui-lib/lib/common/components/hosts/types.ts
libs/ui-lib/lib/common/config/constants.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
libs/ui-lib/lib/ocm/components/hosts/HardwareStatus.tsx
libs/ui-lib/lib/ocm/components/hosts/HostsDiscoveryTable.tsx

- Links that appear after the users choose an Openshift version must display docs for that specific version.
Some examples:

MGMT-8534: Adjusting UI documentation links to OCP version selected

---

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/getProgressBarAlerts.tsx

Related to https://issues.redhat.com/browse/MGMT-15977
The UI will need to explicitly show to the user that the cluster installation is taking longer than expected, and give suggestions on how to proceed.
We also change the "Reset cluster"  button to be in red:

MGMT-15977: Add warning alert for soft installation timeouts

---

libs/ui-lib/lib/common/config/constants.ts

Related to https://issues.redhat.com/browse/MGMT-17851
In prod and staging -  Assisted installer documentation link is broken and leads to 404 page not found - https://access.redhat.com/documentation/en-us/assisted_installer_for_openshift_container_platform/2022/html/assisted_installer_for_openshift_container_platform/index
We need to replace with the correct link.

MGMT-17851: Assisted Installer link documentation is broken

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/HostInventoryExpandable.tsx
libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx

Related to [MGMT-17206](https://issues.redhat.com//browse/MGMT-17206)
When some of the hosts has a timeout in installation we see a warning icon next to "Host inventory" title:
And if user expands the "Host inventory" section can see info about the timeout in hosts:
And when host.progress.stagedtimeout is false then the icon changes another time:

MGMT-17206: Add information to hosts inventory table about host stage timeout in Installation page

---

libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
libs/ui-lib-tests/cypress/views/forms/CustomManifests/CustomManifestsForm.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx

Related to https://issues.redhat.com/browse/MGMT-17904
Custm manifests page - UI not validating filename field before sending it to BE, thus every request sent to BE contains an illegal filename (even in PATCH).
Implementation of unique method in Yup.array comes from here: https://github.com/jquense/yup/issues/345

MGMT-17904: Custom manifests page - UI not validating filename field before sending it to BE

---

libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
libs/ui-lib/lib/common/utils.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx

Related to https://issues.redhat.com/browse/MGMT-17804
Align regexp to validate manifests file name with the same regexp from assisted-service.
And also changes the code to clear alerts when form is submitting.

MGMT-17804: Change validation for patch manifests 

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx

Related to https://issues.redhat.com/browse/MGMT-17955
With latest changes, warning sign/icon appears next to the nodes although should be green. It seems it's a wrong condition in HostStatus file.
Before:
After:

MGMT-17955: Show the correct icon next to the nodes

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx

MGMT-17955: Show the correct icon next to the nodes  - 2.32

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx

Related to https://issues.redhat.com/browse/MGMT-18050
When timeout occured during installation  there is  a yellow triangle for warnning
In case total timeout 24 hours , hosts ((all) changed to error RED.
After changes:

MGMT-18050: UI warning icon not changed to error icon on 24 hours timeout in hosts table

---

libs/ui-lib/lib/common/components/hosts/HostStatus.tsx

MGMT-18050: UI warning icon not changed to error icon on 24 hours timeout in hosts table - 2.32

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmHostRequirements.tsx

Related to https://issues.redhat.com/browse/MGMT-16996
UI displays message parsing required information and show's API information which are the same.
After changes:

MGMT-16996: Show only LVMS requirements messages from BE

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/dummyData.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts

Related to https://issues.redhat.com/browse/MGMT-18211
UI sends incorrect NMstate to BE when user choose Static IP dualstack option.
Before changes we are sending only values from ipv4 and not for ipv6.

MGMT-18211: Static IP dualstack form - UI sends incorrect NMstate to BE

---

libs/ui-lib/lib/common/components/ui/EventsList.tsx

https://issues.redhat.com/browse/MGMT-17388
Replacing `\n` with a space is probably the best we can do here.

MGMT-17388: Log string literal format shown with "special" characters

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/StaticIpViewRadioGroup.tsx

Related with https://issues.redhat.com/browse/MGMT-18358
In "Static Network Configurations" page, in Yaml view if you add invalid YAML and some mac interface mapping and change to Form view the error alert don't dissapears
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/155792a0-db46-473c-ae41-bd67d71dfa41

MGMT-18358: Clear alerts when change from one view to another in Static network configurations step

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/YamlView/MacIpMapping.tsx

Related to https://issues.redhat.com/browse/MGMT-18357
If we create a cluster with Static IP configuration and try to map different Map interfaces the fields don't look aligned.
After changes:

MGMT-18357: Change alignment of MacIpMapping fields in Static Network Configuration

---

libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx

Related to https://issues.redhat.com/browse/MGMT-18567
Try to solve the error that happens in Assisted Installer clusters list:

MGMT-18567: Solving errors in clusters list

---

libs/ui-lib/lib/common/config/constants.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
libs/ui-lib/lib/ocm/services/ClustersService.ts

Related to https://issues.redhat.com/browse/MGMT-19202
JIRA tickets related :
- https://issues.redhat.com/browse/ECOPROJECT-2217
- https://issues.redhat.com/browse/ECOPROJECT-2301 
- https://issues.redhat.com/browse/ECOPROJECT-2260
When we come from Assisted Migration we  implement this:
- Add a tag for the service dashboard ('assisted_migration')
- Check the manifest checkbox automatically
- Add a parameter to know that we come from Assisted Migration (source=assisted_migraiton)
When the URL contains the parameter "source=assisted_migration" we fill some fields i n the cluster creation automatically:
https://github.com/user-attachments/assets/7b2f8d8e-3676-4468-83bf-fb186bff4a8b

MGMT-19202: Changes related with Assisted Migration

---

docs/I18N.md

Currently the internationalization document says that running `yarn i18n` updates the translation files, but that doesn't work: looks like it was changed but the documentation wasn't. The command seems to be this now:
```
yarn workspace @openshift-assisted/locales run process_new_strings
```
This patch updates the documentation accordingly.

NO-ISSUE: Update translation instructions

---

libs/ui-lib-tests/cypress/support/variables/networking.ts
libs/ui-lib-tests/cypress/views/networkingPage.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTableBase.tsx

Related to https://issues.redhat.com/browse/MGMT-19285
Change data-testid="nic-status" in networking page to data-testid="host-status":

MGMT-19285: Change data-testid='nic-status' in networking page to data-testid='host-status'

---

libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-19276
MTV Operator - SNO Cluster misleading tooltip information:

MGMT-19276: Add SNO tooltip information for MTV operator

---

libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-19330
When cluster is SNO, the MTV operator should be enabled because is supported:

MGMT-19330: MTV on SNO - operator enabled

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/FormViewHostsFields.tsx

Related to https://issues.redhat.com/browse/MGMT-19321
Deselect bond and Cancel still remove bond.
Cancelling the deselection should remain the bond selected and with all filled data
https://github.com/user-attachments/assets/d1f78abb-3230-414a-92b2-dda50b88bb4d

MGMT-19321: Deselect bond and cancel wouldn't have to remove the bond

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/formViewHostsValidationSchema.tsx

Related to https://issues.redhat.com/browse/MGMT-19322
UI needs to don't allow to proceed with only one mac address instead of 2 in bond fields

MGMT-19322: Bonds Mac Addresses should be required fields

---

libs/ui-lib/lib/common/components/ui/formik/LabelField.css

https://issues.redhat.com/browse/ACM-13211
Version for master of https://github.com/openshift-assisted/assisted-installer-ui/pull/2689
**Before:**
**After:**

ACM-13211: Low text visibility in label input field due to dark background color in ACM infrastructure environment creation page

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts

Related to https://issues.redhat.com/browse/MGMT-19389
Creating a static IP cluster with VLAN + Bong conf using UI form create an incorrect NMSTATE.

MGMT-18389: Solving problems with nmstate with VLAN+bonds

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

The OpenShift AI operator requires ODF, which in turn is incompatible with the LVM operator. But the UI isn't aware of that. As a result when the user selects the LVM operator and then tries to select the OpenShift AI operator the UI allows it, but the backend returns an error. To avoid that this patch changes the UI so that when LVM is selected the OpenShift AI option be automatically disabled.
Related: https://issues.redhat.com/browse/MGMT-19409

MGMT-19409: Disable OpenShift AI when LVM is enabled

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts

MGMT-19497: Not add VLAN configuration to bonds  - 2.36

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to https://issues.redhat.com/browse/MGMT-19298
MTV operator requires CNV. The better option is disable the CNV operator checkbox when MTV is selected:

MGMT-19298: Disable CNV operator when user selects MTV operator

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts

Related to https://issues.redhat.com/browse/MGMT-19611
Selecting bonds with no vlan and ipv4 UI creates illegal nmstate.
The nmstate:

MGMT-19611: If user use bonds+ipv4 withoud bound we need to generate the correct nmstate yaml

---

libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts

Related to https://issues.redhat.com/browse/MGMT-19587
The warning for MTU validation should only appear during the networking step and should not block users from proceeding with the installation.

MGMT-19587: Show MTU validation only in networking step

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx

Related to https://issues.redhat.com/browse/MGMT-19610
After changes:

MGMT-19160: Remove not highly available cluster text from Control Plane Nodes dropdown

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx

MGMT-19160: Remove not highly available cluster text from Control Plane Nodes dropdown - 2.37

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts

MGMT-19611: If user use bonds+ipv4 withoud bound we need to generate the correct nmstate yaml - 2.37

---

libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
libs/ui-lib/lib/ocm/config/constants.ts
libs/ui-lib/lib/ocm/services/ClustersService.ts

Related to https://issues.redhat.com/browse/MGMT-19726
When cluster is created from Assisted Migration we have to add predefined custom manifests (until the MTV integration be finished).

MGMT-19726: Add predefined custom manifests when cluster is created from Assisted Migration

---

.github/workflows/pull-request.yaml

Change actions/upload-artifact@v4 to actions/upload-artifact@v3
Related to the Deprecation of v3: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

NO-ISSUE: Change actions/upload-artifact@v4 to actions/upload-artifact@v3 in github actions

---

libs/ui-lib/lib/common/config/docs_links.ts

This patch changes the "learn more" link of the OpenShift AI operators so that it points to the "self managed" documentation, which is more appropriate for bare metal installations.

NO-ISSUE: Link to self managed OpenShift AI

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts

Related to:
- https://issues.redhat.com/browse/MGMT-19913
- https://issues.redhat.com/browse/MGMT-19916
I've added the feature support levels to the new bundles and operators.  If some bundle operators are not supported we have to disable all the bundle with a tooltip.
- https://issues.redhat.com/browse/MGMT-19915
The bundles frames have the same size.
- https://issues.redhat.com/browse/MGMT-19917
Now all the operators are sorted by name. We have the same order all the time.
- https://issues.redhat.com/browse/MGMT-19934
For ARM64, Nmstate is not available
- https://issues.redhat.com/browse/MGMT-19935
I've added the dev-preview flag to the new operators:

Improvement in the new Operators page behavior

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OscCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx

Related to https://issues.redhat.com/browse/MGMT-19938
MTV and Openshift AI get disabled  (they should be disabled) only after few seconds (around 10 seconds) after the page is loaded
https://github.com/user-attachments/assets/0a63ad3a-6181-47a4-b2e0-2a6a9ed513bb
After change:
https://github.com/user-attachments/assets/7b904fae-e011-4fb7-8534-4b7c08b41681

MGMT-19938: Get disabled reason for all the operators when the operators page is loaded

---

libs/locales/lib/en/translation.json
libs/ui-lib/lib/common/components/hosts/EditHostForm.tsx

https://issues.redhat.com/browse/MGMT-19589
Resolved by showing an alert:

MGMT-19589: Renaming is available in drop-down for a host in removing from cluster state, no warning/error that it's impossible in opened pop-up

---

libs/ui-lib/lib/common/config/docs_links.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx

With this PR we solved a list of bugs.
- https://issues.redhat.com/browse/MGMT-19914
- https://issues.redhat.com/browse/MGMT-20033
Selecting single operator that collides with bundle - one of them should be deselected/blocked
With this we avoid the problem to save in ui-settings endpoint the bundles if they are "illegal"
- https://issues.redhat.com/browse/MGMT-19942
LSO is disabled and selected after select and deslect a bundle
- https://issues.redhat.com/browse/MGMT-20035
Openshift AI bundle helper indicates that servicemesh is going to be installed, but it is not auto-selected
-https://issues.redhat.com/browse/MGMT-20040
Add "Learn more" links to the new operators

Operators redesign followup

---

libs/ui-lib/lib/common/config/docs_links.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx

backport of  #2805 
* MGMT-20035-openshift-ai-bundle-install-servicemesh
* MGMT-19442-lso-disabled-after-select-deselect-bundle
* MGMT-19914-selecting-operator-that-collides-with-bundle-one-of-them-should-be-deselected/blocked
* Adding Learn more links to the new operators

Operators redesign followup - 2.38

---

libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx
libs/ui-lib/lib/cim/components/Hypershift/types.ts

BP of: https://github.com/openshift-assisted/assisted-installer-ui/pull/2791

ACM-17500: Adding customkubeconfig to HostedClusterK8sResource type

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx

Related with https://issues.redhat.com/browse/MGMT-20056
When user selects CNV operator, the MTV operator is also selected because is needed.

MGMT-20056: When user selects CNV operator the MTV operator is also selected

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx

Related with https://issues.redhat.com/browse/MGMT-20053
In new operators page, trying to select and enable cnv, but getting an error about LSO - "
cannot use Local Storage Operator because it's not compatible with the arm64 architecture on version 4.18.1 of OpenShift"

MGMT-20053: If some operators are not supported, we don't select automatically

---

libs/ui-lib/lib/common/config/docs_links.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx

Related to https://issues.redhat.com/browse/MGMT-20054
Operators learn more link should point to the selected OCP version and not a hard-coded one

MGMT-20054: Change learn more links dinamically for new operators

---

libs/ui-lib/lib/common/config/docs_links.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx

MGMT-20054: Change learn more links dinamically for new operators - 2.28

---

libs/ui-lib/lib/common/config/docs_links.ts

Related with https://issues.redhat.com/browse/MGMT-20093
Some doc links were broken in old OCP versions. We force to use 4.14 version if the cluster's version is below 4.14.
https://docs.openshift.com/container-platform/4.14/virt/virtual_machines/advanced_vm_management/virt-configuring-virtual-gpus.html

MGMT-20093: Solving problems with docs links

---

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx

Related to https://issues.redhat.com/browse/MGMT-20055
Selecting sno cluster and hovering over the bundle boxes needs to show the correct text:

MGMT-20055: Bundle error helper text is unclear

---

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts
libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx

MGMT-20084: Same behavior on same operators in different selection - for MTV and CNV - 2.38

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/BondsSelect.tsx

https://issues.redhat.com/browse/MGMT-20086
changed Broadcast to Broadcase:

MGMT-20086: Change Broadcast to Broadcase in the Bond Type field

---

.github/workflows/release.yaml

Allow CIM releases from master branch too

Update release flow to not force push back to release branch/tag

---

.github/CODEOWNERS

since we are using OpenShift bot, the people responsible for reviews are driven by OWNERS file, not CODEOWNERS

Remove CODEOWNERS, replaced by OWNERS file

---

libs/locales/lib/en/translation.json
libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
libs/ui-lib/lib/cim/components/helpers/versions.ts
libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx

https://issues.redhat.com/browse/MGMT-20082
https://issues.redhat.com/browse/MGMT-20083
4 and 5 control planes nodes should not be allowed for OpenShift versions older than `4.18` and those that are `-multi`.

MGMT-20082: Deploying 4/5 nodes control plane is blocked

---

libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts

This reverts commit 23158a9fce5d51b6497dcce3766bfaa73b0ad4e9.
Im told we dont need this anymore, it was probably due to older backend or some other, already fixed, bug.

Revert "Set UMN=true in disconnected"

---

libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx
libs/ui-lib/lib/cim/components/Hypershift/types.ts

Changes required in the HC API to fix the resource name for the custom kubeconfig status field
#Fixes [ACM-17500](https://issues.redhat.com/browse/ACM-17500)

ACM-17500: Fix HostedCluster status CustomKubeconfig name

---

libs/ui-lib/lib/common/config/docs_links.ts

https://issues.redhat.com/browse/MGMT-20116
we still dont have this doc file for OCP version more than 4.17 in the same url.
so if the cluster uses version 4.17 or more this link will direct to the url of the doc for > 4.18.

MGMT-20116: fix bug: UMN documentation link returns 404

---

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx

Related to https://issues.redhat.com/browse/MGMT-20253
While "Migration Toolkit for Virtualization" operator required virtualization operator, virtualization operator doesn't require MTV.

MGMT-20253: Virtualization operator doesn't require MTV

---

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx

Related to https://issues.redhat.com/browse/MGMT-20291
Add  id/data-testid  to the expand button in operators page:

MGMT-20291: Add data-testid to Single Operators section in Operators page

---

libs/ui-lib/lib/common/config/docs_links.ts

Related to https://issues.redhat.com/browse/MGMT-21888
Replace old URL: `https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/networking/networking-operators#k8s-nmstate-about-the-k8s-nmstate-operator`
To the new one: `https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/networking_operators/k8s-nmstate-about-the-k8s-nmstate-operator`

MGMT-21888: Change NMstate operator docs link

---

apps/assisted-disconnected-ui/Containerfile.ocp

To onboard assisted disconnected UI onto OCP, add the `LABEL io.openshift.release.operator=true` so that the image is included in the release payload.

OCPBUGS-62680: Include assisted disconnected UI image in release payload
