.github/workflows/mergeToMaster.yaml, .github/workflows/pullRequest.yaml
So far without automated release of the NPM package (will follow)
=> GitHub workflows: mergeToMaster.yaml and pullRequest.yaml

README.md
=> README: extra line

src/components/clusterDetail/ClusterProgress.tsx, src/components/hosts/HostProgress.tsx, src/components/hosts/HostStatus.tsx
=> Fix Writing image progress step

src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/clusterConfiguration/DiscoveryProxyFields.tsx, src/components/clusterConfiguration/types.ts, src/components/ui/formik/CheckboxField.tsx, src/components/ui/formik/HelperText.tsx, src/components/ui/formik/InputField.tsx, src/components/ui/formik/TextAreaField.tsx, src/components/ui/formik/index.tsx, src/components/ui/formik/types.ts
=> Add checkbox to enable proxy configuration on discovery ISO dialog

src/components/clusterConfiguration/DiscoveryImageForm.tsx
`alpabetical` to `alphabetical`
=> Add an h to Download ISO modal text

src/api/domains.tsx, src/api/index.ts, src/api/swagger.yaml, src/api/types.ts, src/components/clusterConfiguration/BasicNetworkFields.tsx, src/components/clusterConfiguration/ClusterConfiguration.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/ClusterValidationSection.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/clusterValidations.ts, src/components/clusterConfiguration/utils.ts, src/components/ui/formik/SelectField.tsx, src/config/constants.ts, src/types/clusters.ts
=> Add Red Hat's DNS service capability

src/api/swagger.yaml, src/api/types.ts, src/api/versions.ts, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusters/ClusterPage.tsx, src/components/hosts/HostsTable.tsx, src/components/hosts/RoleCell.tsx, src/components/hosts/RoleDropdown.tsx, src/components/hosts/utils.ts, src/config/constants.ts
- Update API types
- Update versions API
- Starting cluster installation updates
- Adjust to role updates
=> Align to API updates

src/api/clusters.ts, src/components/clusterDetail/CancelInstallationModal.tsx, src/components/clusterDetail/ClusterDetail.tsx, src/components/clusterDetail/ClusterInstallationError.tsx, src/components/clusterDetail/ClusterProperties.tsx, src/components/clusterDetail/ResetClusterModal.tsx, src/components/clusters/ClusterPage.tsx, src/components/hosts/HostStatus.tsx, src/components/ui/table/utils.ts, src/config/constants.ts
~~Depends on https://github.com/filanov/bm-inventory/pull/254 and https://github.com/filanov/bm-inventory/pull/256~~
=> Add reset and cancel cluster installation actions

src/components/clusterConfiguration/NetworkConfiguration.tsx
=> Clear the base_dns_domain when unchecking the DNS service checkbox

src/api/swagger.yaml, src/api/types.ts, src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/clusterDetail/ClusterProgress.tsx, src/components/clusters/ClusterStatus.tsx, src/components/hosts/HostProgress.tsx, src/components/hosts/HostStatus.tsx, src/components/hosts/utils.ts, src/components/ui/table/utils.ts, src/config/constants.ts
- Adjust progress info utils to API changes
- Accommodate 'installing-pending-user-action' host status
- Calculate progress based on progress info provided from backend
=> Progress api updates

src/api/swagger.yaml, src/api/types.ts, src/components/clusters/ClusterPage.tsx, src/config/constants.ts
=> Handle 'finalizing' cluster status

src/api/swagger.yaml, src/api/types.ts, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterDetail/ClusterDetail.tsx, src/components/hosts/HostStatus.tsx, src/components/ui/EventsList.tsx, src/config/constants.ts
- Update API types
- include new 'preparing-for-installation' host status
=> Add severity labels to EventsList

src/api/swagger.yaml, src/api/types.ts, src/components/hosts/HostStatus.tsx, src/components/hosts/HostValidationGroups.css, src/components/hosts/HostValidationGroups.tsx, src/components/hosts/utils.ts, src/config/constants.ts, src/types/hosts.ts
Enhance host status popover to show validation groups and results
=> Handle pending-for-input host status

src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/clusterValidations.ts, src/components/clusterConfiguration/utils.ts, src/components/clusters/newClusterModal.tsx, src/components/ui/formik/HelperText.tsx, src/components/ui/formik/TextAreaField.tsx, src/components/ui/formik/types.ts, src/components/ui/formik/validationSchemas.ts, src/types/clusters.ts
- Add pullSecret field to newClusterModal
- Remove pullSecret field from ClusterConfigurationForm
=> Add pullSecret field to newClusterModal

package.json
Seems like nothing complains when I remove this dependency.
=> Remove tippy dependency

src/components/clusterDetail/ClusterDetail.tsx, src/components/clusterDetail/FailedHostsWarning.tsx
=> Explicitely warn about failed work nodes in the "installed" stated

src/api/clusters.ts, src/components/clusterDetail/KubeconfigDownload.tsx
download verified on standalone and OCM too.
=> Use interceptors when downloading cluster files

package.json, src/api/swagger.yaml, src/api/types.ts
API changes (for UI):
- `securityDefinitions` added
- `Host installation path` property added
- `vip_dhcp_allocation` cluster property added
- OCP 4.6 enabled
=> Fix update-api script to new assisted-service repo location

src/components/clusterConfiguration/DiscoveryImageForm.tsx
Waiting for backend changes to be merged.
=> Temporarily remove HTTP proxy

src/components/hosts/HostsCount.tsx, src/components/hosts/HostsTable.tsx
Render count of both `discovered` and `enabled` hosts.
=> Show host count

src/components/clusterConfiguration/DiscoveryImageForm.tsx
ModalBoxBody and ModalBoxFooter must be direct childen of Modal otherwise
ModalBoxBody overflow is broken
=> Discovery ISO modal scroll fix

src/components/hosts/HostStatus.css, src/components/hosts/HostStatus.tsx, src/components/hosts/HostsTable.css
=> Ensure same font size for buttons in compact table

src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/clusterConfiguration/ProxyFields.tsx, src/components/clusterConfiguration/discoveryImageModal.css, src/components/clusterConfiguration/discoveryImageModal.tsx, src/components/ui/formik/UploadField.tsx, src/components/ui/formik/index.tsx
=> Update Discovery ISO modal

src/components/clusterConfiguration/BasicNetworkFields.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx
Do not hide VIP fields when DHCP is on, just disable
Populate VIP fields once DHCP allocates leases
Reset DHCP value when Networking section is switched between Basic/Advanced
Attempt to fix a bunch of jiras
https://issues.redhat.com/browse/MGMT-1933
https://issues.redhat.com/browse/MGMT-1943
https://issues.redhat.com/browse/MGMT-1946
=> Update DHCP feature

src/api/axiosClient.ts, src/api/clusters.ts, src/components/AlertsContextProvider.tsx, src/components/clusterDetail/ClusterDetail.tsx, src/components/clusterDetail/ClusterInstallationError.tsx, src/components/hosts/HostsTable.tsx, src/components/hosts/utils.ts, src/config/constants.ts
=> Add Host Installation Logs download action

src/components/hosts/HostsTable.tsx
=> Fix Host Events title for hostname

src/components/clusters/ClusterStatus.tsx
=> Change Draft-cluster icon to file-alt

src/components/clusterConfiguration/BasicNetworkFields.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/ui/StaticTextField.tsx
- render VIPs outside of formik context using StaticTextField when
vipDhcpAllocation toggle is enabled
- track VIP DHCP allocation progress
- simplify network configuration logic
=> Move DHCP mode toggle into basic network setting

package.json, src/components/ui/PageSection.tsx
Related to https://github.com/openshift-metal3/facet/pull/298
=> Update peer dependencies to match facet

package.json, src/api/useApi.ts, src/api/utils.ts, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusters/NewClusterPage.tsx, src/components/fetching/EventListFetch.tsx, src/sentry.ts
=> Add Sentry exception logging

src/config/constants.ts
Tentative, till
- RC is out
- API provides versions to list
=> MGMT-2207 Tentatively use "OpenShift 4.6 Nightly" in Create cluster

src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx, src/components/hosts/HostsTable.tsx
=> MGMT-1469 Add "Hosts not showing up" to the empty state

src/components/clusters/ClusterToolbar.css, src/components/clusters/ClusterToolbar.tsx
=> OCPBUGSM-17300 Fix ClusterToolbar sizing in OCM

src/components/clusterConfiguration/ClusterValidationSection.tsx
Follow-up for: https://github.com/openshift/assisted-service/pull/351
=> Use bullets in list of validation errors

src/components/hosts/HostRowDetail.tsx, src/components/hosts/hardwareInfo.ts
The user is provided with information whether hyper-threading is available on a host.
=> MGMT-2089 Show hyper-threading if available

src/components/clusterConfiguration/BasicNetworkFields.tsx, src/components/hosts/EditHostForm.tsx, src/components/ui/StaticTextField.tsx, src/types/clusters.ts
=> MGMT-2258 Add error handling for failed DHCP VIP allocation

src/components/clusters/ClustersTable.tsx, src/components/hosts/HostsTable.tsx, src/components/hosts/hardwareInfo.ts, src/components/ui/table/utils.ts, src/selectors/clusters.tsx
~~Depends on https://github.com/mareklibra/facet-lib/pull/63~~
=> MGMT-1736 Add CreatedAt column to clusters list

src/api/swagger.yaml, src/api/types.ts, src/components/clusterDetail/ClusterDetail.tsx, src/components/clusterDetail/ClusterInstallationError.tsx, src/components/clusterDetail/ClusterProgress.tsx, src/components/clusters/ClusterPage.tsx, src/components/clusters/ClusterStatus.tsx, src/components/hosts/HostProgress.tsx, src/components/hosts/HostStatus.tsx, src/components/hosts/utils.ts, src/config/constants.ts
This comment needs to be resolved before merging https://github.com/openshift/assisted-service/pull/317#pullrequestreview-500961263
=> MGMT-2125 Add 'cancelled' status support

src/components/hosts/RoleDropdown.tsx, src/components/hosts/utils.ts, src/components/ui/SimpleDropdown.tsx, src/config/constants.ts, src/types/hosts.ts
=> MGMT-2373 Add description to role dropdown

src/components/ui/ClusterEventsList.tsx, src/components/ui/ClusterEventsToolbar.tsx
This filter matches all hosts registered to the cluster but subsequently deleted.
=> OCPBUGSM-18078 New option in cluster events filter: Deleted hosts

src/components/ui/DeveloperPreview.tsx
=> Fix Developer Preview banner alignment

src/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/components/ui/formik/validationSchemas.ts
=> OCPBUGSM-17318 Adjust advanced network validations to match backend requirements

src/components/clusters/ClustersFilterToolbar.tsx, src/components/clusters/ClustersTable.tsx, src/selectors/clusters.tsx
Adjust toolbar to match OCM toolbar layout
=> MGMT-2423 Add ability to search clusters by name, id or base domain

src/components/clusterDetail/ClusterProperties.tsx, src/components/hosts/HostRowDetail.tsx, src/components/hosts/HostsTable.tsx
Display Cluster UUID in cluster properties
Display Host UUID in host expanded detail
=> MGMT-2423 Display cluster/host UUIDs

src/components/Router.tsx, src/components/SingleCluster.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterDetail/ClusterDetail.tsx, src/components/clusters/ClusterBreadcrumbs.tsx, src/components/clusters/ClusterPage.tsx, src/components/clusters/NewClusterPage.tsx, src/components/ui/Toolbar/ToolbarButton.tsx, src/config/constants.ts, src/hacks.ts
=> MGMT-1538 Add support of the single-cluster flow

src/api/clusters.ts, src/components/clusterDetail/KubeconfigDownload.tsx, src/components/clusterDetail/utils.tsx, src/components/hosts/utils.ts
New cluster/host states were added to swagger.
Depends on:
=> MGMT-2330 Adapt logs download to new API

src/components/clusterConfiguration/BasicNetworkFields.tsx
=> Replace 'switch' with 'checkbox'

src/components/clusterConfiguration/ClusterSshKeyField.tsx
=> MGMT-1927: Replace switch with checkbox for using SSH pub key

src/components/clusterDetail/ClusterDetail.tsx
Follow-up for https://github.com/mareklibra/facet-lib/pull/270
Discussion:
- https://coreos.slack.com/archives/CUPJTHQ5P/p1603871320130100
- https://coreos.slack.com/archives/CUPJTHQ5P/p1603284140247300?thread_ts=1603278706.226100&cid=CUPJTHQ5P
=> Fix appearance of Abort installation link

src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/ui/formik/TextAreaField.tsx, src/components/ui/formik/UploadField.tsx, src/components/ui/formik/types.ts
To allow using it with other fields. Also fixes validation errors to show up correctly.
=> Make UploadField more generic

src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
Moved to OCM within later changes of https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/1748 .
=> Remove getBareMetalHostsClusterDetailTab()

src/components/clusterDetail/ClusterDetail.tsx
Abort installation action should be decided solely on cluster status.
=> OCPBUGSM-20518 Decide abort installation action on cluster status

src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/utils.ts, src/config/constants.ts
- Replace radio buttons with checkbox.
- Remember adv settings modifications when switching
back to 'Basic'.
=> MGMT-2379: Advanced network configuration - use checkbox

src/components/hosts/HostRowDetail.tsx
In addition, CPU details are reordered - more important things first
=> MGMT-792 Render virtual machine indication

src/components/clusterConfiguration/BasicNetworkFields.tsx, src/components/clusterConfiguration/utils.ts, src/components/ui/formik/validationSchemas.ts, src/config/constants.ts
Require user to enter API vip and Ingress vip
when DHCP allocation is not checked.
=> Bug 1882281: Add vip validation

src/components/clusterConfiguration/ProxyFields.tsx, src/components/ui/formik/utils.ts, src/components/ui/formik/validationSchemas.ts
Follow-up for https://bugzilla.redhat.com/show_bug.cgi?id=1877486
=> MGMT-2793 Enable '*' in NoProxy value

src/api/clusters.ts, src/components/hosts/HostsTable.tsx, src/components/hosts/ResetHostModal.tsx, src/components/hosts/utils.ts
So installation can be re-triggered.
=> OCPBUGSM-20923 A failed day2 host can be reseted

src/components/AddBareMetalHosts/BareMetalInventoryAddHost.tsx, src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/clusterConfiguration/discoveryImageModal.tsx, src/components/hosts/HostsTable.tsx
=> HTML ID change: button-download-discovery-iso button ID is prefixed

src/components/clusterDetail/ConsoleModal.tsx
=> MGMT-2316: Provide DNS entries instructions

src/components/ui/AlertsSection/AlertsSection.css
=> Fix AlertSection padding

src/components/clusterConfiguration/BaremetalInventory.tsx
=> Show FormatDiskWarning

src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
After latest changes around openshift_cluster_id
=> Fix Day 2 cluster retrieval

src/components/AddBareMetalHosts/BareMetalHostsClusterDetailTab.tsx
Latest changes around openshift_cluster_id query look-up were based on wrong
assumption that the look-up is implemented consistently
for both Day 1 and 2 in the backend.
This patch conforms the backend best.
=> Simplify look-up of the Day 2 cluster

package.json
=> move ip-address package to be dependency and not a peerDep

src/components/clusterConfiguration/utils.ts
=> Bug 1904485: fix machine_network_cidr string

package.json, src/components/ui/formik/validationSchemas.ts, yarn.lock
Needs proper review + ensure that there are no more regressions related to ipv6 work
=> OCPBUGSM-21354 Fix vip validation

src/api/addHostsClusters.ts, src/components/hosts/HostsTable.tsx, src/components/hosts/utils.ts
=> MGMT-3186: Day2 Install action per host

src/components/hosts/HostsTable.tsx, src/components/hosts/utils.ts
=> BZ 1905461 Add Delete and Reset actions to installing-pending-user-action

.github/workflows/release.yaml, README.md, package.json, scripts/sync-dist.sh, src/components/ui/DeveloperPreview.tsx, src/styles.css
Former upstream location:
https://github.com/marek-libra/facet-lib
New location:
https://github.com/openshift-assisted/assisted-ui-lib
=> Changes after repository ownership transfer

README.md, package.json, scripts/sync-dist.sh
Ownership and name of the "facet" project has been changed to openshift-assisted/assisted-ui.
=> Changes after facet to openshift-assisted/assisted-ui transfer

src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterWizard/ClusterWizardStep.tsx, src/components/clusters/ClusterPage.tsx, src/components/ui/Alerts.tsx
~~Depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/379~~
=> MGMT-3232 Convert ClusterConfiguration into a wizard step

src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusters/ClusterPage.tsx
~~Depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/380~~
=> Move ClusterConfigurationForm buttons

src/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx
- Align to docs team recommendations
- Update code sections to resemble latest state
=> MGMT-1576, MGMT-2228 Update the Discovery troubleshooting modal

src/components/clusters/ClustersListToolbar.tsx
=> Bug 1911409: Remove duplicate 'Draft' strings from filter

src/components/clusterDetail/ConsoleModal.tsx
=> MGMT-3304: DNS instructions - use asterisk for records with the same IP

src/components/clusters/ClustersListToolbar.tsx
The issue is most probably related to an older browser version.
We can tweak babel or do this.
=> BZ 1911409: Fix cluster list status filter values

src/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/config/constants.ts
=> Bug 1908924: Rename "Additional NTP..." to "Alternative NTP..."

src/components/ui/PrismCode.tsx
=> Use github prism theme as default

src/components/clusterConfiguration/ClusterSshKeyField.tsx
=> Bug 1908458: Fix typo - add space between 2 words

src/components/hosts/DiskLimitations.tsx, src/components/hosts/DiskRole.tsx, src/components/hosts/HostRowDetail.tsx, src/components/hosts/HostsTable.tsx, src/components/hosts/utils.ts, src/config/constants.ts
MGMT-3290 Add disk limitations and roles to host detail
MGMT-3338 Add disk role setting functionality to host detail
=> MGMT-3290, MGMT-3338 Add disk management to host detail

src/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/config/constants.ts
This reverts commit bedb331b5c0e5daab9e568fe79325c49b7e4c910.
=> Revert "Merge pull request #404 from jkilzi/master"

src/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/utils.ts, src/components/hosts/AdditionalNTPSourcesDialog.tsx, src/components/hosts/HostValidationGroups.tsx, src/components/ui/formik/types.ts, src/config/constants.ts
- Add validation action to NTP validation
- Remove 'Additional NTP Source' field
=> OCPBUGSM-22339, OCPBUGSM-22227 Set additional NTP sources as an action on the failing NTP validation

src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/NetworkConfigurationForm.tsx, src/components/clusterConfiguration/ReviewCluster.tsx, src/components/clusterConfiguration/ReviewStep.tsx, src/components/clusterWizard/ClusterWizard.tsx, src/components/clusterWizard/ClusterWizardStep.css, src/components/clusterWizard/ClusterWizardStep.tsx, src/components/clusterWizard/ClusterWizardToolbar.tsx, src/components/clusterWizard/wizardTransition.ts, src/components/clusters/ClusterToolbar.css, src/components/clusters/ClusterToolbar.tsx, src/components/hosts/hardwareInfo.ts
This PR is heavily WIP.
TODO:
For follow-ups: Capability levels and YAML manifests
Depends on:
=> MGMT-3236 Add ReviewStep to wizard

package.json
Reverts openshift-assisted/assisted-ui-lib#430
=> Revert "Generated - New 0.0.2-wizard version"

src/components/hosts/AdditionalNTPSourcesDialog.tsx, src/components/hosts/HostDialogsContext.tsx, src/components/hosts/HostPropertyValidationPopover.tsx, src/components/hosts/HostStatus.tsx, src/components/hosts/HostValidationGroups.tsx, src/components/hosts/HostsTable.tsx, src/components/hosts/NtpValidationStatus.tsx, src/features/dialogs/dialogsSlice.ts
Enable setting NTP source from NtpValidationStatus
- Move host dialogs into a state provided through context to enable triggering the dialog from different places
- Convert the dialogs state to useReducer and improve the API
=> OCPBUGSM-23658 Ntp action in host detail property

src/components/clusterDetail/ClusterProgress.tsx
=> Change popover title to 'Initialization'

src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/utils.ts, src/components/clusterDetail/ClusterProperties.tsx, src/components/clusters/NewClusterPage.tsx, src/components/ui/DetailList.tsx, src/components/ui/formik/SingleNodeCheckbox.tsx
**new cluster page:**
(The checkbox is unchecked by default)
------------------------------------------------------------------------------------------------
**cluster configuration page (No subnet, API-VIP and Ingress VIP selection):**
------------------------------------------------------------------------------------------------
**installing page ( no  API-VIP and Ingress VIP properties) :**
=> MGMT-2974: Allow the user to install Single Node OpenShift

src/components/Router.tsx, src/components/SingleCluster.tsx, src/components/clusters/NewClusterPage.tsx, src/components/ui/ClusterEventsToolbar.tsx, src/features/featureGate.tsx, src/features/index.ts, src/index.ts
First usage: enable/disable Single Node OpenShift
Related PRs:
- https://github.com/openshift-assisted/assisted-ui/pull/395
- OCM 2117
=> Introduce feature gates

src/components/hosts/AdditionalNTPSourcesDialog.tsx
Changed dialog title, enhanced NTP field description
=> Adjust NTP Dialog wording

src/components/clusterConfiguration/NetworkConfigurationForm.tsx, src/components/clusterConfiguration/ReviewStep.tsx, src/components/clusterWizard/BaremetalDiscovery.tsx, src/components/clusterWizard/ClusterDetails.tsx, src/components/clusterWizard/ClusterWizardStep.css, src/components/clusterWizard/ClusterWizardStep.tsx, src/components/clusterWizard/wizardTransition.ts, src/types/clusters.ts
=> MGMT-3824 Wizard transition functions

src/components/clusterWizard/ClusterDetails.tsx
=> MGMT-1612 Validate unique cluster in context of the base DNS 

src/components/clusterWizard/ClusterDetails.tsx, src/components/clusterWizard/ClusterWizard.tsx, src/components/clusterWizard/ClusterWizardContext.tsx, src/components/clusterWizard/wizardTransition.ts
=> Make wizard first step dynamic based on current flow

src/components/Router.tsx, src/components/SingleCluster.tsx, src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusters/NewClusterPage.tsx, src/features/featureGate.tsx
Defaults for features are provided, so they can be configured via Unleash without additional change in the assisted-ui-lib code.
=> Introduce ASSISTED_INSTALLER_OCS_FEATURE

src/components/clusterConfiguration/ReviewCluster.css, src/components/clusterConfiguration/ReviewCluster.tsx
=> Avoid bold in group-titles of the wizard summary table

package.json, src/components/AddBareMetalHosts/BareMetalInventoryAddHost.tsx, src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/hosts/HostRowDetail.tsx, src/components/hosts/hardwareInfo.ts
- Fixes the memory and disk size display units as per IEC standard
=> BZ-1917396 Display sizes as per IEC standard

src/components/clusterWizard/ClusterDetails.tsx, src/components/clusterWizard/ClusterWizardToolbar.tsx
- make 'cluster' prop optional in ClusterWizardToolbar
- Fix SNO checkbox in NewClusterPage and ClusterPage components
=> Use ClusterWizardToolbar in ClusterDetails

src/components/clusterConfiguration/ReviewCluster.tsx, src/components/clusterConfiguration/ReviewStep.tsx, src/components/clusterConfiguration/ReviewValidations.tsx, src/components/clusterWizard/ClusterWizard.tsx, src/components/clusterWizard/ClusterWizardStep.css, src/components/clusterWizard/ClusterWizardStep.tsx, src/components/clusterWizard/wizardTransition.ts, src/config/constants.ts, src/types/clusters.ts
=> Wizard: Add validation sections to the Review step

src/components/clusterConfiguration/ClusterValidationSection.tsx, src/components/clusterConfiguration/NetworkConfigurationForm.tsx, src/components/clusterConfiguration/ReviewStep.tsx, src/components/clusterWizard/BaremetalDiscovery.tsx, src/components/clusterWizard/ClusterDetails.tsx, src/components/clusterWizard/ClusterWizardToolbar.tsx, src/components/clusterWizard/wizardTransition.ts
=> MGMT-4200 Fix position of wizard validation section

src/components/AddBareMetalHosts/BareMetalInventoryAddHost.tsx, src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/hosts/HostRowDetail.tsx, src/components/hosts/hardwareInfo.ts, src/components/hosts/utils.ts
- Disk sizes are displayed in GB (b * 1000) and memory in GiB (b * 1024)
=> BZ-1917396 Fixes disk and memory display units

src/components/clusters/ClusterBreadcrumbs.tsx, src/styles.css
Per UXD request, the badge is shifted closer to the text to be consistent with OCM.
=> MGMT-4317 Add margin to the Technology Preview badge

src/components/clusterConfiguration/ReviewCluster.tsx
Memory and Storage displayed unit sizes both in GB
=> refactor: Fixes size units in cluster review step

src/api/clusters.ts, src/api/swagger.yaml, src/api/types.ts, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/ClusterDefaultConfigurationContext.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/types.ts, src/components/clusterConfiguration/utils.ts, src/components/clusters/ClusterPage.tsx, src/components/clusters/NewClusterPage.tsx
Retrieves the default configuration dynamically from `/cluster/default-config` endpoint
=> MGMT-3891 Default config UI sync

src/components/clusterConfiguration/BaremetalInventory.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/utils.ts, src/components/clusterDetail/ClusterProperties.tsx, src/components/clusters/utils.ts, src/components/hosts/HostsTable.tsx, src/components/hosts/RoleCell.tsx, src/components/hosts/utils.ts
- Disables host role dropdown in SNO setup
=> BZ-1931572 Setting role for a SNO node shows an error

src/components/clusterConfiguration/NetworkConfigurationForm.tsx, src/components/clusterWizard/BaremetalDiscovery.tsx, src/components/ui/formik/FormikAutoSave.tsx
- Introduces FormikAutoSave component which tries to submit the form
when values change. The submission is debounced to avoid frequent
subsequent updates e.g. on user typing
- FormikAutoSave is used on baremetal-discovery and networking wizard
steps
- Adjusted Next button behavior on autosave steps
=> Wizard formik autosave

src/api/swagger.yaml, src/api/types.ts, src/components/clusterDetail/ResetClusterModal.tsx, src/components/clusters/utils.test.ts, src/components/clusters/utils.ts
=> MGMT-3818 Log Collection State UI side

src/api/swagger.yaml, src/api/types.ts, src/components/clusterConfiguration/BasicNetworkFields.tsx, src/components/clusterConfiguration/ClusterConfigurationForm.tsx, src/components/clusterConfiguration/ClusterValidationSection.tsx, src/components/clusterConfiguration/utils.ts, src/components/clusters/utils.ts, src/components/hosts/HostStatus.tsx, src/config/constants.ts, src/types/clusters.ts, src/types/hosts.ts
- Update api/types.ts according to latest swagger
- MGMT-3907 Support new preparing-successful host status
- MGMT-3663 Support new host validations
- Adjust cluster and hosts validation groups
- MGMT-4208 Bug 1938578 Update OCS checkbox to use latest operators API
=> API Updates

src/components/clusterDetail/ClusterDetail.tsx, src/components/clusterDetail/ClusterProgress.tsx, src/components/clusterDetail/FailedOperatorsWarning.tsx, src/components/clusterDetail/OperatorsProgressItem.css, src/components/clusterDetail/OperatorsProgressItem.test.ts, src/components/clusterDetail/OperatorsProgressItem.tsx, src/components/clusterWizard/BaremetalDiscovery.tsx, src/components/clusters/utils.ts, src/config/constants.ts
=> MGMT-4654 Add OLM Operators tracking to cluster progress

src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterConfiguration/NetworkConfigurationForm.tsx, src/components/clusterConfiguration/utils.ts, src/components/clusterWizard/networkingSteps/AvailableSubnetsControl.tsx, src/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx, src/components/clusterWizard/networkingSteps/UserManagedNetworkingTextContent.tsx, src/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx, src/components/clusterWizard/networkingSteps/index.ts, src/components/ui/ExternalLink.tsx, src/components/ui/RenderIf.tsx, src/components/ui/formik/RadioField.tsx, src/components/ui/formik/validationSchemas.ts, src/config/constants.ts, src/types/clusters.ts
This PR allows the user to select between user-managed or cluster-managed networking
=> MGMT-2754 Enable cluster/user-managed networking

src/components/clusterConfiguration/InformationAndAlerts.tsx, src/components/hosts/OCSDisksManualFormattingHint.tsx
=> BZ 1946579 Add OCS manual disk formatting hint

src/api/hostRequirements.ts, src/components/AddHosts/AddHosts.tsx, src/components/AddHosts/InventoryAddHost.tsx, src/components/clusterConfiguration/ClusterPreflightRequirementsContext.tsx, src/components/clusterConfiguration/HostInventory.tsx, src/components/clusterWizard/HostDiscovery.tsx, src/components/fetching/HostRequirements.tsx
=> MGMT-4671: Use preflight cluster requirements

src/components/clusterDetail/ConsoleModal.tsx
=> BZ-1939251 appends the base dns part to the hostname

src/api/utils.ts, src/components/clusterDetail/utils.test.tsx, src/components/clusterDetail/utils.tsx
=> fix: BZ-1954967 Cluster overview card in OCM shows stacktrace when cluster is installing

src/components/clusterWizard/HostDiscovery.tsx
=> BZ 1954106 Workaround Formik's dirty mulfunction

src/components/clusterConfiguration/SNOControlGroup.tsx, src/components/clusterConfiguration/SNODisclaimer.tsx, src/components/clusterWizard/ClusterDetails.tsx, src/components/ui/formik/CheckboxField.tsx, src/types/clusters.ts
=> Add SNO disclaimet ro ClusterDetails

src/components/clusterDetail/ConsoleModal.tsx, src/components/hosts/utils.ts
=> MGMT-3210 Fix console troubleshooting modal for SNO

src/components/clusterConfiguration/HostInventory.tsx
=> MGMT-3454 Display write speed requirement in the UI

package.json, yarn.lock
Whenever it makes sense, use regular dependencies instead.
=> Review peerDependencies

src/components/clusterWizard/ClusterDetails.tsx
=> Updates the disclaimer validation text

src/components/hosts/NetworkingHostsTable.tsx
=> BZ-1957199 Fixes IPv6 column title

src/components/AddHosts/InventoryAddHost.tsx, src/components/clusterConfiguration/DiscoveryInstructions.tsx, src/components/clusterConfiguration/HostInventory.tsx
=> BZ-1954074 Fix discovery instruction to mentions machine in SNO

src/components/clusterDetail/ClusterProgress.tsx
=> BZ-1928703 Use singular for Control Plane masters count in SNO

src/components/clusterDetail/ConsoleModal.tsx
Is up to the user to set the FQDN for the host name
=> BZ-1939251 Fixes duplicated dns part

src/components/clusterDetail/ConsoleModal.tsx, src/components/hosts/utils.ts
Ref: https://issues.redhat.com/browse/MGMT-6014
=> MGMT-6014 Removes FE logic for resolving vip values in SNO

src/components/clusterDetail/ConsoleModal.tsx, src/components/hosts/utils.ts
Reverts openshift-assisted/assisted-ui-lib#609
Backend patches are delayed.
We will merge #609 later.
=> Revert "MGMT-6014 Removes FE logic for resolving vip values in SNO"

src/components/clusterDetail/ConsoleModal.tsx, src/components/hosts/utils.ts
Reverts openshift-assisted/assisted-ui-lib#617 since https://github.com/openshift/assisted-service/pull/1811 is merged now
https://coreos.slack.com/archives/CUPJTHQ5P/p1622641643234600?thread_ts=1622639424.222100&cid=CUPJTHQ5P
=> Revert "Revert "MGMT-6014 Removes FE logic for resolving vip values in SNO""

src/components/clusters/ClusterPage.tsx
=> BZ-1928653 Fixes window not reloading when pressing Try Again CTA

src/components/clusterDetail/ResetClusterModal.tsx
Please read the discussion inside [BZ-1946653](https://bugzilla.redhat.com/show_bug.cgi?id=1946653) for more details.
=> BZ-1946653 Display percentage instead of ratio of logs available for downloading

package.json, src/components/InfraEnv/EnvironmentDetails.tsx, src/components/InfraEnv/Wizard/InfraWizard.tsx, src/components/InfraEnv/Wizard/index.ts, src/components/InfraEnv/Wizard/steps/ConfigureNetworkModal.tsx, src/components/InfraEnv/Wizard/steps/EnvironmentStep.tsx, src/components/InfraEnv/Wizard/steps/ReviewStep.tsx, src/components/InfraEnv/Wizard/types.ts, src/components/InfraEnv/Wizard/utils.ts, src/components/InfraEnv/index.ts, src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/clusterConfiguration/UploadSSH.tsx, src/components/index.ts, src/components/ui/formik/InputField.tsx, src/components/ui/formik/LabelField.css, src/components/ui/formik/LabelField.tsx, src/components/ui/formik/types.ts, src/index-cim.ts, yarn.lock
Reverts openshift-assisted/assisted-ui-lib#627
=> Revert "Revert "Infra wizard""

src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx, src/components/ui/PopoverIcon.tsx
=> MGMT-3713 Allows the user to generate a minimal ISO

.github/workflows/mergeToMainBranches.yaml, .github/workflows/pullRequest.yaml, package.json, src/config/constants.ts, tsconfig.json, yarn.lock
This reverts commit c51c202515a9d9b3fd53424bbae921f97afbebb1.
=> Revert "Do not bundle, transpile only"

src/components/clusterWizard/ClusterDetails.tsx
Filter-out actual cluster name.
=> Fix used-cluster name validation

src/components/AddHosts/HostsClusterDetailTab.tsx, src/components/clusters/ClusterPage.tsx
Consistently cast the status code to number instead of string
=> fix: fixes cannot read property code of undefined

src/components/clusterConfiguration/ClusterSshKeyFields.tsx, src/components/clusterConfiguration/DiscoveryImageForm.tsx, src/components/clusterConfiguration/UploadSSH.tsx
**Resolves [BZ-1970772](https://bugzilla.redhat.com/show_bug.cgi?id=1970772)**
https://user-images.githubusercontent.com/77008341/122940300-0567e600-d37d-11eb-9e63-283e3c042919.mp4
=> MGMT-4476 Makes the ssh key field optional

src/config/constants.ts
=> BZ-1967064 Fixes incorrect validation message for SNO's disclaimer

src/api/swagger.yaml, src/api/types.ts, src/components/clusterDetail/ClusterDetail.tsx
=> MGMT-6625 adds a warning message to indicate that the cluster will be deleted after X days

src/components/AddHosts/utils.ts
=> BZ-1963928 Dont show "add host" tab for SNO clusters

src/components/hosts/HostStatus.tsx, src/components/hosts/HostsTable.css, src/components/ui/RenderIf.tsx
[Discussion](https://bugzilla.redhat.com/show_bug.cgi?id=1931017)
[Mocks](https://issues.redhat.com/browse/MGMT-4786)
https://user-images.githubusercontent.com/77008341/122877867-c1a2bb80-d33f-11eb-889d-99303d95b527.mp4
=> BZ-1931017 NTP sync should be resolved at Networking step

src/components/clusterDetail/ClusterPropertiesList.tsx, src/components/clusterDetail/index.ts
As a subsequent step I'll refactor the ClusterProperties component to use ClusterPropertiesList internally
=> Add ClusterPropertiesList component

src/api/swagger.yaml, src/api/types.ts, src/config/constants.ts
- Updates swagger.yaml (in sync with assisted-service)
- Adds labels to the following new validations:
-  'sufficient-network-latency-requirement-for-role'
- 'sufficient-packet-loss-requirement-for-role'
- 'has-default-route'
=> MGMT-7108 Adds labels to the new validations

src/components/clusterDetail/ClusterProgress.tsx
=> Refactor cluster status utilities to not depend on whole cluster

src/components/clusterConfiguration/OpenShiftVersionSelect.tsx, src/config/constants.ts
[MGMT-7193](https://issues.redhat.com/browse/MGMT-7193)
https://user-images.githubusercontent.com/77008341/124916755-b0260880-dffb-11eb-8f56-b356f7f94252.mp4
=> MGMT-7193 Adds a warning about v4.7 reaching end-of-support

src/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx
https://user-images.githubusercontent.com/77008341/124628727-703f1400-de89-11eb-8f18-6e79ad5cc6a4.mp4
=> MGMT-6967 Update the radio buttons labels in Generate Discovery ISO dialog

src/components/hosts/OCSDisksManualFormattingHint.tsx
[MGMT-5262](https://issues.redhat.com/browse/MGMT-5262)
https://user-images.githubusercontent.com/77008341/124761466-8062fc00-df3a-11eb-87b2-a7f100c2fefb.mp4
=> MGMT-5262 Display message in the UI that disks need to be cleaned up for OCS installation

src/components/ui/PreviewBadge.tsx
=> MGMT-7126 Updates the tech preview badge in OCM

src/components/clusterConfiguration/OpenShiftVersionSelect.tsx, src/config/constants.ts
Reverts openshift-assisted/assisted-ui-lib#675
=> Revert "MGMT-7193 Adds a warning about v4.7 reaching end-of-support"

src/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/components/clusterConfiguration/DownloadIso.tsx, src/components/clusterConfiguration/FormatDiskWarning.tsx, src/components/clusterConfiguration/HostInventory.tsx, src/components/clusterConfiguration/InformationAndAlerts.tsx, src/components/clusterConfiguration/NetworkConfiguration.tsx, src/components/clusterWizard/ClusterDetailsForm.tsx, src/components/clusterWizard/ClusterDetailsFormFields.tsx, src/components/clusterWizard/ClusterWizardStepHeader.tsx, src/components/clusterWizard/constants.ts, src/components/hosts/ClusterHostsTable.tsx, src/components/hosts/HostRowDetail.tsx, src/components/hosts/HostsTable.tsx, src/components/hosts/VMRebootConfigurationInfo.tsx, src/components/ui/formik/SingleNodeCheckbox.tsx
[MGMT-5994](https://issues.redhat.com/browse/MGMT-5994)
=> MGMT-5994 Going over existing wizard phase 1 microcopy

src/components/clusterConfiguration/HostInventory.tsx, src/components/hosts/HostRequirementsContent.tsx
[MGMT-5284](https://issues.redhat.com/browse/MGMT-5284)
Non-SNO
SNO
=> MGMT-5284 Persistent storage for CNV

src/cim/types/fromOCP/k8sTypes.ts, src/cim/types/fromOCP/kebab.ts, src/cim/types/k8s/agent-cluster-install.ts, src/cim/types/k8s/agent.ts, src/cim/types/k8s/cluster-deployment.ts, src/cim/types/k8s/infra-env.ts, src/cim/types/metal3.ts
instead of @openshift-console/dynamic-plugin-sdk
=> Fix imports from console-sdk-ai-lib

src/components/ui/formik/validationSchemas.ts
https://bugzilla.redhat.com/show_bug.cgi?id=1979942
=> BZ-1979942: The assisted UI should not forbid creating 2 cluster with the same name and domain name

src/components/clusterDetail/ClusterDetailStatusVarieties.tsx
Motivated by https://issues.redhat.com/browse/AITRIAGE-930
=> Reduce frequency of credentials fetching

src/common/components/hosts/HostsTable.tsx
[MGMT-7373](https://issues.redhat.com/browse/MGMT-7373)
=> MGMT-7373: Fixes do not call hooks in built-in hooks

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/config/constants.ts
https://issues.redhat.com/browse/MGMT-6423
=> MGMT-6423 Handle new DNS validation in the UI

src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, src/common/config/constants.ts
[MGMT-7193](https://issues.redhat.com/browse/MGMT-7193)
https://user-images.githubusercontent.com/77008341/127283252-03849dfd-167a-45ec-875e-01c96e2c4240.mp4
=> MGMT-7193 Add a warning message that OCP version 4.7 version will be removed at the end of July

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/clusterConfiguration/networkConfigurationValidation.ts, src/common/components/clusterConfiguration/utils.ts, src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx, src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx, src/common/components/ui/formik/RadioField.tsx, src/common/components/ui/formik/validationSchemas.ts, src/common/config/constants.ts, src/common/types/clusters.ts, src/custom.d.ts, src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx
[MGMT-6769](https://issues.redhat.com/browse/MGMT-6769)
https://user-images.githubusercontent.com/77008341/127576039-3ffc45b5-a6ae-4a39-bd13-ba76c87d7186.mp4
=> MGMT-6769: Allows the users to select the network type (SDN/OVN)

src/cim/components/ClusterDeployment/ClusterDeploymentHostsTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx, src/cim/components/ClusterDeployment/NetworkingStatus.tsx, src/cim/components/ClusterDeployment/types.ts, src/cim/components/index.ts, src/cim/components/modals/EditAgentModal.tsx, src/cim/components/modals/index.ts, src/cim/types/k8s/index.ts, src/common/components/hosts/index.ts, src/common/components/hosts/networking-hosts-table.tsx, src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx, src/ocm/components/hosts/NetworkingStatus.tsx
depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/700
=> Change table callbacks to work with k8s objects

src/common/components/constants.ts, src/common/components/hosts/hardwareInfo.ts
Signed-off-by: jkilzi <jkilzi@redhat.com>
=> BZ-1971759: Disk size calculation includes the read-only bytes from DVD-ROM storage

src/common/components/fetching/EventListFetch.tsx, src/common/components/ui/ClusterEventsList.tsx, src/common/components/ui/ClusterEventsToolbar.css, src/common/components/ui/ClusterEventsToolbar.tsx, src/common/components/ui/EventsList.css, src/common/components/ui/EventsList.tsx, src/common/components/ui/EventsModal.css, src/common/components/ui/eventsModal.tsx, src/common/types/events.ts
https://issues.redhat.com/browse/MGMT-7381
https://user-images.githubusercontent.com/87187179/128347644-13831dfa-78f5-4c96-887c-4acc43c2e259.mp4
=> MGMT-7381: Make cluster events toolbar fixed

src/common/components/clusterConfiguration/utils.ts
[BZ-1990011](https://bugzilla.redhat.com/show_bug.cgi?id=1990011)
=> BZ-1990011: Adv. Networking checkbox is enabled despite defaults aren't changed

src/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, src/cim/components/helpers/status.ts, src/common/components/clusterWizard/clusterDetailsValidation.ts
Add isDraft utility function for detecting cluster status
=> Add default base domain prop for integration with ACM credentails.

src/common/components/hosts/HostValidationGroups.tsx
`host-discovery` step:
`networking` step:
=> MGMT-7477: Fixes display 'change hostname' helper text conditionally

src/common/components/hosts/hardwareInfo.ts, src/ocm/components/clusterDetail/utils.test.tsx, src/ocm/components/clusterDetail/utils.tsx
https://issues.redhat.com/browse/MGMT-7391
=> MGMT-7391 - UI and back-end are looking at different memory stats

src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx
[BZ-1999297](https://bugzilla.redhat.com/show_bug.cgi?id=1999297)
refactor: Updates NetworkConfigurationForm.tsx
=> BZ-1999297: Fixes vip-dhcp-allocation mode broken cannot set networking for cluster

src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, src/common/components/clusterWizard/clusterDetailsValidation.ts, src/common/components/ui/formik/PullSecretField.tsx, src/common/config/constants.ts
https://issues.redhat.com/browse/MGMT-7707
=> MGMT-7707: Capilization errors in 'Cluster details' step

src/common/styles.css, src/ocm/components/clusters/ClusterBreadcrumbs.tsx, src/ocm/components/clusters/ClusterPage.tsx, src/ocm/components/ui/PreviewBadge.tsx
https://issues.redhat.com/browse/MGMT-7711
before:
after:
=> MGMT-7711: Show 'Technology preview' badge near the title of Assisted installer wizard title

src/ocm/components/clusterConfiguration/discoveryImageModal.tsx, src/ocm/components/hosts/ClusterHostsTable.tsx
https://issues.redhat.com/browse/MGMT-7702
before:
after:
=> MGMT-7702 - Tweaks in the "Host discovery" step design

src/cim/components/ClusterDeployment/ClusterDeploymentCredentials.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentProgress.tsx, src/cim/components/ClusterDeployment/helpers.test.ts, src/cim/components/ClusterDeployment/helpers.ts, src/cim/components/ClusterDeployment/index.ts, src/cim/components/ClusterDeployment/types.ts, src/cim/components/InfraEnv/utils.ts, src/cim/components/helpers/clusterDeployment.ts, src/cim/types/fromOCP/k8sTypes.ts
Addresses feedback from https://github.com/rawagner/dynamic-cim/pull/35
=> Add ClusterDeploymentDetails and ClusterDeploymentCredentials components

src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/helpers/toAssisted.ts, src/cim/index.ts, src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, src/common/components/ui/formik/SingleNodeCheckbox.tsx, src/common/components/ui/utils.ts, src/common/features/featureGate.tsx
Depends on:
Required by:
TODO:
=> MGMT-7352 Add Single Node OpenShift (SNO) support

src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionBasic.tsx, src/cim/components/common/constants.ts, src/cim/components/helpers/clusterDeployment.ts
Counterpart: https://github.com/rawagner/console-1/pull/4
=> Remove RESERVED_AGENT_LABEL_KEY in favor of clusterDeploymentName

src/ocm/components/clusterConfiguration/ReviewCluster.tsx
https://issues.redhat.com/browse/MGMT-7701
=> MGMT-7701 - Guide users to set vsphere configuration after the installation (Review step note)

src/cim/components/Agent/AgentStatus.tsx
=> Update approve host modal content

src/cim/components/InfraEnv/InfraEnvAgentTable.tsx, src/common/components/hosts/HostsTable.tsx, src/ocm/components/clusterConfiguration/NetworkConfigurationTable.tsx, src/ocm/components/hosts/ClusterHostsTable.tsx, src/ocm/components/hosts/HostsDiscoveryTable.tsx, src/ocm/components/hosts/use-hosts-table.tsx
=> Add hosts not showing up troubleshooting modal for infra env table

src/common/components/clusterConfiguration/utils.ts
https://bugzilla.redhat.com/show_bug.cgi?id=2008043
=> BZ-2008043 - The UI is stuck in the networking page with: "The following fields are not valid: API Virtual IP, Ingress Virtual IP." 

src/cim/components/Agent/BMCForm.tsx, src/cim/components/modals/EditBMHModal.tsx, src/common/components/ui/formik/InputField.tsx, src/common/components/ui/formik/validationSchemas.ts
- nm state is not required if infra env is using DHCP
- improve BMC address validation
ACM bug: https://github.com/open-cluster-management/backlog/issues/16650
=> Fix adding BM agents

src/cim/components/helpers/versions.ts, src/common/components/ui/utils.ts, src/common/types/versions.ts
Remove support warning for any update channel
Fixes https://github.com/open-cluster-management/backlog/issues/16680
=> Fix detection of SNO supported versions

.idea/jsLibraryMappings.xml, src/ocm/api/clusters.ts, src/ocm/api/versions.ts
[MGMT-7722](https://issues.redhat.com/browse/MGMT-7722)
Migrated:
- GET /v2/clusters
- DELETE /v2/clusters/{cluster_id}
- GET /v2/component-versions
=> MGMT-7722: Clusters list page with v2 APIs (WIP)

src/cim/components/Agent/BMCForm.tsx, src/common/components/ui/formik/validationSchemas.ts
Boot MAC address is not required
=> Remove validation for BMC address

src/cim/components/InfraEnv/InfraEnvFormPage.tsx
Fixes https://github.com/open-cluster-management/backlog/issues/16870
=> Add pull secret validation to InfraEnv form

src/cim/components/Agent/NoAgentsAlert.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelection.tsx
=> Add warning about no available agents in Hosts selection step

src/ocm/components/clusterConfiguration/ClusterValidationSection.tsx
Just a little something I saw.
=> Fix typo in background checks alert

src/cim/components/helpers/versions.ts, src/common/api/swagger.yaml, src/common/api/types.ts, src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
https://issues.redhat.com/browse/MGMT-7919
=> MGMT-7919 - Filter out OCP versions with maintenance support level in the create cluster screen

src/common/api/swagger.yaml, src/common/api/types.ts, src/ocm/components/AddHosts/AddHosts.tsx, src/ocm/components/AddHosts/HostsClusterDetailTab.tsx, src/ocm/components/hosts/use-hosts-table.tsx, src/ocm/services/HostsService.ts, src/ocm/services/apis/ClustersAPI.ts, src/ocm/services/apis/HostsAPI.ts
https://issues.redhat.com/browse/MGMT-7718
=> V2 day2 [WIP]

src/cim/types/k8s/agent-cluster-install.ts
Required by https://github.com/openshift-assisted/dynamic-cim/pull/61
=> Add holdInstallation property to AgentClusterInstalK8sResource type

src/common/components/hosts/utils.ts
chaned from 'Control Plane, Worker' to 'Control plane node, Worker'
=> small fix, fixed label of control plane node when schedulable masters is on

src/ocm/components/clusterConfiguration/HostInventory.tsx
fixed bug which caused switch to jump to previous value after user changed it when cluster polling response came after patch response.
=> fixed schedulable masters field reaction to cluster polling

src/cim/components/InfraEnv/AgentAlerts.tsx, src/cim/components/InfraEnv/EnvironmentErrors.tsx, src/cim/components/InfraEnv/index.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/955 for ACM2.4
=> Fix link to ACM docs.

src/cim/components/helpers/agents.ts, src/cim/components/helpers/status.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/958
=> Do not show insufficient hosts in host selection step

src/ocm/components/clusters/ClusterStatus.tsx
Ffixes an issue related to `esbuild` and `jest` inside `uhc-portal`
=> Do not use IconSize enum

yarn.lock
=> chore: leftover after bumping dpdm

src/ocm/hooks/useClusterSupportedPlatforms.ts
Fixed error handling of failure in call to supported-platforms API to no run for every rerender
=> MGMT-8437: error handling for supported-platforms API causes react error

src/common/components/hosts/tableUtils.tsx
https://issues.redhat.com/browse/MGMT-8404
=> MGMT-8404 - Misleading Disk column name on Host Discovery page

src/cim/components/Agent/AgentStatus.tsx, src/common/components/hosts/HostStatus.tsx
=> Add/update icons for Discovered, Binding/Bound states

src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/config/constants.ts
https://issues.redhat.com/browse/MGMT-5286
=> MGMT-5286 - Provide a link to documentation about how to setup firewall in order to use proxy

src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx, src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/clusterConfiguration/networkConfigurationValidation.ts, src/common/components/ui/formik/validationSchemas.ts
- add hostSubnet validation to prevent submitting form without it being correctly set
- automatically populate host subnet dropdown with first subnet whenever available
=> Add hostSubnet validation to networking step

src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/ocm/components/clusterConfiguration/ReviewCluster.tsx, src/ocm/components/featureSupportLevels/utils.tsx
Fixed the condition for showing the title to the same logic of generating the LimitedSupportLevel component content
=> MGMT-8509: No reason specified for "Your cluster will be subject to support limitations"

src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/featureSupportLevels/FeatureSupportLevelBadge.tsx, src/common/components/ui/PreviewBadge.tsx, src/ocm/components/clusterConfiguration/ReviewCluster.tsx, src/ocm/components/clusters/ClusterPage.tsx, src/ocm/components/clusters/NewClusterPage.tsx
added test ids to:
support level badges
review and create support level section
cluster managed networking with vms alert
=> MGMT-8502: add test IDs to the support level badges

src/cim/components/InfraEnv/InfraEnvFormPage.tsx, src/cim/components/modals/AddHostModal.tsx, src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, src/common/config/constants.ts
=> Add static ip option for non-bm platforms

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx, src/ocm/services/DiscoveryImageFormService.ts
https://issues.redhat.com/browse/MGMT-8517
=> MGMT-8517 - Display current ISO image url

src/ocm/components/clusters/ClustersListToolbar.tsx
https://issues.redhat.com/browse/MGMT-8543
Note: variable name changed to better represent its purpose / expected value.
Before:
After:
=> MGMT-8543 - Filter in cluster list include "Adding hosts" though these are not showing anyway

src/ocm/hooks/useOpenshiftVersions.tsx
https://issues.redhat.com/browse/MGMT-8500
Before:
After:
=> MGMT-8500 - OCP versions are sorted old -> new rather than the other way around

src/cim/components/Agent/AgentsSelectionTable.tsx, src/cim/components/Agent/tableUtils.tsx, src/cim/components/ClusterDeployment/AdditionalNTPSourcesDialogToggle.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx, src/cim/components/helpers/toAssisted.ts, src/cim/components/status/HardwareStatus.tsx, src/cim/components/status/NetworkingStatus.tsx, src/common/components/clusterWizard/validationsInfoUtils.ts, src/common/components/hosts/AdditionalNTPSourcesDialog.tsx, src/common/components/hosts/HostStatus.tsx, src/common/components/hosts/HostValidationGroups.tsx, src/common/components/hosts/types.ts, src/ocm/components/hosts/HardwareStatus.tsx, src/ocm/components/hosts/NetworkingStatus.tsx, src/ocm/components/hosts/use-hosts-table.tsx
Adds validation-info based host status to `hosts-selection` and `networking` CIM cluster wizard steps
=> Cluster wizard host validation info

src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, src/common/components/clusterConfiguration/SNOControlGroup.tsx, src/common/components/clusterWizard/ClusterDetailsFormFields.tsx
https://issues.redhat.com/browse/MGMT-8463
https://user-images.githubusercontent.com/87187179/146930372-0cf3e06f-930f-4ebc-8c2a-98dfe3f92a78.mp4
=> MGMT-8463: SNO checkbox and OpenShift version misbehavior

src/ocm/components/clusterDetail/ClusterProperties.tsx
Reverts openshift-assisted/assisted-ui-lib#1010 which was merged by mistake.
=> Revert "MGMT-8077: Add "disk encryption" to cluster details"

src/ocm/components/AddHosts/HostsClusterDetailTab.tsx, src/ocm/components/AddHosts/utils.ts, src/ocm/services/Day2ClusterService.ts
https://issues.redhat.com/browse/MGMT-8547
https://github.com/openshift-assisted/assisted-ui-lib/pull/1030
=> MGMT-8547: Changes to day2 hosts take too long to display [FOLLOWUP]

src/common/components/featureSupportLevels/FeatureSupportLevelBadge.tsx, src/common/components/ui/PreviewBadge.tsx, src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
This reverts commit ff0ced50a89a4aea8ab533d4b361b4f2e45c61c5.
=> MGMT-8678: Revert "removed developer preview"

src/ocm/services/InfraEnvsService.ts, src/ocm/services/apis/InfraEnvsAPI.ts
=> MGMT-8530: Stop fetching all InfraEnvs in the UI

src/ocm/components/clusterDetail/ClusterProperties.tsx
Reverts openshift-assisted/assisted-ui-lib#1043 adding back MGMT-8077
Needs to be merged after #1056
=> MGMT-8077: Add "disk encryption" to cluster details

src/ocm/components/clusterDetail/ClusterProperties.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=2003163
When user managed networking == true the API virtual IP and Ingress virtual IP don't appear in the cluster details.
=> BZ-20003163: API virtual IP and Ingress virtual IP don't apear in user-managed networking mode 

src/common/components/hosts/EditHostForm.tsx
https://bugzilla.redhat.com/show_bug.cgi?id=2018070
=> BZ-2018070: The text in the hostname text box (edit host dialog) should come up selected

src/common/components/hosts/Hostname.tsx
https://issues.redhat.com/browse/MGMT-8790
Before:
After:
=> MGMT-8790 - Remove askerisk from hostname

src/common/config/constants.ts, src/ocm/components/clusterDetail/ClusterDetail.tsx
https://issues.redhat.com/browse/MGMT-8736
Calculating in how many days the Kubeconfig file is going to be deleted:
After 20 days, the button is removed:
=> MGMT-8736 - Cluster deletion warning wording

src/common/components/ui/formik/SwitchField.tsx, src/common/components/ui/formik/types.ts, src/ocm/components/clusterConfiguration/HostInventory.tsx
=> MGMT-8760: Disabled options should show explanation tooltip when hovering the checkbox/switch

src/ocm/api/utils.ts
https://issues.redhat.com/browse/MGMT-8901
The sentry message now includes the request url, status and method, and message/response/reason. Depending on the url and response lenght, the message might still get truncated, but hopefully the most important information can still be gathered.
=> MGMT-8901 - Reduce the amount of data sent to Sentry

src/common/api/types.ts, src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx, src/common/components/ui/DetailList.tsx, src/common/types/featureSupportLevel.ts, src/common/types/versions.ts, src/ocm/api/types.ts, src/ocm/components/AddHosts/InventoryAddHost.tsx, src/ocm/components/clusterConfiguration/ArmCheckbox.tsx, src/ocm/components/clusterConfiguration/CnvCheckbox.tsx, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/clusterConfiguration/OcsCheckbox.tsx, src/ocm/components/clusterConfiguration/ReviewCluster.tsx, src/ocm/components/clusterConfiguration/utils.ts, src/ocm/components/clusterDetail/ClusterProperties.tsx, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx, src/ocm/components/clusters/ClusterPage.tsx, src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx, src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts, src/ocm/components/featureSupportLevels/utils.ts, src/ocm/hooks/useOpenshiftVersions.tsx, src/ocm/selectors/clusterSelectors.ts, src/ocm/services/ClusterDetailsService.ts
**details**
**details after created**
**hosts**
**networking**
**review and create** 
**installation** 
**add hosts**
=> MGMT-8555: Implement UI for ARM

src/cim/components/InfraEnv/EnvironmentDetails.tsx, src/cim/components/modals/EditPullSecretModal.tsx, src/cim/components/modals/EditSSHKeyModal.tsx, src/cim/components/modals/types.ts, src/cim/components/modals/utils.ts
@ShiranHi 
According to https://marvelapp.com/prototype/haechg7/screen/84021478 we should show a warning if agent is booted with old ISO. But that cannot be detected from UI.
=> MGMT-8068: Add edit capabilities for infra env pullsecret and ssh keys

src/cim/components/helpers/status.ts
Remove deriving agent status from conditions and replace it by using
actual agent status and validationsInfo from agent's debugInfo.
Keep derived 'discovered' agent status.
=> Use debugInfo.state and validations info for agent status

src/cim/components/InfraEnv/InfraEnvFormPage.tsx, src/cim/components/modals/AddHostModal.tsx, src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, src/common/components/clusterConfiguration/DownloadIso.tsx
Fix iso-download/iso-config logic
Update static network help text
=> Show static ip info on ISO download page too

src/common/config/constants.ts, src/ocm/components/clusterDetail/ClusterDetail.tsx
Reverts openshift-assisted/assisted-ui-lib#1092
=> Revert "MGMT-9061 - Download kubeconfig button doesn't exist"

src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/featureSupportLevels/utils.ts, src/common/types/errorHandling.ts, src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx, src/ocm/components/featureSupportLevels/index.ts, src/ocm/sentry.ts
resolves issue of dependency on OCM sentry error handling using a callback
=> NO-ISSUE: resolve dependency of common on OCM featureSupportlevel utils

src/ocm/components/featureSupportLevels/featureStateUtils.ts
https://issues.redhat.com/browse/MGMT-9103
=> MGMT-9103: ARM cluster ODF and CNV tooltips are switched

src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx
https://issues.redhat.com/browse/MGMT-9137
=> MGMT-9137: Disk Encryption - radio buttons will appear below "enable on" switch buttons

src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/TangServers.tsx, src/common/config/constants.ts
https://issues.redhat.com/browse/MGMT-9148
1. Add label to alert 
2. Code improvements
3. Enable on workers won't appears if SNO is chosen
=> MGMT-9148: Disk Encryption fixes

src/common/components/hosts/RoleCell.tsx, src/common/components/hosts/tableUtils.tsx, src/common/components/hosts/utils.ts, src/ocm/components/hosts/HostsDiscoveryTable.tsx
This reverts commit 397a7d136646ed2ee205f624d558d07a904bb8fa.
=> Revert "MGMT-9067: Implement the UI for auto-select control plane nodes (#1097)"

src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
=> MGMT-8221: Adds missing white space

src/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx
https://issues.redhat.com/browse/MGMT-8913
Help text for the full version:
Help text for the minimal version:
=> MGMT-8913: Full and Minimal image help text is not clear

src/common/components/hosts/AITable.tsx
https://issues.redhat.com/browse/MGMT-9163
=> MGMT-9163: Hosts are not sorted in discovery hosts

src/common/components/hosts/RoleCell.tsx, src/common/components/hosts/tableUtils.tsx, src/common/components/hosts/utils.ts, src/ocm/components/hosts/HostsDiscoveryTable.tsx
Reverts openshift-assisted/assisted-ui-lib#1125
https://issues.redhat.com/browse/MGMT-8082
=> MGMT-8082: Auto role selection

src/common/components/clusterWizard/ClusterDetailsFormFields.tsx
=> MGMT-9137: Change TPMv2 alert message

src/cim/components/InfraEnv/InfraEnvFormPage.tsx, src/common/components/ui/formik/RichInputField.tsx, src/common/components/ui/formik/utils.ts, src/common/components/ui/formik/validationSchemas.ts
=> MGMT-8441: Add rich text validation for infra env name

src/cim/components/Agent/AgentStatus.tsx
Reverts openshift-assisted/assisted-ui-lib#1117
=> Revert "MGMT-8342 : Update approval popover"

src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/config/constants.ts
=> MGMT-8711: Remove proxy link for documentation from the ISO modal

src/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, src/common/components/clusterWizard/clusterDetailsValidation.ts, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
Pass only pullSecretSet instead of whole cluster object
=> Enhance cluster details form validation schema calculation

src/common/config/constants.ts, src/ocm/components/clusterConfiguration/HostInventory.tsx
https://issues.redhat.com/browse/MGMT-8975
https://issues.redhat.com/browse/MGMT-9297
=> MGMT-8975: Text updates for the Platform integration popover

src/cim/components/Agent/AgentStatus.tsx
reopening https://github.com/openshift-assisted/assisted-ui-lib/pull/1117
=> MGMT-8342: Update approval popover

src/common/components/clusterDetail/KubeconfigDownload.tsx
https://issues.redhat.com/browse/MGMT-9284
=> MGMT-9284: Kubeconfig file is always named "kubeconfig"

src/cim/components/Agent/BMCForm.tsx, src/common/components/ui/formik/validationSchemas.ts
Related to issue https://bugzilla.redhat.com/show_bug.cgi?id=2014874
=> BZ-2014874: Add bmc address validation to create bare metal asset form

src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
Related to : https://bugzilla.redhat.com/show_bug.cgi?id=2039826
=> BZ-2039826: Change text of button to Install Cluster in last step of cluster creation

src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
https://issues.redhat.com/browse/MGMT-9243
=> Fix text - Enable disk encryption on SNO

src/common/components/ui/WizardFooter.tsx, src/ocm/components/clusterConfiguration/ReviewStep.tsx
Fixes incorrect spacing in wizard footer
before
- unnecessary space before Next button
- space is too big between alert and buttons
after
=> Fix wizard footer spacing

src/common/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/clusterConfiguration/networkConfigurationValidation.ts, src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
Reverts openshift-assisted/assisted-ui-lib#1130
=> Revert "MGMT-9176:  SNO installations will use OVN by default"

src/ocm/services/ClustersService.ts
https://issues.redhat.com/browse/MGMT-9385
=> MGMT-9385: Wrong file name generated when downloading logs

src/cim/components/Agent/AgentTable.tsx, src/cim/components/Agent/tableUtils.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx
Bug 2054179:  https://bugzilla.redhat.com/show_bug.cgi?id=2054179
Add link from cluster details to infra env in cluster hosts table
=> Add link from cluster details to infra env

src/cim/components/helpers/versions.ts
Issue related: https://bugzilla.redhat.com/show_bug.cgi?id=2058624
=> Avoid duplicate values in OpenShift dropdown selector in cluster wizard

src/common/components/clusterDetail/ClusterProgress.tsx
Related to issue https://bugzilla.redhat.com/show_bug.cgi?id=2054342
=> Change cluster status adding hosts to installed on status

src/common/config/constants.ts, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/clusterConfiguration/ODFCheckbox.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts
=> MGMT-7075: Requirements for ODF popover

src/cim/components/Agent/BMCForm.tsx
NMState and MAC/interface mapping are not required anymore
=> Bug 2054798: Improve BMC nmstate fields validation

src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx, src/cim/components/InfraEnv/InfraEnvAgentTable.tsx, src/cim/components/modals/MassApproveAction.tsx, src/cim/components/modals/MassDeleteAgentModal.tsx, src/cim/components/modals/index.ts, src/common/components/hosts/HostToolbarActions.tsx, src/common/components/hosts/MassDeleteHostModal.tsx, src/common/components/hosts/TableToolbar.tsx, src/common/components/hosts/index.ts, src/ocm/components/hosts/HostsDiscoveryTable.tsx, src/ocm/components/hosts/ModalDialogsContext.tsx, src/ocm/components/hosts/use-hosts-table.tsx
=> MGMT-9250: Add mass delete action to OCM

src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
followup for https://github.com/openshift-assisted/assisted-ui-lib/pull/1162
=> Update Details page disabled message

src/common/components/ui/formik/SingleNodeCheckbox.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2058232
=> Bug 2058232: Add space between TP badge and text

src/common/components/clusterConfiguration/AdvancedNetworkFields.tsx, src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/clusterConfiguration/networkConfigurationValidation.ts, src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
This reverts commit 3ae12241309dfa948c7790b5745b80177379aa87.
=> Revert "MGMT-9176:  SNO installations will use OVN by default (#1165)" (#1193)

package.json, src/cim/components/Agent/AgentsSelectionTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionAdvanced.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizardFooter.tsx, src/cim/components/ClusterDeployment/helpers.ts, src/cim/components/ClusterDeployment/types.ts, src/cim/components/YamlPreview/YamlPreview.tsx, src/cim/components/YamlPreview/index.ts, src/cim/components/YamlPreview/useYAMLPreview.ts, src/common/components/hosts/RoleCell.tsx, src/common/components/hosts/RoleDropdown.tsx, src/common/components/hosts/tableUtils.tsx, src/common/components/ui/SimpleDropdown.tsx, yarn.lock
=> Bug 2058235: Add Yaml preview for edit cluster wizard

src/common/components/clusterDetail/ConsoleModal.tsx
[MGMT-9283](https://issues.redhat.com/browse/MGMT-9283)
It was agreed to simply delete the optional section in this feature, about showing how to set DNS for hosts.
We decided that it's not needed and is bug-prone.
=> MGMT-9283: delete optional section in console modal

src/cim/components/modals/EditNtpSourcesModal.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2059607
=> Bug 2059607: Edit NTP sources in the infra-env details page small adjustments

src/ocm/components/featureSupportLevels/featureStateUtils.ts
https://issues.redhat.com/browse/MGMT-9634
=> MGMT-9629: Handle ODF feature as unsupported for 4.10 in the UI

src/ocm/components/featureSupportLevels/featureStateUtils.ts
https://issues.redhat.com/browse/MGMT-9634
=> MGMT-9634: Updates the tooltip message

src/cim/components/InfraEnv/InfraEnvFormPage.tsx, src/common/components/ui/formik/validationSchemas.ts
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2059605
=> Bug 2059605:[UI] Make a smart validation on the infra-env location field

src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx, src/cim/components/featureSupportLevels/featureStateUtils.tsx, src/cim/components/helpers/versions.ts, src/cim/config/constants.ts
SNO is shown as tech preview for all versions
Related to bug: https://bugzilla.redhat.com/show_bug.cgi?id=2059610
=> Bug 2059610: SNO is shown as tech preview for all versions

src/ocm/components/clusterConfiguration/CnvCheckbox.tsx, src/ocm/components/clusterConfiguration/HostInventory.css, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/hosts/HostRequirementsContent.tsx
https://issues.redhat.com/browse/MGMT-9652
Also, the font size in the popover with the CNV requirements was adjusted
=> MGMT-9652: vsphere enhancements

.github/workflows/test_and_build.yaml
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1245
=> CIM2.5 - Run test_and_build workflow for CIM branches

src/cim/components/modals/AddHostModal.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2066616
=> Bug 2066616 - Incorrect message in add host dialog if BM is not supported

src/ocm/components/featureSupportLevels/featureStateUtils.ts
=> MGMT-9629: Handle ODF feature as unsupported for 4.10 in the UI (#1219)

src/cim/components/helpers/toAssisted.ts, src/common/components/clusterConfiguration/NetworkConfiguration.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1242
=> CIM2.5: Fix CIM SNO network page

src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/components/clusterConfiguration/SecurityFields.tsx, src/common/components/clusterConfiguration/UploadSSH.tsx, src/common/config/constants.ts
https://issues.redhat.com/browse/MGMT-6952
Todo:
=> MGMT-6952: Change help text in the "Generate Discovery ISO" modal

src/cim/components/modals/EditNtpSourcesModal.tsx, src/cim/components/modals/EditPullSecretModal.tsx, src/cim/components/modals/EditSSHKeyModal.tsx, src/common/components/hosts/EditHostForm.tsx, src/common/components/hosts/MassChangeHostnameModal.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1266
=> Update submit text for Hostname/PullSecret/SSH/NTP sources modals

src/cim/components/Agent/AgentStatus.tsx, src/cim/components/Agent/AgentsSelectionTable.tsx, src/cim/components/Agent/tableUtils.tsx, src/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetailsTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelection.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionAdvanced.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionBasic.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizardFooter.tsx, src/cim/components/ClusterDeployment/ScaleUpForm.tsx, src/cim/components/ClusterDeployment/helpers.ts, src/cim/components/ClusterDeployment/types.ts, src/cim/components/InfraEnv/InfraEnvAgentTable.tsx, src/cim/components/modals/AddHostModal.tsx, src/cim/components/modals/EditBMHModal.tsx, src/cim/components/modals/ScaleUpModal.tsx, src/common/components/hosts/MassChangeHostnameModal.tsx, src/common/components/hosts/tableUtils.tsx, src/common/components/hosts/types.ts, src/ocm/components/hosts/use-hosts-table.tsx
- improve on which tables, the actions are shown
- add disabled messages
- improve types
=> Fix table actions

src/cim/components/Agent/AgentStatus.tsx, src/cim/components/Agent/AgentsSelectionTable.tsx, src/cim/components/Agent/tableUtils.tsx, src/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentDetailsTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelection.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionAdvanced.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionBasic.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizardFooter.tsx, src/cim/components/ClusterDeployment/ScaleUpForm.tsx, src/cim/components/ClusterDeployment/helpers.ts, src/cim/components/ClusterDeployment/types.ts, src/cim/components/InfraEnv/InfraEnvAgentTable.tsx, src/cim/components/modals/AddHostModal.tsx, src/cim/components/modals/EditBMHModal.tsx, src/cim/components/modals/ScaleUpModal.tsx, src/common/components/hosts/MassChangeHostnameModal.tsx, src/common/components/hosts/tableUtils.tsx, src/common/components/hosts/types.ts, src/ocm/components/hosts/use-hosts-table.tsx
- improve on which tables, the actions are shown
- add disabled messages
- make action types more strict
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1261
=> CIM25: Fix table actions

src/cim/config/constants.ts
=> Bug 2059610: Add feature support level data for OpenShift version 4.7

src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/ClusterDeployment/types.ts
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2067076
=> Bug 2067076: show message when there are more than 1 host in sno clusters

src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/ClusterDeployment/types.ts
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2067076
=> Bug 2067076: UI show message when there are more than 1 host in sno clusters

src/cim/components/InfraEnv/InfraEnvFormPage.tsx, src/common/components/clusterConfiguration/ProxyFields.css, src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/components/ui/formik/RichInputField.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1276
=> CIM25: Validate infra form before submitting via temptifly

src/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx, src/cim/components/ClusterDeployment/types.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1279
=> CIM25: Bind all hosts from discovery step

src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/components/ui/formik/validationSchemas.ts
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2064179
=> Bug 2064179: pressing on edit cluster wide proxy settings getting incorrect msg regarding no proxy comma separator

src/cim/components/Agent/tableUtils.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1285
=> CIM25: Do not allow editing BMH in provisioned state

src/common/config/constants.ts
=> Fix pull-secret link

src/cim/components/InfraEnv/InfraEnvFormPage.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2070847
=> Bug 2070847: Adjust labels for new infra env -> network type

src/cim/components/ClusterDeployment/types.ts, src/cim/components/ClusterDeployment/use-networking-formik.ts, src/common/components/clusterConfiguration/NetworkConfiguration.tsx, src/common/components/clusterConfiguration/networkConfigurationValidation.ts, src/common/types/clusters.ts, src/ocm/components/clusterConfiguration/NetworkConfigurationForm.tsx
followup for https://issues.redhat.com/browse/MGMT-9873
needs proper testing
=> Do not update networking form after autosave

src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1291
=> CIM25: Stop the next flow after switching the autoselect

src/common/components/ui/formik/validationSchemas.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1293
=> improve No proxy validation

src/cim/components/InfraEnv/InfraEnvFormPage.tsx
ACM integration https://github.com/stolostron/console/pull/1489
=> Add validation for infraenv ntp sources

src/cim/components/InfraEnv/InfraEnvFormPage.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1295
=> CIM25: Add validation for infraenv ntp sources

src/cim/components/ClusterDeployment/AdditionalNTPSourcesDialogToggle.tsx, src/cim/components/modals/EditNtpSourcesModal.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1302
=> CIM25: Update NTP sources validation msg

package.json
Triggered by new tag - https://github.com/openshift-assisted/assisted-ui-lib/releases/tag/v2.3.7
=> Generated - New 2.3.7 version

.eslintrc, src/cim/components/ClusterDeployment/validationSchemas.ts, src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/TangServers.tsx, src/common/components/clusterWizard/ClusterDetailsFormFields.tsx, src/common/components/clusterWizard/clusterDetailsValidation.ts, src/common/components/hosts/HostStatus.tsx, src/common/components/hosts/tableUtils.tsx, src/ocm/components/hosts/HostsDiscoveryTable.tsx
=> Add eslint rule to disallow ==

src/common/components/hosts/tableUtils.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2073750
=> Bug 2073750: Greyed options are clickable and function as if they were not forbid - such as removing a host during install

src/common/components/hosts/tableUtils.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2073750
=> Bug 2073750: Greyed options are clickable on hosts table

src/common/components/ui/formik/validationSchemas.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1315
=> CIM25: Remove trailing . from noProxy validation values

src/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx, src/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1317
=> CIM25: Do not fail if there is no openshift version available

src/cim/components/Agent/AgentsSelectionTable.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelection.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionAdvanced.tsx, src/cim/components/ClusterDeployment/types.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1322
=> CIM25: Properly reset binding/saving state when switching between autosave

src/common/components/clusterDetail/OperatorsProgressItem.tsx
https://issues.redhat.com/browse/MGMT-10018
=> MGMT-10018: Change the 'available' status of operators to 'install'

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/components/hosts/hardwareInfo.ts, src/common/config/constants.ts, src/ocm/hooks/useInfraEnvImageUrl.ts, src/ocm/services/apis/ClustersAPI.ts, src/ocm/services/apis/InfraEnvsAPI.ts
I updated the image with the latest version from the BE. 
It changed our _types.ts_ file and therefore I fixed some of the files.  
@jkilzi 
In the file _hardwareInfo.ts_ they use the field:  **inventory.cpu?.clockMegahertz** as an one of the possibles parameters of a function, but from what I understood this filed doesn't exist anymore so I removed it, but I'm not sure this is the right thing to do. 
Screenshot of the change:
=> Updates swagger.yaml

src/ocm/components/clusters/ClusterPage.tsx, src/ocm/components/clusters/NewClusterPage.tsx
https://issues.redhat.com/browse/MGMT-10157
Part of the GA requirements + backported to v2.3.8
=> MGMT-10157: removes the tech-preview badges

src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1341
=> Set 1 host as minimum for SNO

src/ocm/components/clusterConfiguration/HostInventory.tsx
port from v2.3
https://issues.redhat.com/browse/MGMT-10190
https://issues.redhat.com/browse/MGMT-10214
=> MGMT-10214: Missing TP badge for vSphere

src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx
https://issues.redhat.com/browse/MGMT-7527
=> MGMT-7527: Deprecate old cluster networking fields in the UI

src/common/components/hosts/HostRequirements.tsx
https://issues.redhat.com/browse/MGMT-9952
Before:
After:
=> MGMT-9952: Minimum hardware requirements text change

src/ocm/components/clusterConfiguration/ArmCheckbox.tsx
https://issues.redhat.com/browse/MGMT-9891
Before:
After:
=> MGMT-9891: Align the question mark next to the ARM chebox

src/ocm/components/clusterConfiguration/HostInventory.tsx
https://issues.redhat.com/browse/MGMT-10220
**now:**
**before:**
=> MGMT-10220: Remove the TP badge next to the vSphere

src/common/components/clusterDetail/ClusterCredentials.tsx
https://issues.redhat.com/browse/MGMT-10418
=> MGMT-10418: Web console URL appears twice in installation page

src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1382
=> MGMT-10388 network suffix single stack 2.4

src/common/components/clusterDetail/ClusterCredentials.tsx
https://issues.redhat.com/browse/MGMT-10418
=> MGMT-10418:  web console url appears twice in installation page

src/common/components/ui/formik/validationSchemas.ts, src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
https://issues.redhat.com/browse/MGMT-10185
I also specified that characters need to be lowercase, since uppercase letters are not allowed.
Before:
After:
=> MGMT-10185: UI not blocking "localhost" name changing

src/ocm/components/hosts/HostsDiscoveryTable.tsx
https://issues.redhat.com/browse/MGMT-9431
I removed the **"force role"** function, so now the roles are determined only by the BE.
=> MGMT-9431: First discovered hosts forced to master role instead of auto-assign

src/ocm/components/clusterWizard/wizardTransition.ts, src/ocm/components/hosts/HardwareStatus.tsx
=> MGMT-10226 Show ignition-downloadable message

src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionValues.ts, src/common/components/clusterWizard/clusterDetailsValidation.ts, src/common/components/clusterWizard/types.ts, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1389
=> MGMT-10392 Do not patch if no changes happened

package.json
This reverts commit 689f2f8557a121e87c948348a4782e5eedd2007a.
=> Revert "NO_ISSUE: Fix build scripts to correctly emit types (#1386)"

src/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
https://issues.redhat.com/browse/MGMT-10485
Managed to reproduce the issue with the following steps:
1. create static IP cluster
2. in form view fill in network wide configuration steps, dual stack 
3. fill in invalid address in ipv6 fieldv - notice that data isn't save because it isn't valid
4. **switch to yaml** view and don't fill in data, thus wizard steps change without persistence of yaml view
5. click on cluster details
6. click on next
issue is the steps in the wizard don't correlate with the current status of the infra env, and we get an invalid UI state
=> MGMT-10485: Static IP shows wrong view after backend failing when filling in wrong ipv6 address

src/common/components/clusterWizard/ClusterDetailsFormFields.tsx, src/common/components/ui/formik/constants.tsx, src/common/components/ui/formik/index.tsx, src/common/components/ui/formik/validationSchemas.ts, src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
https://issues.redhat.com/browse/MGMT-9341
=> MGMT-9341: Interactive text checker in the cloud

src/common/components/hosts/MassChangeHostnameModal.tsx, src/common/components/ui/formik/RichInputField.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1420
=> [release-2.4] Do not run validation after setting setTouched

.idea/runConfigurations/sync_dist.xml, README.md, package.json, scripts/esbuild/dev.js, scripts/sync-dist.sh, yarn.lock
Reverts openshift-assisted/assisted-ui-lib#1376  
Unfortunately, this approach didn't work and it degraded the DX.  
I suggest reverting this change until we figure out how to make it work correctly
=> Revert "NO-ISSUE: Publish with Yalc after build in dev environment"

src/common/components/ui/formik/validationSchemas.ts
https://issues.redhat.com/browse/MGMT-10803
=> MGMT-10803: Allowing IPv4 machine net CIDRs larger than /25 [BACKPORT]

src/common/components/ui/formik/validationSchemas.ts
https://issues.redhat.com/browse/MGMT-10803
=> MGMT-10803: Allowing IPv4 machine net CIDRs larger than /25

src/ocm/components/clusterConfiguration/networkConfiguration/AvailableSubnetsControl.tsx
https://issues.redhat.com/browse/MGMT-10761
Before:
After:
=> MGMT-10761: Machine network says 2 vailable subnets when only 1 exists

src/common/api/swagger.yaml, src/common/api/types.ts, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts
https://issues.redhat.com/browse/MGMT-10610
OCP v4.10:
OCP v4.11:
Please note I didn't have access to a real ARM cluster, I only mocked that configuration in the incoming data.
=> MGMT-10610: Enable cluster managed networking on arm installation for 4.11

src/common/components/ui/formik/SwitchField.tsx
https://issues.redhat.com/browse/MGMT-10860
=> MGMT-10860: Checkmark icon visible when switch is turned off

src/common/components/clusterDetail/ClusterProgressItems.tsx, src/ocm/components/clusterDetail/ClusterDetail.tsx, src/ocm/components/clusterDetail/ClusterDetailStatusVarieties.tsx
https://issues.redhat.com/browse/MGMT-10442
Before:
After:
=> MGMT-10442: "Operators" is not aligned with the progress bar on zoom 100%

src/common/components/clusterConfiguration/SNODisclaimer.tsx, src/common/index.ts, src/common/utils.ts, src/ocm/components/AddHosts/utils.ts
https://issues.redhat.com/browse/MGMT-9380
https://issues.redhat.com/browse/MGMT-10731
https://issues.redhat.com/browse/MGMT-10086
https://issues.redhat.com/browse/MGMT-10701
Preview of what the alert will look like once OpenShift 4.11 is fully supported:
=> MGMT-9380: Assisted Installer Single Node + Day 2 workers

src/common/components/hosts/status.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2091825
=> Bug 2091825: Change alert text of disconnected hosts

src/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx, src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/components/clusterConfiguration/UploadSSH.tsx, src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx, src/common/components/ui/PopoverIcon.tsx, src/ocm/components/clusterConfiguration/CnvCheckbox.tsx, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/clusterConfiguration/ODFCheckbox.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx, src/ocm/components/clusterDetail/ClusterProperties.tsx
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2080711
=> Bug 2080711: Change the question mark icons to be gray and not blue

.eslintrc.js, I18N.md, README.md, locales/en/translation.json, locales/ja/translation.json, package.json, scripts/esbuild/common-config.js, scripts/i18n.sh, scripts/i18next-parser.config.js, src/cim/components/Agent/AgentsSelectionHostCountAlerts.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsSelectionBasic.tsx, src/cim/components/ClusterDeployment/ClusterScaleUpAutoHostsSelection.tsx, src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, src/common/hooks/use-translation-wrapper.ts, yarn.lock
Related to https://github.com/stolostron/console/pull/1710
Related to https://issues.redhat.com/browse/MGMT-8156
More info: https://docs.google.com/document/d/1KxjA8qsKA3K81MQrMF4jt0Ope4EM0lHWAN0emUx-q4w/edit
=> MGMT-8156: Extract strings for localization

src/common/components/clusterWizard/clusterDetailsValidation.ts, src/common/components/ui/formik/constants.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1463
=> MGMT-10927 Fix missing OCM validation error shown in pop-over

src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, src/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1477
=> MGMT-10918 default minimal iso 2.4

src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, src/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx
=> MGMT-10918: default minimal iso 2.5

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
eslint warnings dropped to 328
=> fix: infraEnvError is now a string

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/components/clusterConfiguration/SNOControlGroup.tsx, src/common/components/clusterConfiguration/SNODisclaimer.tsx, src/common/utils.ts, src/ocm/components/AddHosts/types.ts, src/ocm/components/AddHosts/utils.ts, src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx
https://issues.redhat.com/browse/MGMT-10862
UHC-portal PR: https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/3433
=> MGMT-10862: Make use of feature-support-levels for day2 SNO

src/ocm/components/hosts/HostsDiscoveryTable.tsx
https://issues.redhat.com/browse/MGMT-9636
Before:
After:
=> MGMT-9636: SNO cluster configuration should not include bulk actions

src/ocm/reducers/clusters/currentClusterSlice.ts
Something about the last change wasn't working...
(The tests went all crazy.)
=> NO_ISSUE: Fix host assignment

src/common/components/ui/formik/constants.tsx, src/common/components/ui/formik/validationSchemas.ts
https://issues.redhat.com/browse/MGMT-10958
**List of forbidden names:** 
**When a user tries to changes to such name:**
=> MGMT-10958: Hostname 'localhost4.localdomain4' and more should not be valid.

src/common/components/clusterWizard/clusterDetailsValidation.ts, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx, src/ocm/services/ClusterDetailsService.ts
https://issues.redhat.com/browse/MGMT-10208
=> MGMT-10208: Creating new clusters with ARM option enabled in the UI

src/common/api/swagger.yaml, src/common/api/types.ts, src/ocm/components/clusterConfiguration/networkConfiguration/AvailableSubnetsControl.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts
https://issues.redhat.com/browse/MGMT-10318
https://issues.redhat.com/browse/MGMT-10476
https://user-images.githubusercontent.com/87187179/176172394-d16462e1-7a4e-4901-88af-5d8eeb0bc671.mp4
=> MGMT-10476 - Advanced network IPv6 address fields on the Networking step aren't auto populated

src/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, src/cim/components/ClusterDeployment/NetworkConfiguration.tsx, src/cim/components/ClusterDeployment/ShortCapacitySummary.tsx, src/common/components/clusterWizard/clusterDetailsValidation.ts, src/common/components/ui/formik/validationSchemas.ts, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
fixes:
- call of useTranslation hook outside of component
- remove execution of getLimitedFeatureSupportLevels which is not yet available in CIM
- fix API range validation schema in  CIM which does have dual stack yet
=> Fix couple of issues which break CIM create wizard

.github/workflows/on-pull-request.yaml, .github/workflows/on-push.yaml, .github/workflows/on-release.yaml, locales/en/translation.json, locales/ja/translation.json, scripts/validatei18n_files.sh
Update our CI job to check whether the localization file was updated
=> MGMT-8156: upadte our CI job to check whether the localization files were  updated

.github/workflows/on-push.yaml
Fix problems with i18n tests (2)
=>  MGMT-8156: Fix problems with i18n tests (2)

.github/workflows/on-push.yaml, .github/workflows/on-release.yaml
Update our CI job to check whether the localization file was updated (only added in pull request action)
=> MGMT-8156: upadte our CI job to check whether the localization files were updated (only in pull request action)

src/cim/components/modals/AddBmcHostModal.tsx
=> MGMT-9612: [UI] Update size of Add Bmc Host modal

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1544
=> MGMT-11345 display stored ssh key 2.7

package.json, src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx, src/ocm/components/clusterConfiguration/DiscoveryImageSummary.tsx, src/ocm/components/clusterConfiguration/discoveryImageModal.tsx, src/ocm/hooks/useInfraEnvImageUrl.ts
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1541
=> MGMT-11344 iso download timing 2.7

src/ocm/components/clusterConfiguration/discoveryImageModal.tsx, src/ocm/hooks/useInfraEnvId.ts, src/ocm/hooks/useInfraEnvImageUrl.ts
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1549
=> MGMT-11384 wrong iso url 2.7

src/ocm/hooks/useOpenshiftVersions.tsx
https://issues.redhat.com/browse/MGMT-11392
=> MGMT-11392: New cluster creation failed when OCP v4.11 is selected by default

src/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts, src/ocm/components/clusterConfiguration/staticIp/data/nmstateTypes.ts, src/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1556 to add to new Assisted UI Lib 2.8 Release
=> Static IP UI form view with vlans generates wrong nmstate yaml - 2.8

src/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts, src/ocm/components/clusterConfiguration/staticIp/data/nmstateTypes.ts, src/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Co-authored-by: Celia Amador <camadorg@redhat.com>
port to 2.7
=> Static IP: form to yaml vlan (#1556) (r/2.7)

src/common/components/storage/StorageUtils.tsx, src/ocm/components/hosts/HostsStorageTable.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1570
=> MGMT-11545 show correct disk storage 2.8

locales/en/translation.json, src/cim/components/Agent/AgentStatus.tsx, src/cim/components/Hypershift/DetailsPage/NodePoolsTable.tsx, src/cim/components/helpers/status.ts, src/common/components/hosts/HostStatus.tsx, src/common/components/hosts/status.tsx
=> Agent based installation does not require node CSR approval

src/ocm/components/clusterConfiguration/InformationAndAlerts.tsx
Related to https://issues.redhat.com/browse/MGMT-11747
=> MGMT-11747: Add space beween information links

src/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/formViewHostsValidationSchema.tsx
Related to https://issues.redhat.com/browse/MGMT-11627
Validate that host IP is not broadcast IP or network address:
=> MGMT-11627:We accept both: broadcast IP and network address for host IP

src/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/formViewHostsValidationSchema.tsx
=> MGMT- 11627: we accept broadcast ip and network address for host ip

src/ocm/components/clusterConfiguration/HostsNetworkConfigurationControlGroup.tsx
https://issues.redhat.com/browse/MGMT-11528
**Before:**
**After:**
=> MGMT-11528 - Renaming option under Hosts' network configuration

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/config/constants.ts, src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx, src/ocm/components/clusterConfiguration/ReviewStep.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx, src/ocm/components/clusterWizard/ClusterDetails.tsx, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx, src/ocm/components/clusterWizard/HostDiscovery.tsx, src/ocm/components/clusterWizard/Operators.tsx, src/ocm/components/hosts/use-hosts-table.tsx, src/ocm/components/hosts/utils.ts, src/ocm/services/ClusterDetailsService.ts, src/ocm/services/ClustersService.ts, src/ocm/services/DiscoveryImageFormService.ts
https://issues.redhat.com/browse/MGMT-11800
Adds a `ui_ocm` tag to the cluster create/update/install parameters if it's not already there when using OCM.
=> MGMT-11800 - Adding a cluster tag for SaaS

src/common/components/clusterConfiguration/utils.ts, src/common/selectors/clusterSelectors.ts, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/clusterConfiguration/ReviewCluster.tsx, src/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx
https://issues.redhat.com/browse/MGMT-11916
=> MGMT-11916: UI always shows "vSphere integration" as enabled due to API change

.eslintrc.js, src/cim/components/InfraEnv/utils.ts, src/common/components/hosts/DiskRole.tsx, src/common/components/hosts/HostRowDetail.tsx, src/common/components/hosts/HostsTableDetailContext.tsx, src/common/components/hosts/types.ts, src/common/components/storage/StorageDetail.tsx, src/common/components/ui/table/utils.ts, src/ocm/components/clusterDetail/ProgressBarAlerts.tsx
Enforces type definitions names to use `PascalCase`.
=> Enforce TS type definition name conventions

src/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx, src/common/components/clusterConfiguration/ProxyFields.tsx, src/common/components/clusterConfiguration/UploadSSH.tsx, src/common/components/ui/PopoverIcon.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx
Fixes:
- [MGMT-11313](https://issues.redhat.com/browse/MGMT-11313)
- [MGMT-11801](https://issues.redhat.com/browse/MGMT-11801)
=> MGMT-11313: text is not aligned

src/common/components/ui/formik/utils.ts
The function is used by ACM codebase
=> Add back missing labelsToArray helper function

locales/en/translation.json, scripts/validatei18n_files.sh, src/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx, src/common/components/clusterConfiguration/ProxyFields.tsx
Cherry-picked from 7d164dfb
Fixes Bug 2118308
=> [2.6-cim] Bug 2118308: Fix typos in i18n msgs

src/cim/components/common/constants.ts
=> Bug 2126853: Update link to CIM prerequisities

src/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx, src/cim/components/Hypershift/DetailsPage/HostedClusterProgress.tsx
Do not show progressing condition in conditions table Show error when Degraded condition is True
=> [2.6-cim] Bug 2119340: Consider progressing condition when calculating hypershift status

src/cim/components/Hypershift/hooks/useSupportedOCPVersions.ts
Cherry-picked from 7a2db384
Bug 2125234
Co-authored-by: Jiri Tomasek <jtomasek@redhat.com>
=> [2.6] Bug 2125234: Fix supported versions config map format

src/cim/components/common/constants.ts
Cherry-picked from d26dde74
Fixes Bug 2126853
=> [2.6-cim] Bug 2126853: Update link to CIM prerequisities

src/ocm/components/clusterConfiguration/staticIp/components/YamlView/YamlViewFields.tsx
https://issues.redhat.com/browse/MGMT-11654
=> MGMT-11654 - Need to show (?) with pop over for the Mac to interface name mapping section heading

locales/en/translation.json, src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
I saw this issue while running the i18n script
=> Removes a leading space from a string in CIM

src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
=> Fix: Remove duplicate DNS field

src/common/config/constants.ts, src/ocm/components/clusterConfiguration/staticIp/components/YamlView/YamlViewFields.tsx
https://issues.redhat.com/browse/MGMT-11464
Adding a  "Learn more" link for NMState.
=> MGMT-11464: Adding Learn More for NMState

locales/en/translation.json, src/common/api/swagger.yaml, src/common/api/types.ts, src/common/components/clusterConfiguration/utils.ts, src/common/config/constants.ts, src/common/selectors/clusterSelectors.ts, src/common/types/clusters.ts, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx, src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationVsphere.tsx, src/ocm/components/clusterWizard/ClusterPlatformIntegrationHint.tsx, src/ocm/components/clusterWizard/ClusterWizardFooter.tsx, src/ocm/components/clusterWizard/HostDiscovery.tsx, src/ocm/components/ui/OcmFormFields.tsx, src/ocm/hooks/useClusterSupportedPlatforms.ts, src/ocm/services/HostDiscoveryService.ts
Related to : https://issues.redhat.com/browse/MGMT-11268
Without hosts:
When we have vSphere hosts:
https://user-images.githubusercontent.com/11390125/193260796-bbb6b639-9bbc-4c27-864b-0f3f7c374f69.mp4
When we have Nutanix hosts:
https://user-images.githubusercontent.com/11390125/193768179-8a3e6991-a6c9-42b5-97df-e238b67b537d.mp4
=> MGMT-11268: Add Nutanix platform type

locales/en/translation.json, src/common/components/ui/ClusterEventsToolbar.tsx
https://issues.redhat.com/browse/MGMT-9245
**Before:**
**After:**
=> MGMT-9245: Remove ellipses on host discovery

package.json, src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx, src/ocm/services/ClusterDetailsService.ts
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1673
=> MGMT-11294 default network type OVN

src/common/types/clusters.ts, src/ocm/hooks/useClusterSupportedPlatforms.ts
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1694
=> MGMT-12275 fix supported platforms logic

src/common/types/typescriptExtensions.ts, src/ocm/components/AddHosts/AddHosts.tsx, src/ocm/components/clusters/Clusters.tsx, src/ocm/components/hosts/use-hosts-table.tsx, src/ocm/reducers/clusters/currentClusterSlice.ts, src/ocm/services/ClustersService.ts, src/ocm/services/HostsService.ts, src/ocm/services/InfraEnvsService.ts
https://issues.redhat.com/browse/MGMT-12094
Replaces #1652
=> MGMT-12094: Remove unnecessary calls to the get hosts api

src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx, src/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionValues.ts, src/common/components/clusterWizard/ClusterWizardStep.css, src/ocm/components/AddHosts/InventoryAddHost.tsx, src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx, src/ocm/components/AddHosts/day2Wizard/Day2DownloadISO.tsx, src/ocm/components/AddHosts/day2Wizard/Day2GenerateISO.tsx, src/ocm/components/AddHosts/day2Wizard/Day2Wizard.tsx, src/ocm/components/AddHosts/day2Wizard/Day2WizardContext.tsx, src/ocm/components/AddHosts/day2Wizard/Day2WizardContextProvider.tsx, src/ocm/components/AddHosts/day2Wizard/Day2WizardNav.tsx, src/ocm/components/AddHosts/day2Wizard/constants.tsx, src/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx, src/ocm/components/clusterWizard/wizardTransition.ts, src/ocm/components/hosts/ModalDialogsContext.tsx
https://issues.redhat.com/browse/MGMT-12242
=> Host discovery wizard - simple flow

src/ocm/components/clusterWizard/HostDiscovery.tsx, src/ocm/services/HostDiscoveryService.ts
Port of #1715 
* Fix wrong patch request when platform integration is disabled
=> MGMT-12424: Wrong patch request when platform integration is disabled (#1715)

src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx
https://issues.redhat.com/browse/MGMT-12321
Before:
After:
=> MGMT-12321 - VMware SNO cluster - "Integrate with platform..." toggle is disabled with no explanation

src/ocm/components/clusterConfiguration/HostsNetworkConfigurationControlGroup.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts
https://issues.redhat.com/browse/MGMT-10940
=> MGMT-10940 - Missing disabled field tooltip of static IP configuration

package.json, src/cim/components/ClusterDeployment/networkConfigurationValidation.ts, src/cim/components/ClusterDeployment/use-networking-formik.ts, src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx, src/common/components/ui/formik/NumberInputField.tsx, src/common/components/ui/formik/validationSchemas.ts, src/ocm/components/hosts/ModalDialogsContext.tsx, src/ocm/components/hosts/UpdateDay2ApiVipForm.tsx, src/ocm/components/hosts/use-hosts-table.tsx, src/ocm/hooks/usePullSecret.ts, src/ocm/types.ts
=> BZ2136106: CIM - UI validation for overlapping CIDRs

src/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx
https://issues.redhat.com/browse/MGMT-11400
=> MGMT-11400 - Need update message about Add Host in case integration

src/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx, src/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx, src/ocm/components/clusterWizard/Operators.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts, src/ocm/services/OperatorsService.tsx
=> MGMT-12311 LVMO + CNV fixes 2.12

src/common/components/hosts/RoleDropdown.tsx, src/common/components/ui/SimpleDropdown.tsx
https://issues.redhat.com/browse/MGMT-12578
Before:
After:
But the bug still prevails for the action kebab menu:
=> MGMT-12578: Role selection is cut because of an inner scroll bar

src/cim/components/Hypershift/HostedClusterWizard/DetailsStep/DetailsForm.tsx, src/cim/components/Hypershift/HostedClusterWizard/DetailsStep/DetailsStep.tsx, src/cim/components/Hypershift/HostedClusterWizard/DetailsStep/types.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1756
=> Hypershift: Use supported ocp version in formik init values

src/cim/components/ClusterDeployment/helpers.ts, src/cim/components/ClusterDeployment/types.ts, src/cim/components/Hypershift/DetailsPage/ClusterInstallationProgress.tsx, src/cim/components/Hypershift/DetailsPage/NodePoolsProgress.tsx, src/cim/components/Hypershift/DetailsPage/NodePoolsTable.tsx, src/cim/components/Hypershift/modals/AddNodePoolModal.tsx, src/cim/components/Hypershift/modals/ManageHostsModal.tsx, src/cim/components/Hypershift/types.ts, src/cim/components/helpers/agentClusterInstall.ts, src/cim/components/modals/utils.ts, src/cim/types/k8s/agent-cluster-install.ts, src/cim/types/k8s/agent.ts, src/cim/types/k8s/infra-env-k8s-resource.ts, src/cim/types/k8s/shared.ts
Required by: https://github.com/stolostron/console/pull/2264
=> Update types to enable correct typechecking on CIM

locales/en/translation.json, package.json, src/cim/components/modals/AddBmcHostYamlForm.tsx
Rendering of FE and BE errors follows the same pattern.
This PR will be backported to 2.6 and 2.7.
=> BZ2117507: Unify look of errors in Upload by YAML

src/cim/components/modals/CimConfiguration/persist.ts
=> MGMT-12451: Fix create AgentClusterConfig

locales/en/translation.json, package.json, src/cim/components/modals/AddBmcHostYamlForm.tsx
=> BZ2117507: Unify look of errors in Upload by YAML (ACM 2.6)

locales/en/translation.json, package.json, src/cim/components/modals/AddBmcHostYamlForm.tsx
=> BZ2117507: Unify look of errors in Upload by YAML (ACM 2.7)

src/cim/components/ClusterDeployment/ClusterInstallationError.tsx, src/common/config/constants.ts, src/ocm/components/clusterDetail/ClusterInstallationError.tsx, src/ocm/components/clusterDetail/ProgressBarAlerts.tsx
=> MGMT-12590 Use Jira for customer bug reports [2.7-cim]

src/cim/components/helpers/clusterDeployment.ts
Multiple networks:
---
Single network:
=> MGMT-12898: Show dualstack data on the Cluster Detail page

src/cim/components/helpers/clusterDeployment.ts
=> MGMT-12898: Show dualstack data on the Cluster Detail page [rel-2.7]

src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
https://issues.redhat.com/browse/MGMT-12657
=> MGMT-12657 - Multiple DNS servers - explain the option better to the user

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx, src/ocm/components/clusterConfiguration/review/ReviewClusterDetailTable.tsx, src/ocm/components/clusterConfiguration/review/ReviewOperatorsTable.tsx, src/ocm/components/clusterConfiguration/review/ReviewValidations.tsx, src/ocm/components/clusterDetail/ClusterProperties.tsx
=> NO_ISSUE: Fix TS errors

src/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx
Somewhat port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1826
=> MGMT-13037 Add Nutanix link in case its the integrated platform - 2.13

src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
https://issues.redhat.com/browse/MGMT-12382
DHCP allocation is not supported for nutanix hosts (even if platform integration was not enabled). We need to check the supported-platforms instead of cluster.platform.type to determine whether to hide the DHCP checkbox or not.
Note that it takes a second to get the `supported-platforms` and check for nutanix. So for that second the DHCP checkbox might appear and then disappear. I figured not-hiding it initially was better than hiding it and having it appear after a second (I assume there will be more people with non-nutanix hosts than vice versa).
If anyone has any ideas for how to avoid this flashing, they are welcome.
=> MGMT-12382 - Nutanix cluster - Trying to enable DHCP for vips returns "The DHCP server failed to allocate the IP"

src/ocm/components/clusterConfiguration/review/ReviewClusterDetailTable.tsx, src/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx, src/ocm/components/clusterConfiguration/review/ReviewOperatorsTable.tsx
Detected here: https://github.com/openshift-assisted/assisted-ui-lib/pull/1811#discussion_r1056087886
Fix the `data-testid` casing.
=> NO_ISSUE: Fix casing for data-testid

locales/en/translation.json, src/common/components/clusterDetail/ConsoleModal.tsx
=> MGMT-13046: Add missing translation for console dialog

locales/en/translation.json, src/common/components/clusterDetail/ConsoleModal.tsx
Fixes MGMT-13046
Cherry-picked from 2c4f1d6f
=> [2.7-cim] MGMT-13046 Add missing translation for console dialog

locales/en/translation.json, src/cim/components/modals/CimConfiguration/persist.ts
=> MGMT-13153: Add router-type to assisted-image-service Route

src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkForm.tsx, src/common/components/ui/formik/validationSchemas.ts
=> MGMT-13108: Fix listing IPv6 CIDRs for Hypershift [acm 2.7]

src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationNote.tsx, src/ocm/components/clusterConfiguration/review/ReviewCluster.css, src/ocm/components/clusterConfiguration/review/ReviewPreflightChecks.tsx, src/ocm/components/clusterConfiguration/review/ReviewSummary.tsx
https://issues.redhat.com/browse/MGMT-13060
- Adding the note about Platform integration to the new Review & Create page, in the "Host inventory" block
Note: The section "Host inventory" was previously "Inventory", I renamed it based on the latest mockup.
=> MGMT-13060 Display "Platform Integration" in new "Review & Create" page

locales/en/translation.json, src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
https://issues.redhat.com/browse/MGMT-13103
Backpor of #1842
=> Block UMN option in case we're in nutanix platform - 2.13

locales/en/translation.json, src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
https://issues.redhat.com/browse/MGMT-13103
Backport of #1842
=> Block UMN option in case we're in nutanix platform - 2.14

src/cim/components/modals/utils.ts, src/common/components/clusterDetail/OperatorsProgressItem.tsx, src/common/components/clusterWizard/ReviewValidations.tsx, src/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx, src/common/components/clusterWizard/validationsInfoUtils.ts, src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx, src/ocm/components/clusterConfiguration/staticIp/components/StaticIpHostsArray.tsx, src/ocm/components/clusterDetail/ProgressBarAlerts.tsx
- Fixing problems which become errors in Typescript 4.
=> Fixes Typescript 4 errors - part 1

src/cim/components/modals/EditPullSecretModal.tsx
=> MGMT-13347 Fix pull secret modal dialog

src/cim/components/modals/EditPullSecretModal.tsx
=> [2.7-cim] MGMT-13347 Fix pull secret modal dialog (#1873)

package.json, src/cim/components/InfraEnv/utils.ts, src/common/components/clusterConfiguration/utils.ts, src/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx, src/common/components/clusterWizard/validationsInfoUtils.ts, src/common/components/hosts/utils.ts, src/common/components/ui/formik/utils.ts, src/common/utils.ts, src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx
Fixing more issues that would be errors in Typescript 4.
=>  Fixes Typescript 4 errors - part 2

src/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx
https://issues.redhat.com/browse/MGMT-13460
Fixes the validation of ipv6 addresses.
=> MGMT-13460: Correct validations of ipv6 addresses

src/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1883
=> MGMT-13460 correct ipv6 validations - 2.14

package.json
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1882
=> Correct deprecated translation exports 2.14

src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
https://issues.redhat.com/browse/MGMT-11676
https://user-images.githubusercontent.com/87187179/214527349-c3bd9c3f-a4a5-4da9-ba91-b0c43eff1f7f.mp4
=> MGMT-11676 - The entered values are lost when we toggle between ipv4/dual stack

src/common/config/constants.ts
=> MGMT-13093: Change ODF requirements link url 2.14

src/common/components/ui/formik/validationSchemas.ts, src/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1898
=> MGMT-13489: UI won't getstuck with IP with suffix - 2.14

src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx, src/common/components/ui/PopoverIcon.tsx, src/ocm/components/clusterConfiguration/HostInventory.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/StackTypeControl.tsx, src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx
https://issues.redhat.com/browse/MGMT-13226
Before:
After:
Network and stack type controls were handled similarly. However controls with helper texts are a bit trickier, so for now I'm leaving them as is.
=> MGMT-13226 - Tooltip should not appear when user hovers over the informational question mark

src/common/components/ui/table/utils.ts, src/ocm/components/clusterConfiguration/review/ReviewClusterDetailTable.tsx, src/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx, src/ocm/components/clusterConfiguration/review/ReviewOperatorsTable.tsx
Fixes the console errors and warnings we were receiving from the `Table` component due to the missing `aria-label` at the table level, and the `rowKey` at the row level.
=> NO-ISSUE: Fix table console errors

locales/en/translation.json, package.json, src/common/components/clusterConfiguration/UploadSSH.tsx, src/common/components/ui/formik/validationSchemas.ts, src/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
Enable to create ISO image.
This reverts commit 1de5c5213ae5ed68fbde384b0eb8dd6e668ca09d (PR #1909 )
=> Revert commit PR 1909

src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
https://issues.redhat.com/browse/MGMT-13443
**Before:**
**After:**
=> MGMT-13443 - Switch SDN and OVN places

src/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
https://issues.redhat.com/browse/MGMT-13652
**Before:**
**After:**
=> MGMT-13652 - Fix machine network label capitalisation

src/ocm/components/hosts/HostRequirementsContent.tsx
Related to https://issues.redhat.com/browse/MGMT-12308
Add the additional requirements for operators in minimal hardware requirements in SNO clusters:
=> MGMT-12308: Add additional HW requirements for operators in SNO clusters

src/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/FormViewHostsFields.tsx
https://issues.redhat.com/browse/MGMT-10941
**Before:**
**After:**
=> MGMT-10941 - Missing "Host specific configurations" header

src/common/components/ui/OpenShiftVersionDropdown.tsx, src/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx
Port of https://github.com/openshift-assisted/assisted-ui-lib/pull/1927
=> MGMT-13677: Fix non-production warning only for appropriate versions 2.15

.eslintrc.js, package.json, src/cim/components/helpers/network.ts, src/common/components/ui/formik/AdditionalNTPSourcesField.tsx, src/common/components/ui/formik/LabelField.tsx, src/common/components/ui/formik/SelectField.tsx, src/common/components/ui/formik/SwitchField.tsx, src/common/components/ui/formik/UploadField.tsx, src/common/components/ui/formik/types.ts, src/common/hooks/useFieldErrorMsg.tsx, src/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx
Fixing errors of type `no-unsafe-argument`
=> Fix no-unsafe-argument errors

locales/en/translation.json, src/common/components/clusterConfiguration/SNODisclaimer.tsx
https://issues.redhat.com/browse/MGMT-9167
New text
=> MGMT-9167: Rephrase label in SNO disclaimer

src/common/components/hosts/HostRequirements.tsx
=> Fix host requirements typo

.github/workflows/on-pull-request.yaml, .github/workflows/on-push.yaml, .github/workflows/on-release.yaml
* MGMT-12825 Use new Github actions updated to Node16
* Set correct node-version to 16
=> [2.7-cim] MGMT-12825 Use new Github actions updated to Node16

src/common/components/hosts/HostRequirements.tsx
Cherry-picked from a474c256
Fixes MGMT-13349
=> [2.7-cim] Fix host requirements typo

locales/en/translation.json, src/common/components/ui/formik/LabelField.tsx, src/common/components/ui/formik/PullSecretField.tsx
* Add missing label translation to LabelField
* Enable translation for label in Pull secret field Fixes MGMT-13745
=> [2.7-cim] MGMT-13745: Translation fixes in Infra environment form

src/common/components/ui/PreviewBadge.tsx
=> Hotfix for data-testid undefined

src/common/components/ui/PreviewBadge.tsx
https://issues.redhat.com/browse/MGMT-13154
**Before:**
https://user-images.githubusercontent.com/87187179/222683928-0667643a-7115-4871-aa79-aa3286b5a266.mp4
**After:**
https://user-images.githubusercontent.com/87187179/222683952-0179b218-5f93-4932-afc8-bbe45ee1beed.mp4
=> MGMT-13154 - LVMO link hyper element of checkbox is extended until start of Developer Preview button

src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
https://issues.redhat.com/browse/MGMT-12603
**Before:**
**After:**
=> MGMT-12603 - Network Type selector when there is only 1 valid option

src/ocm/components/clusterConfiguration/staticIp/components/StaticIpHostsArray.tsx
https://issues.redhat.com/browse/MGMT-13702
https://user-images.githubusercontent.com/87187179/224305091-508bba07-47c7-454b-9a31-c6183542a2a0.mp4
=> MGMT-13702 - Copy nmstate configuration must be enabled by default

src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx
https://issues.redhat.com/browse/MGMT-13728
**Before:**
**After:**
=> MGMT-13728 - Platform helper text should be reformatted

src/common/components/ui/OpenShiftVersionDropdown.tsx
https://issues.redhat.com/browse/MGMT-11887
**Before:**
**After:**
=> Discourage / prevent the average user from choosing older z versions

src/ocm/components/hosts/UpdateDay2ApiVipModal.tsx
https://issues.redhat.com/browse/MGMT-13790
=> MGMT-13790 - Day2 "set the IP or domain used to reach the cluster" modal closing issues

.eslintrc.js, package.json, src/cim/components/Agent/AgentStatus.tsx, src/cim/components/Agent/BMCForm.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentKubeconfigDownload.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentReviewStep.tsx, src/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx, src/cim/components/Hypershift/modals/AddNodePoolModal.tsx, src/cim/components/Hypershift/modals/ManageHostsModal.tsx, src/cim/components/InfraEnv/InfraEnvFormPage.tsx, src/cim/components/YamlPreview/YamlPreview.tsx, src/cim/components/modals/EditNtpSourcesModal.tsx, src/cim/components/modals/EditPullSecretModal.tsx, src/cim/components/modals/EditSSHKeyModal.tsx, src/cim/components/modals/MassApproveAgentModal.tsx, src/cim/components/modals/ScaleUpModal.tsx, src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, src/common/components/hosts/AdditionalNTPSourcesDialog.tsx, src/common/components/hosts/MassDeleteHostModal.tsx, src/common/components/hosts/RoleDropdown.tsx, src/ocm/components/clusterDetail/ClusterDetail.tsx, src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
Removing the warnings about `no-misused-promises`
For the most part, I have just added exceptions to the code, to avoid breaking the existing actions.
The ones I have fixed are those that I could test properly (a few in OCM).
But we won't be able to introduce more issues of this type in the future.
=> Fix misused promises

src/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx
https://issues.redhat.com/browse/MGMT-13649
**Before**
**After:**
Non-SNO:
SNO:
=> MGMT-13649 - SNO cluster - R&C page - no API and Ingress IPs info

src/common/components/storage/DisksTable.tsx
https://issues.redhat.com/browse/MGMT-12331
**Before:**
**After:**
=> MGMT-12331 - Remove Format column in the Host discovery page

src/ocm/components/clusters/Clusters.tsx, src/ocm/components/clusters/ClustersTable.tsx, src/ocm/components/clusters/DeleteClusterModal.tsx
https://issues.redhat.com/browse/MGMT-11395
**Before:**
https://user-images.githubusercontent.com/87187179/224264751-9c2895c4-1588-4025-b2a3-d4157cfef5eb.mp4
**After:**
https://user-images.githubusercontent.com/87187179/224264780-a4d795bd-0190-474f-a33b-e397882e53b0.mp4
**With no way to close the modal while the cluster is being deleted:**
https://user-images.githubusercontent.com/87187179/224653145-b348bbfc-5f70-4df0-a54f-98702eb1169c.mp4
=> MGMT-11395 - Improve cluster and hosts deletion experience

src/common/components/ui/OpenShiftVersionDropdown.tsx
=> Fix missing key in Openshift version dropdown

locales/en/translation.json, src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx, src/common/components/hosts/VMRebootConfigurationInfo.tsx
=> Fix spacing between help texts for Hosts

src/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1967
=> MGMT-12928: Add separate handling for progressing conditions

locales/en/translation.json, src/cim/components/Agent/AgentStatus.tsx, src/cim/components/common/SpecSyncErrAlert.tsx, src/cim/components/helpers/agentStatus.tsx, src/cim/components/helpers/status.ts
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1974
=> MGMT-13573: Propagate agent's spec sync error to status

src/cim/components/ClusterDeployment/networkConfigurationValidation.ts, src/cim/components/ClusterDeployment/use-networking-formik.ts, src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkForm.tsx, src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx, src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/types.ts, src/common/components/ui/formik/validationSchemas.ts
Stop using podCIDR as it is deprecated
=> MGMT-13262: Enable setting host prefix for hypershift clusters

src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkForm.tsx, src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx, src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/types.ts
ACM PR https://github.com/stolostron/console/pull/2716
=> MGMT-14122: Hypershift: Remove machine CIDR dropdown

src/cim/components/Agent/tableUtils.tsx, src/cim/components/ClusterDeployment/types.ts, src/cim/components/InfraEnv/InfraEnvAgentTable.tsx
ACM PR https://github.com/stolostron/console/pull/2727
=> MGMT-14138: CIM Hypershift: Fix details page link from Agent to Cluster

src/cim/components/Agent/tableUtils.tsx, src/cim/components/ClusterDeployment/types.ts, src/cim/components/InfraEnv/InfraEnvAgentTable.tsx
Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1997
=> CIM Hypershift: Fix details page link from Agent to Cluster

src/cim/components/Hypershift/forms/NodePoolAgentsForm.tsx, src/cim/components/Hypershift/modals/NodePoolForm.tsx
backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/1998
=> Disable changing labels when editing nodepool

src/cim/components/common/constants.ts
Fixes MGMT-14121
Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/2002
=> [2.7-cim] MGMT-14121 Update documentation link for enabling CIM

src/cim/components/common/constants.ts
=> MGMT-14121 Update documentation link for enabling CIM

package.json, src/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx
=> MGMT-14214: Disable and uncheck SNO checkbox when choose IBM Power or IBM Z archs - 2.18

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/types/cpuArchitecture.ts, src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx, src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts, src/ocm/components/newFeatureSupportLevels/NewFeatureSupportLevelProvider.tsx, src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts, src/ocm/services/Day2ClusterService.ts
=> MGMT-14225: New support level unavailable added - 2.18

src/common/api/swagger.yaml, src/common/api/types.ts, src/common/types/cpuArchitecture.ts, src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx, src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx, src/ocm/components/featureSupportLevels/featureStateUtils.ts, src/ocm/components/newFeatureSupportLevels/NewFeatureSupportLevelProvider.tsx, src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts, src/ocm/services/Day2ClusterService.ts
Related to https://issues.redhat.com/browse/MGMT-14225
With the new API(2.18), we have one more support level added: 'unavailable'. We need to adapt the UI to works with that.
=> MGMT-14225: New support level unavailable added

locales/en/translation.json, src/cim/components/Agent/NoAgentsAlert.tsx
=> MGMT-13319 Fix translation for NoAgentsAlert component

locales/en/translation.json, src/cim/components/modals/CimConfiguration/persist.ts
Fixes MGMT-14216
Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/2017
=> [2.7-cim] MGMT-14216: Don't fail CIM configuration on unsuccessful provisioning configuration

locales/en/translation.json, src/cim/components/Agent/NoAgentsAlert.tsx
Backport of https://github.com/openshift-assisted/assisted-ui-lib/pull/2018
MGMT-13319
=> [2.7-cim] MGMT-13319: Fix translation for NoAgentsAlert component

src/ocm/components/HostsClusterDetailTab/utils.ts
=> MGMT-14270: We need to show 'Add hosts' tab to cluster with 'installed' status - 2.18

src/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
=> MGMT-14262: Put correct CPU architecture in dropdown when OCP version changed - 2.18

src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
=> MGMT-14267: CNV will be disabled for P/Z clusters - 2.18

src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx, src/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx, src/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx, src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
=> MGMT-14170: In Add hosts modal disable minimal ISO and ipxe for s390 architecture - 2.18

src/common/types/cpuArchitecture.ts, src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx, src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts, src/ocm/services/Day2ClusterService.ts
=> MGMT-14290: Filling CpuArchitectureDropdown from release image architectures - 2.18

src/common/types/cpuArchitecture.ts, src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx, src/ocm/components/clusterDetail/ClusterProperties.tsx
=> MGMT-14320: Power Z clusters can be only homogeneous clusters - 2.18

src/common/types/cpuArchitecture.ts
Related to https://issues.redhat.com/browse/MGMT-14320
=> MGMT-14320: s390 clusters should be homogeneous

src/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
=> MGMT-14170: Allow ipxe script download for s390 clusters - 2.18

src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkForm.tsx, src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
Please check out the commits to learn more about the fixes
=> Fixes build time errors

package.json, src/common/components/clusterConfiguration/SecurityFields.tsx, src/common/components/ui/formik/CheckboxField.tsx, src/common/components/ui/formik/CodeField.tsx, src/common/components/ui/formik/InputField.tsx, src/common/components/ui/formik/LabelField.tsx, src/common/components/ui/formik/MultiSelectField.tsx, src/common/components/ui/formik/NumberInputField.tsx, src/common/components/ui/formik/PullSecretField.tsx, src/common/components/ui/formik/SelectField.tsx, src/common/components/ui/formik/SwitchField.tsx, src/common/components/ui/formik/TextAreaField.tsx, src/common/components/ui/formik/UploadField.tsx
https://issues.redhat.com/browse/MGMT-9166
**Some examples of input fields with helper and error texts:**
=> MGMT-9166 - Help text disappears once there is an error

src/common/components/hosts/RoleCell.tsx, src/common/components/hosts/RoleDropdown.tsx, src/common/components/hosts/tableUtils.tsx, src/common/components/hosts/utils.ts, src/common/components/ui/SimpleDropdown.tsx, src/ocm/components/hosts/ClusterHostsTable.tsx, src/ocm/components/hosts/HostsDiscoveryTable.tsx
https://issues.redhat.com/browse/MGMT-14307
Day1 should remain unaffected.
**Before:**
**After:**
=> MGMT-14307 - Day2 - In add hosts - setting "control plane" role to host but UI marks it as control plane + worker

src/ocm/components/clusterDetail/ClusterPollingErrorModal.tsx, src/ocm/components/clusters/Clusters.tsx, src/ocm/reducers/clusters/clustersSlice.ts
https://issues.redhat.com/browse/MGMT-14131
If the error happens on load, we show an in-page error:
If the error happens on reload, we show a modal:
=> MGMT-14131 - When AI service is down, AI cluster list is hang with loading sign

.github/workflows/pull-request.yaml, .github/workflows/push-to-master.yaml, libs/ui-lib/lib/common/config/constants.ts, libs/ui-lib/lib/package.json, libs/ui-lib/tsconfig.json
Fixes this CI issue: https://github.com/openshift-assisted/assisted-installer-ui/actions/runs/4820684340/jobs/8585752382
=> NO-ISSUE: Get the UI lib version from the AIUI_APP_VERSION envvar

.github/CODEOWNERS, .github/workflows/pull-request.yaml, .github/workflows/push-to-master.yaml, README.md, apps/assisted-ui/package.json, libs/eslint-config-assisted-ui/package.json, libs/locales/package.json, libs/toolbox/package.json, libs/ui-lib/package.json, package.json, yarn.lock
Fixes some GitHub Actions unexpected nuances and updates the README file.
=> MGMT-8600: Monorepo leftovers

apps/assisted-ui/package.json, libs/ui-lib/package.json, package.json, yarn.lock
=> NO-ISSUE: Fixes the issue with the toolbox watch command

.github/workflows/release.yaml
=> NO-ISSUE: Do not sleep after publishing the second package

libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewSummary.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/review/TableSummaryExpandable.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/ClusterSummaryExpandable.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/HostInventoryExpandable.tsx
Related to: https://issues.redhat.com/browse/MGMT-14447
We need id to test purposes.
=> MGMT-14447: Add id to kubeconfig download button

libs/locales/lib/en/translation.json, libs/locales/lib/ja/translation.json, libs/locales/lib/ko/translation.json, libs/locales/lib/zh/translation.json, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx, libs/ui-lib/lib/common/components/clusterDetail/KubeconfigDownload.tsx, libs/ui-lib/lib/common/components/ui/ViewClusterEventsButton.tsx
- ViewClusterEventsButton
- KubeconfigDownload
Fixes [MGMT-14448](https://issues.redhat.com//browse/MGMT-14448)
=> MGMT-14448: Enable translation in common components

.github/workflows/release.yaml, libs/ui-lib/lib/common/config/constants.ts, libs/ui-lib/package.json, libs/ui-lib/scripts/generate-build-manifest.mjs
=> MGMT-14497: The UI version deployed to OCM always shows 'latest'

libs/ui-lib/lib/common/components/fetching/EventListFetch.tsx
https://issues.redhat.com/browse/MGMT-14425
The UI uses a new response header to get the total number of available events given the current filters.
=> MGMT-14425 - Improving the severity counters in the events API

libs/ui-lib/lib/common/components/fetching/EventListFetch.tsx
https://issues.redhat.com/browse/MGMT-14471
=> MGMT-14471 - Events modal has memory leak problems

libs/ui-lib/lib/common/components/hosts/HostPropertyValidationPopover.tsx
https://issues.redhat.com/browse/MGMT-14329
**Before:**
**After:**
=> MGMT-14329 - Unhelpful popover for NTP “Synced” status

src/cim/components/ClusterDeployment/ClusterDeploymentCredentials.tsx, src/cim/components/ClusterDeployment/ClusterDeploymentKubeconfigDownload.tsx, src/cim/types/k8s/cluster-deployment.ts
Backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2081
=> CIM: Fallback to CD credentials when they are missing in ACI

libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStep.tsx, libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2DownloadISO.tsx, libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2Wizard.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
Testing 2.20 version I've found some issues. This PR fix these issues
=> NO-ISSUE: Hotfix for version 2.20

libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
=> MGMT-14645: Change Power and z names in the UI (backport)

libs/ui-lib/lib/ocm/services/InfraEnvIdsCacheService.ts
=> MGMT-14646: Problems to create OCP multi version cluster  (backport)

libs/ui-lib/lib/ocm/services/InfraEnvIdsCacheService.ts
Related to https://issues.redhat.com/browse/MGMT-14646
=> MGMT-14646: Problems to create OCP multi version cluster

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/types.ts, libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/utils.ts
Addresses: [MGMT-14261](https://issues.redhat.com//browse/MGMT-14261), [HAC-3989](https://issues.redhat.com//browse/HAC-3989)
=> MGMT-14261: Show the add hosts tab only when the cluster was installed using Assisted Installer

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
=> MGMT-14197: Fix catastrophic backtracking in no proxy dns regex (2.20)

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx, libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/NewFeatureSupportLevelProvider.tsx
Related to https://issues.redhat.com/browse/MGMT-14706
With some changes done in 2.20 version, we can't create P/Z cluster:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/6909295d-252b-4d4e-8c63-5d36004c73f6
With this patch we can create the P/Z  cluster:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/c3f3164c-12ea-406f-ae04-db727e57c9b6
=> MGMT:14706: Solving problems to create pz cluster

libs/ui-lib/lib/common/components/ui/formik/UploadField.tsx
=> MGMT-14658: Generate iso modal - not able to drag and drop ssh key - Page gets blank + upload file not reading it - 2.20

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts, libs/ui-lib/lib/ocm/hooks/useClusterCustomManifests.ts
=> MGMT-14178: Problems renaming manifests file name - 2.20

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx, libs/ui-lib/lib/ocm/hooks/useClusterCustomManifests.ts
=> MGMT-14760: Solving problems saving custom manifests - 2.20

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
=> MGMT-14760: Solving problems saving custom manifests  - follow up - 2.20

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
Related to https://issues.redhat.com/browse/MGMT-14786
=> MGMT-14786: Adding second Manifest delete content of first manifest in UI 

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
Related to https://issues.redhat.com/browse/MGMT-14806
Port of #2179
=> MGMT-14806: Fix error in view installed cluster - 2.21

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
=> MGMT-14807: Change base domain validation regexp to avoid catastrophic backtracking problems - 2.21

apps/assisted-ui/package.json, yarn.lock
https://issues.redhat.com/browse/MGMT-14658
=> MGMT-14658: Generate iso modal - not able to drag and drop ssh key [BACKPORT]

libs/ui-lib/lib/common/types/clusters.ts
=> MGMT-14849: Changes in supported-platforms API with OCI - 2.21

libs/ui-lib/lib/common/types/featureSupportLevel.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/ExternalPartnerIntegrationsCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts, libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
=> MGMT-14905: External platform integrations option should be available from OCP 4.14 and above

libs/ui-lib/lib/ocm/components/clusterWizard/HostDiscovery.tsx
Related to https://issues.redhat.com/browse/MGMT-14970
=> MGMT-14970: After node discovering not change cluster platform when platform type===oci

libs/ui-lib/lib/ocm/components/clusterWizard/HostDiscovery.tsx
=> MGMT-14970: After node discovering not change cluster platform when platform type===oci - 2.21

libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
=> MGMT-14972: Full iso should be blocked in case of OCI (external partners) - 2.21

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetail.tsx
=> MGMT-14833: On-Prem Day2 - add hosts button is not clickable - 2.21

libs/ui-lib/lib/common/features/featureGate.tsx
=> MGMT-14827: Remove multiarch capacity for UI - 2.21

libs/ui-lib/lib/ocm/components/AddHosts/types.ts, libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/utils.ts, libs/ui-lib/lib/ocm/components/index.ts, libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/index.ts, libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/types.ts, libs/ui-lib/lib/ocm/index.ts, libs/ui-lib/lib/ocm/services/CpuArchitectureService.ts, libs/ui-lib/lib/ocm/services/NewFeatureSupportLevelsService.ts, libs/ui-lib/lib/ocm/services/apis/NewFeatureSupportLevelsAPI.ts, libs/ui-lib/lib/ocm/services/apis/index.ts, libs/ui-lib/lib/ocm/services/index.ts
=> MGMT-14996: Day 2 -Can't add hosts to SNO 4.14 cluster - 2.21

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mce-operator.cy.ts, libs/ui-lib-tests/cypress/views/common.ts
Improving tests for MCE operator
=> Improving tests for MCE operator

libs/ui-lib-tests/cypress/integration/ui-behaviour/events-modal.cy.ts
Changed the tests. Let's hope they are more stable now :')
=> MGMT-14787: Event pagination test flakiness

libs/ui-lib/lib/common/index.ts
Fix to solve a problem with version 2.22.0
=> Fix configurations import in v2.22.0

libs/ui-lib/lib/common/index.ts
=> Fix configurations import in v2.22.0 - master

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/ExpandedManifest.tsx
Related to https://issues.redhat.com/browse/MGMT-14730
=> MGMT-14730: Add help text beside filename label

libs/ui-lib-tests/cypress/integration/static-ip/3-configure-static-ip-yaml.cy.ts, libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
=> MGMT-15256: Solving problems uploading yaml in staticIp page - v2.23

libs/ui-lib-tests/cypress/integration/static-ip/3-configure-static-ip-yaml.cy.ts, libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
Related to: https://issues.redhat.com/browse/MGMT-15256
Before these changes, when user upload for first time yaml, it not works well:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/cc28280c-1c7a-4c2b-98d4-f50d074289fb
After these changes, it works well:
https://github.com/openshift-assisted/assisted-installer-ui/assets/11390125/a45c44df-c91c-409b-8de4-4565ee3be334
=> MGMT-15256: Solving problems uploading yaml in staticIp page

libs/ui-lib-tests/cypress/fixtures/infra-envs/feature-support.ts, libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts, libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts, libs/ui-lib-tests/cypress/views/forms/ClusterDetailsForm.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
=> MGMT-15328: External partners remains selected after OCP < v4.14 is selected  - 2.23

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts, libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts, libs/ui-lib/lib/common/components/clusterWizard/types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/HostsNetworkConfigurationControlGroup.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
=> MGMT-15016: Block static ip if oci is selected - 2.23

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts, libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
=> OCPBUGS-16077: problems regexp base domain - followup - 2.24

libs/locales/lib/en/translation.json, libs/ui-lib/lib/common/components/storage/DisksTable.tsx
https://issues.redhat.com/browse/MGMT-14053
=> MGMT-14053: Add "?" icon and a explanation text popover to the " WWN" column

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts, libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
=> OCPBUGS-16077: Problems base domain validation - remove validation from UI  - 2.24

libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
=> MGMT-15666: Clear alerts when user click next button in cluster details form - 2.24

libs/ui-lib/lib/ocm/components/clusters/AssistedInstallerHeader.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx, libs/ui-lib/lib/ocm/components/clusters/NewClusterPage.tsx
https://issues.redhat.com/browse/MGMT-15700
=> MGMT-15700: What's new + AI docs link should appear in all steps

libs/ui-lib/lib/common/features/featureGate.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Backport of #2328
The issue was introduced in #2326
=> MGMT-15709: OCI option must be exposed only to selected users

libs/ui-lib-tests/cypress/fixtures/custom-manifests/files/manifest_multiple.yaml, libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts, libs/ui-lib-tests/cypress/views/common.ts, libs/ui-lib/lib/common/utils.ts
backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2331
=> MGMT-15714: Allow to load multi-yaml files in custom manifests page - 2.24

libs/ui-lib-tests/cypress/fixtures/custom-manifests/files/manifest_multiple.yaml, libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts, libs/ui-lib-tests/cypress/views/common.ts, libs/ui-lib/lib/common/utils.ts
=> MGMT-15714: Allow to load multi-yaml files in custom manifests page - 2.25

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Related to https://issues.redhat.com/browse/MGMT-15726
=> MGMT-15726: Add developer preview badge to oci option in external platform dropdown

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
=> MGMT-15725: Add developer preview badge to oci option in external platform dropdown - 2.24

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts, libs/ui-lib-tests/cypress/views/forms/ClusterDetails/ClusterDetailsForm.ts, libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/SnoField.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
=> MGMT-15530: external platform integration dropdown - disable Nutanix and Vsphere when sno is selected - 2.24

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
=> MGMT-15708: cluster details page - block power/z + SNO + OCI platform - 2.25

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
=> MGMT-15708: cluster details page - block power/z + SNO + OCI platform - 2.24

libs/ui-lib/lib/common/components/ui/formik/SingleNodeCheckbox.tsx, libs/ui-lib/lib/common/features/featureGate.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> MGMT-7525: Removes obsolete feature-toggles - 2.24

libs/ui-lib/lib/common/features/featureGate.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
The issue was introduced in #2326
Backport of #2328
=> MGMT-15709: OCI option must be exposed only to selected users - 2.24

libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
Related to https://issues.redhat.com/browse/MGMT-15760
=> MGMT-15760: Change the text for Oracle in the External partner integrations dropdown

libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
=> MGMT-15760: Change the text for Oracle in the External partner integrations dropdown - 2.25

libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
=> MGMT-15760: Change the text for Oracle in the External partner integrations dropdown - 2.24

libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
=> MGMT-15760: Change the text for Oracle in the External partner integrations dropdown - followup

libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
=> MGMT-15760: Change the text for Oracle in the External partner integrations dropdown - followup - 2.24

libs/ui-lib-tests/cypress/fixtures/cluster/external-platform-types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
=> MGMT-15760: Change the text for Oracle in the External partner integrations dropdown - followup - 2.25

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
https://issues.redhat.com/browse/MGMT-15734
=> MGMT-15734: Remove helper from Oracle platform when hover on it [2.25 BACKPORT]

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
https://issues.redhat.com/browse/MGMT-15734
=> MGMT-15734: Remove helper from Oracle platform when hover on it

libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
https://issues.redhat.com/browse/MGMT-15734
=> MGMT-15734: Remove helper from Oracle platform when hover on it [2.24 BACKPORT]

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
=> MGMT-15737: Disable UMN when platform type is nutanix or vsphere - 2.25

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
=> MGMT-15737: Disable UMN when platform type is nutanix or vsphere - 2.24

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
Related to https://issues.redhat.com/browse/MGMT-15737
When platform.type==='nutanix' or 'vsphere' we need to disable UMN option.
=> MGMT-15737: Disable UMN when platform type is nutanix or vsphere

libs/types/assisted-installer-service.d.ts, libs/ui-lib-tests/cypress/fixtures/day2-flow/day1-ai-cluster.ts, libs/ui-lib-tests/cypress/fixtures/storage/storage-cluster.ts, libs/ui-lib/lib/common/api/assisted-service/NewFeatureSupportLevelsAPI.ts, libs/ui-lib/lib/common/components/newFeatureSupportLevels/types.ts, libs/ui-lib/lib/common/types/featureSupportLevel.ts, libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts, libs/ui-lib/lib/ocm/hooks/useSupportLevelsAPI.ts
Related to https://issues.redhat.com/browse/MGMT-15803
Update calls to feature support levels API using platform type param
=> MGMT-15803: Update calls to feature support levels API using platform type param

libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvFormPage.tsx, libs/ui-lib/lib/cim/components/modals/AddHostModal.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx, libs/ui-lib/lib/common/config/constants.ts
Still waiting for confirmation that this is the correct link
=> MGMT-15649: Fix incorrect docs link for nmstate config

libs/types/assisted-installer-service.d.ts, libs/ui-lib-tests/cypress/fixtures/day2-flow/day1-ai-cluster.ts, libs/ui-lib-tests/cypress/fixtures/storage/storage-cluster.ts, libs/ui-lib/lib/common/api/assisted-service/NewFeatureSupportLevelsAPI.ts, libs/ui-lib/lib/common/components/newFeatureSupportLevels/types.ts, libs/ui-lib/lib/common/types/featureSupportLevel.ts, libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts, libs/ui-lib/lib/ocm/hooks/useSupportLevelsAPI.ts
=> MGMT-15803: Update calls to feature support levels API using platform type param - 2.25

libs/types/accounts-management-service.d.ts, libs/types/authorization-service.d.ts, libs/types/package.json, libs/ui-lib/lib/common/api/accounts-management-service/access-token-api.ts, libs/ui-lib/lib/common/api/accounts-management-service/current-account-api.ts, libs/ui-lib/lib/common/api/accounts-management-service/organizations-api.ts, libs/ui-lib/lib/common/api/authorization-service/all-apis.ts
https://issues.redhat.com/browse/MGMT-15756
=> MGMT-15756: Adds API clients for AMS and authorization svc

.github/workflows/pull-request.yaml, libs/ui-lib-tests/package.json, yarn.lock
Related to https://github.com/cypress-io/cypress/issues/27804
https://issues.redhat.com/browse/MGMT-15857
=> MGMT-15857: Fix GH actions (Cypress)

libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmBaseDomainField.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
https://issues.redhat.com/browse/MGMT-15647
=> MGMT-15647: Unable to change to temporary 60-day domain

.eslintrc.json, .github/workflows/pull-request.yaml, docs/CONTRIBUTING.md, libs/ui-lib-tests/package.json, libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts, libs/ui-lib/tsconfig.eslint.json, libs/ui-lib/tsconfig.json, package.json, yarn.lock
backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2386
=> MGMT-15857: Fix GH actions (Cypress) (#2386)

libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetails.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/helpers.ts
backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2367
=> MGMT-15652 Fix disappearing events modal

libs/types/README.md, libs/types/accounts-management-service.d.ts, libs/types/authorization-service.d.ts, libs/types/package.json, libs/ui-lib/lib/common/api/accounts-management-service/access-token-api.ts, libs/ui-lib/lib/common/api/accounts-management-service/current-account-api.ts, libs/ui-lib/lib/common/api/accounts-management-service/organizations-api.ts, libs/ui-lib/lib/common/api/authorization-service/all-apis.ts
Reverts openshift-assisted/assisted-installer-ui#2392
We are not yet ready for this change. Right now it causes more trouble than it should.
=> Revert "MGMT-15871: Changing types in external API calls to use types from sdks package"

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifests.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsArray.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/utils.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/data/dataTypes.ts
https://issues.redhat.com/browse/MGMT-15597
=> MGMT-15597: Custom manifests - stop using fakeIds

libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx, libs/ui-lib/lib/cim/components/helpers/versions.ts, libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx, libs/ui-lib/lib/common/components/ui/formik/types.ts
ACM PR https://github.com/stolostron/console/pull/3084
=> MGMT-15805 Set OVNKubernetes network type as default for 4.12+ clusters

libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx, libs/ui-lib/lib/cim/components/helpers/versions.ts, libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx, libs/ui-lib/lib/common/components/ui/formik/types.ts
Backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2399
=> [2.8] MGMT-15805 Set OVNKubernetes network type as default for 4.12+ clusters

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2400
=> [2.8] MGMT-15633 Improve NMState config msg

libs/ui-lib/package.json, yarn.lock
Related to https://issues.redhat.com/browse/MGMT-15952
=> MGMT-15952: Declaring PF4 as a direct dependency

libs/ui-lib/package.json, yarn.lock
Related to https://issues.redhat.com/browse/MGMT-15952
Remove patternfly from peerDependencies in package.json
=> MGMT-15952: Declaring PF4 as a direct dependency - followup

locales/en/translation.json, src/cim/components/ClusterDeployment/ClusterDeploymentCredentials.tsx, src/common/components/clusterDetail/ClusterCredentials.tsx
backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2049
=> CIM: Handle case when admin credentials are not available

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/modals/CimConfiguration/CimConfigProgressAlert.tsx, libs/ui-lib/lib/cim/components/modals/CimConfiguration/constants.ts
backport of https://github.com/openshift-assisted/assisted-installer-ui/pull/2239
=> MGMT-15140: Do not report delayed CIM config as an error

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTab.tsx, libs/ui-lib/lib/ocm/components/Routes.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/HostInventory.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetail.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx, libs/ui-lib/lib/ocm/hooks/_use-feature-detection.test.tsx, libs/ui-lib/lib/ocm/hooks/use-feature-detection.ts, libs/ui-lib/lib/ocm/hooks/use-feature.ts, libs/ui-lib/lib/ocm/store/slices/feature-flags/selectors.ts
Related to https://issues.redhat.com/browse/MGMT-16103
We have a hook now that integrates with the Redux store called "useFeatureDetection", that achieves the same functionality.
=> MGMT-16103: Remove FeatureGateContextProvider

libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx
=> MGMT-16151: Failed to download installation logs from cluster with 103 nodes - 2.27

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/FolderDropdown.tsx
Related to https://issues.redhat.com/browse/MGMT-14729
=> MGMT-14729: Custom Manifest - enhance popup text next to Folder label

libs/ui-lib/lib/ocm/services/Day2ClusterService.ts
Related to https://issues.redhat.com/browse/MGMT-16354
=> MGMT-16354: Problem adding hosts when platform type is not baremetal,nutanix,vsphere,none,oci - 2.28

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
https://issues.redhat.com/browse/MGMT-15365
=> MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow

libs/locales/lib/en/translation.json, libs/ui-lib/lib/common/components/hosts/TableToolbar.tsx
https://issues.redhat.com/browse/MGMT-16284
=> MGMT-16284: Infrastructure->Host Inventory->Hosts : Actions menu tooltip is unmarked for translation

libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2441
=> MGMT-15633: Improve UX for static network config in CIM (in BMC dialog) [BACKPORT 2.8]

libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2441
=> MGMT-15633: Improve UX for static network config in CIM (in BMC dialog) [BACKPORT 2.9]

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2423
=> MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow [BACKPORT 2.9]

libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Related to https://issues.redhat.com/browse/MGMT-16478
Before changes, unable to create arm + 4.10 cluster:
After changes:
=> MGMT-16478: Solving problems creating ARM+4.10 cluster

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts, libs/ui-lib/lib/ocm/components/utils.ts
=> MGMT-16463: Enable LVMS for OCP version 4.15 or above - 2.30

libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
https://issues.redhat.com/browse/MGMT-15633
Skeleton from [docs](https://docs.okd.io/latest/installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.html).
=> MGMT-15633: Improve UX for static network config in CIM (in BMC dialog)

libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2483
=> MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow [FOLLOWUP] [BACKPORT 2.9]

libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx, libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
https://issues.redhat.com/browse/MGMT-16810
=> MGMT-16810: Changes in hosts' "Status" filter in host inventory make the filter useless

apps/assisted-ui/Containerfile
Change Nodejs version from 16 to 18 in Containerfile
=> FIX: Change Nodejs version in Containerfile

libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx, libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
https://issues.redhat.com/browse/MGMT-16810
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2496
=> MGMT-16810: Changes in hosts' "Status" filter in host inventory make the filter useless [BACKPORT 2.10]

libs/ui-lib/lib/cim/components/ClusterDeployment/NetworkConfiguration.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts, libs/ui-lib/lib/common/components/clusterConfiguration/utils.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts, libs/ui-lib/lib/ocm/components/fetching/fetchEvents.ts
https://issues.redhat.com/browse/MGMT-15805
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2495
=> MGMT-15805: OpenshiftSDN is the default SDN selected when installing a new cluster [2.8-cim BACKPORT]

libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
https://issues.redhat.com/browse/MGMT-16841
=> MGMT-16841: Failed to add host when infraenv has networkType of DHCP

libs/ui-lib-tests/cypress/views/storagePage.ts, libs/ui-lib/lib/cim/components/Agent/MinimalHWRequirements.tsx, libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx, libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HostedClusterProgress.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, libs/ui-lib/lib/common/components/clusterWizard/ReviewValidations.tsx, libs/ui-lib/lib/common/components/hosts/VMRebootConfigurationInfo.tsx, libs/ui-lib/lib/common/components/storage/DisksTable.tsx, libs/ui-lib/lib/common/components/storage/StorageUtils.tsx, libs/ui-lib/lib/common/components/ui/UiIcon.tsx, libs/ui-lib/lib/common/components/ui/WizardNavItem.tsx, libs/ui-lib/lib/common/components/ui/formik/RemovableField.tsx, libs/ui-lib/lib/common/components/ui/index.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationNote.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewPreflightChecks.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/OpenShiftVersionDetail.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/ResetClusterModal.tsx, libs/ui-lib/lib/ocm/components/clusters/ClusterStatus.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx, libs/ui-lib/lib/ocm/components/ui/InfoLinkWithModal.tsx
Related to https://issues.redhat.com/browse/MGMT-17013
Solving problems with icon's color in Review&Create page:
=> MGMT-17013: Solving problems with icon's color that are incorrect in Review&Create page

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsForm.tsx, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/types.ts
https://issues.redhat.com/browse/MGMT-16982
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2511
=> MGMT-16982: Enable switching infra-availability-policy Single replica / HA [BACKPORT 2.10]

libs/ui-lib/lib/common/components/ui/formik/UploadField.tsx
Related to https://issues.redhat.com/browse/MGMT-17132
=> MGMT-17132: Trigger SSH key validations when user changes this field

libs/ui-lib/lib/cim/components/modals/EditAgentModal.tsx
https://issues.redhat.com/browse/MGMT-17118
=> MGMT-17118: Host agent name change, UX flow could be improved

libs/ui-lib/lib/cim/components/Agent/AgentStatus.tsx, libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx, libs/ui-lib/lib/cim/components/helpers/status.ts
https://issues.redhat.com/browse/MGMT-17281
=> MGMT-17281: CIM UI crashes if the installation_disk_id is not correct

libs/ui-lib/lib/cim/components/Agent/AgentStatus.tsx, libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx, libs/ui-lib/lib/cim/components/helpers/status.ts
https://issues.redhat.com/browse/MGMT-17281
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2522
=> MGMT-17281: CIM UI crashes if the installation_disk_id is not correct [BACKPORT 2.9]

libs/ui-lib/lib/cim/components/Agent/AgentStatus.tsx, libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx, libs/ui-lib/lib/cim/components/helpers/status.ts
https://issues.redhat.com/browse/MGMT-17281
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2522
=> MGMT-17281: CIM UI crashes if the installation_disk_id is not correct [BACKPORT 2.10]

libs/types/assisted-installer-service.d.ts, libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts, libs/ui-lib/lib/common/utils.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
=> MGMT-15999: Assisted Installer UI should allow patch manifests - 2.31

apps/assisted-ui/package.json, libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts, libs/ui-lib/lib/cim/components/ClusterDeployment/use-networking-formik.ts, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx, libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvFormPage.tsx, libs/ui-lib/lib/cim/components/modals/EditProxyModal.tsx, libs/ui-lib/lib/cim/components/modals/ScaleUpModal.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStep.tsx, libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts, libs/ui-lib/lib/common/components/clusterWizard/index.ts, libs/ui-lib/lib/common/components/ui/formik/utils.ts, libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/propTypes.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/formViewHostsValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/formViewNetworkWideValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/StaticIpForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/YamlView/yamlViewValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/propTypes.ts, libs/ui-lib/package.json, yarn.lock
https://issues.redhat.com/browse/MGMT-17348
Upgrades `Yup` to 1.4.0.
=> MGMT-17348: UI gets stuck in networking page

apps/assisted-ui/package.json, libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts, libs/ui-lib/lib/cim/components/ClusterDeployment/use-networking-formik.ts, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx, libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx, libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvFormPage.tsx, libs/ui-lib/lib/cim/components/modals/EditProxyModal.tsx, libs/ui-lib/lib/cim/components/modals/ScaleUpModal.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStep.tsx, libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts, libs/ui-lib/lib/common/components/clusterWizard/index.ts, libs/ui-lib/lib/common/components/ui/formik/utils.ts, libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/propTypes.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/formViewHostsValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/formViewNetworkWideValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/StaticIpForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/YamlView/yamlViewValidationSchema.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/propTypes.ts, libs/ui-lib/package.json, yarn.lock
https://issues.redhat.com/browse/MGMT-17348
Upgrades Yup to 1.4.0.
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2532
=> MGMT-17348: UI gets stuck in networking page [BACKPORT 2.31]

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx
Related to https://issues.redhat.com/browse/MGMT-17377
Validate field values in Networking page:
=> MGMT-17377: Change the way to validate field values in networking page

libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx
=> MGMT-17377: Change the way to validate field values in networking page - 2.31

libs/locales/lib/en/translation.json, libs/ui-lib-tests/cypress.config.ts, libs/ui-lib-tests/cypress/fixtures/day2-flow/day2-responses.ts, libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts, libs/ui-lib-tests/cypress/integration/create-sno/0-create-cluster.cy.ts, libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts, libs/ui-lib-tests/cypress/support/interceptors.ts, libs/ui-lib/lib/common/api/assisted-service/SupportedOpenshiftVersionsAPI.ts, libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts, libs/ui-lib/lib/common/components/clusterWizard/types.ts, libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx, libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenShiftVersionModal.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenshiftVersionModal.css, libs/ui-lib/lib/ocm/components/clusterDetail/OpenShiftVersionDetail.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx, libs/ui-lib/lib/ocm/components/clusters/NewClusterPage.tsx, libs/ui-lib/lib/ocm/hooks/useOpenshiftVersions.tsx
=> MGMT-12995: Allow users to use custom OCP releases  - 2.31

libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
=> MGMT-17475: Updating CPU and platform dropdowns when OCP custom release is selected - 2.31

libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx
=> MGMT-17471: Add maxLength to search input and not allow to select 'No results found' option - 2.31

libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx, libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx
=> MGMT-17477: Show dev preview badge when select custom OCP versions - 2.31

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts
=> MGMT-17476: Solving problems with validations in Advanced Networking fields in Networking Page - 2.31

libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenShiftVersionModal.tsx
=> MGMT-17504: Adjusting behavior of the OpenshiftVersionModal buttons - 2.31

libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx
=> MGMT-17501: Show all OCP versions in OpenshiftVersionDropdown - 2.31

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts, libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx, libs/ui-lib/lib/common/components/ui/OpenshiftSelectWithSearch.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenShiftVersionModal.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenshiftVersionHelperText.tsx
=> MGMT-17477: Update dev preview badge when user selects custom OCP release - 2.31

libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
=> MGMT-17569: Patch Manifest - Second attempt to upload invalid content of manifest not declined - 2.31

libs/ui-lib/lib/common/components/hosts/MassChangeHostnameModal.tsx
=> MGMT-17139: Enable "Change" button in Mass Change Hostname Modal when hostname value is not empty - 2.31

libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStepValidationsAlert.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx
Related to https://issues.redhat.com/browse/MGMT-17696 and https://issues.redhat.com/browse/MGMT-17809
=> MGMT-17696: Show an error message to the user when the cluster preparation fails

libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts, libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-custom-ocp-releases.cy.ts, libs/ui-lib-tests/cypress/views/clusterDetails.ts, libs/ui-lib-tests/cypress/views/customOCPModal.ts
=> MGMT-17439: Add tests to assisted-ui-lib for custom OCP releases - 2.31

libs/ui-lib/lib/common/config/constants.ts
=> MGMT-17851: Asisted installer link documentation broken - 2.31

libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts, libs/ui-lib-tests/cypress/views/forms/CustomManifests/CustomManifestsForm.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
=> MGMT-17904: Custom manifests page - UI not validating filename field before sending it to BE - 2.31

libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx, libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx, libs/ui-lib/lib/common/components/hosts/HostRequirements.tsx, libs/ui-lib/lib/common/components/ui/TechnologyPreview.tsx, libs/ui-lib/lib/common/config/constants.ts, libs/ui-lib/lib/common/config/docs_links.ts, libs/ui-lib/lib/common/config/index.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/UserManagedNetworkingTextContent.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx, libs/ui-lib/lib/ocm/components/hosts/HostRequirementsContent.tsx
Related to https://issues.redhat.com/browse/MGMT-17933
To avoid problems with docs links we agree with docs team that we'll create a docs_links.ts with all the links that we are consuming in Assisted UI Lib.
=> MGMT-17933: Create docs_links file with all documentation links

libs/ui-lib/lib/cim/components/helpers/versions.ts
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2589
=> [2.10-cim] MGMT-17417 Consider architecture label when getting ocp img arch

libs/ui-lib/lib/cim/components/helpers/network.ts
https://issues.redhat.com/browse/MGMT-17940
=> MGMT-17940: CIM UI crashes on the create cluster networking page

libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
https://issues.redhat.com/browse/MGMT-17993
=> Add host popup - proxy fields - API supports adding one of the proxy fields while in UI both HTTP and HTTPS are mandatory

libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
https://issues.redhat.com/browse/MGMT-16841
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2500
=> MGMT-16841: Failed to add host when infraenv has networkType of DHCP [BACKPORT 2.9]

libs/ui-lib/lib/cim/components/modals/EditAgentModal.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2515
=> MGMT-17118: Host agent name change, UX flow could be improved [BACKPORT 2.11]

libs/ui-lib/lib/cim/components/helpers/network.ts
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2585
=> MGMT-17940: CIM UI crashes on the create cluster networking page [BACKPORT 2.11]

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmHostRequirements.tsx
=> MGMT-16996: Show only LVMS requirements messages from BE - 2.32

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Related to https://issues.redhat.com/browse/MGMT-17123
Read the CPU and RAM requirements from additional requirements API.
=> MGMT-17123: Add CPU and RAM requirements for MCE operator

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> MGMT-17123: Add CPU and RAM requirements for MCE operator - 2.32

libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/dummyData.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
=> MGMT-18211: Static IP dualstack form - UI sends incorrect NMstate to BE  - 2.32

libs/ui-lib/lib/common/config/docs_links.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
=> MGMT-18241: Review docs_links file to align all the URLs with correct links - 2.32

libs/ui-lib/lib/common/config/docs_links.ts
Related to https://issues.redhat.com/browse/MGMT-18241
Change LVMS operator documentation link in Operators page.
=> MGMT-18241: Change documentation link for LVMS operator

libs/ui-lib/lib/common/config/docs_links.ts
=> MGMT-18241: Change documentation link for LVMS operator - 2.32

libs/ui-lib/lib/ocm/components/clusterDetail/CancelInstallationModal.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
https://issues.redhat.com/browse/MGMT-17466
=> MGMT-17466: There is no way to Abort cluster installation when it is Finalizing

libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts
https://issues.redhat.com/browse/MGMT-18296
=> MGMT-18296: User Managed networking selection in Network page is not "remembered"

libs/ui-lib/lib/common/config/docs_links.ts
Related to https://issues.redhat.com/browse/MGMT-18321
=> MGMT-18321: Change Assisted Installer documentation link

libs/ui-lib/lib/common/components/ui/formik/RemovableField.css
https://issues.redhat.com/browse/MGMT-18368
**Before:**
**After:**
=> MGMT-18368: Removable field 'remove' button styling issues

libs/ui-lib-tests/cypress/integration/day-2/1-first-access.cy.ts, libs/ui-lib-tests/cypress/support/interceptors.ts, libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2638
=> MGMT-17540: Remove unnecessary calls to openshift-versions API in cluster creation page [FOLLOWUP, BACKPORT 2.33]

libs/ui-lib-tests/cypress/integration/day-2/1-first-access.cy.ts, libs/ui-lib-tests/cypress/support/interceptors.ts, libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx
https://issues.redhat.com/browse/MGMT-17540
I missed a couple components.
=> MGMT-17540: Remove unnecessary calls to openshift-versions API in cluster creation page [FOLLOWUP]

apps/assisted-ui/package.json, libs/ui-lib/package.json, yarn.lock
Updating monaco-editor library to use in assisted-installer-app
=> NO-ISSUE: Updating monaco-editor library to use in assisted-installer-app

apps/assisted-ui/package.json, libs/ui-lib/package.json, yarn.lock
=> Updating monaco-editor lib - 2.33

libs/ui-lib/lib/cim/components/helpers/network.ts
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2643
=> MGMT-18439: Handle undefined majority_groups gracefully [BACKPORT 2.12]

libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx, libs/ui-lib/lib/ocm/components/clusters/CustomToolbarFilter.tsx
Related to https://issues.redhat.com/browse/MGMT-18567
Try to solve the error that happens in Assisted Installer clusters list:
=> MGMT-18567: Solving errors in clusters list - 2.33

libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx, libs/ui-lib/lib/ocm/components/clusters/CustomToolbarFilter.tsx
Related to https://issues.redhat.com/browse/MGMT-18567
Try to solve the error that happens in Assisted Installer clusters list:
=> MGMT-18567: Solving errors in clusters list

libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx
https://issues.redhat.com/browse/MGMT-18862
UHC Portal: https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/5931
=> MGMT-18862: production via console.dev.redhat.com returns error

libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStepValidationsAlert.tsx, libs/ui-lib/lib/common/types/index.ts, libs/ui-lib/lib/common/types/ui-settings.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewStep.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContext.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx, libs/ui-lib/lib/ocm/hooks/useUISettings.ts, libs/ui-lib/lib/ocm/services/UISettingsService.ts, libs/ui-lib/lib/ocm/services/types.ts
https://issues.redhat.com/browse/MGMT-18099
=> MGMT-18099: warning of error in prepare installation remain even after fixing manifest name

libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx, libs/ui-lib/lib/common/components/hosts/utils.ts
https://issues.redhat.com/browse/ACM-14148
=> ACM-14148: "Invalid value for key _targetInst" error when trying to search for host

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
https://issues.redhat.com/browse/MGMT-18847
=> MGMT-18847: UI does not recognize externally provisioned BMH status

libs/ui-lib/lib/common/config/docs_links.ts
https://issues.redhat.com/browse/MGMT-19132
=> MGMT-19132: Broken url in networking page

libs/locales/lib/en/translation.json, libs/types/assisted-installer-service.d.ts, libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts, libs/ui-lib-tests/cypress/views/forms/Operators/OperatorsForm.ts, libs/ui-lib/lib/common/config/constants.ts, libs/ui-lib/lib/common/config/docs_links.ts, libs/ui-lib/lib/common/types/clusters.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts, libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Related to https://issues.redhat.com/browse/MGMT-18859
=> MGMT-18859: Add MTV operator to Operators page

libs/ui-lib-tests/cypress/support/variables/networking.ts, libs/ui-lib-tests/cypress/views/networkingPage.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTableBase.tsx
=> MGMT-19285: Change data-testid='nic-status' in networking page to data-testid='host-status' - 2.36

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvRequirements.tsx
Related to https://issues.redhat.com/browse/MGMT-19275
=> MGMT-19275: Show correct requirements for MTV operator

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvRequirements.tsx
=> MGMT-19275: Show correct requirements for MTV operator - 2.36

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
Related to https://issues.redhat.com/browse/MGMT-19274
=> MGMT-19274: MTV Operator - selecting mtv operator does not select cnv

libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
=> MGMT-19274: MTV Operator - selecting mtv operator does not select cnv - 2.36

libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx, libs/ui-lib/lib/common/components/ui/formik/types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/ExpandedManifest.tsx
Related to https://issues.redhat.com/browse/MGMT-19196
https://github.com/user-attachments/assets/e99ce58c-f9ca-4448-bdcd-86252667d142
=> MGMT-19196: Implement 'Paste' button in Custom manifests form

libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx, libs/ui-lib/lib/common/components/ui/formik/types.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/ExpandedManifest.tsx
=> MGMT-19196: Implement 'Paste' button in Custom manifests form - 2.36

libs/ui-lib/lib/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx, libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx, libs/ui-lib/lib/cim/components/helpers/versions.ts
https://issues.redhat.com/browse/MGMT-19204
Stolostron/console PR: https://github.com/stolostron/console/pull/4089
=> MGMT-19204: Filter OpenShift versions based on availability in AgentServiceConfig

libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
https://issues.redhat.com/browse/MGMT-19118
=> MGMT-19118: Launch openshift console and Abort Installation buttons got connected

libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataFromInfraEnvField.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
=> MGMT-19389: nmstate not generated well with bonds - 2.36

libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataFromInfraEnvField.ts
Related to https://issues.redhat.com/browse/MGMT-19445
=> MGMT-19445: MAC address should be empty

libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataFromInfraEnvField.ts
=> MGMT-19445: MAC address should be empty - 2.36

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Change the order of the Operators. CNV is more related with MTV:
=> NO-ISSUE: Change order in Operator's page

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> NO-ISSUE: Change order in Operator's page - 2.36

libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
=> MGMT-19615: Solving problems with history undefined - 2.37

libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewStep.tsx
https://issues.redhat.com/browse/MGMT-19604
Clear alerts in installation page when installation starts.
=> MGMT-19604: Clear alerts when starting cluster installation

libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
Related to https://issues.redhat.com/browse/MGMT-19619
=> MGMT-19619: We don't allow users to continue with cluster creation if not agree with cluster limitations

libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
=> MGMT-19587: Show MTU validation only in networking step - 2.37

libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewStep.tsx
=> MGMT-19604: Clear alerts when starting cluster installation - 2.37

libs/locales/lib/en/translation.json, libs/ui-lib/lib/common/config/constants.ts
=> MGMT-19605: Add MTV operator to Installation page - 2.37

libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
=> MGMT-19619: We don't allow users to continue with cluster creation if not agree with cluster limitations - 2.37

libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
=> Solving problems with draft clusters in staging

libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
=> Solving problems with draft clusters in staging - 2.37

libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx, libs/ui-lib/lib/common/config/constants.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageModal.tsx, libs/ui-lib/lib/ocm/services/ClustersService.ts
Add tag to clusters when user choose to create hosts from Cisco Intersight:
And the cluster:
=> MGMT-18925: Add tag to know if users are creating hosts from Cisco Intersight

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Related to https://issues.redhat.com/browse/MGMT-19941
=> MGMT-19441: Disable Openshift AI (NVIDIA) bundle for SNO clusters

OWNERS, apps/assisted-disconnected-ui/proxy/config/config.go
This file is needed for onboarding assisted-disconnected-ui to OpenShift CI
=> Add OWNERS file

libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts, libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
This reverts commit d15c7d6bed16f61e7f2fd2aa9b1d88181dff7cdf.
=> Revert "add OCP custom version button to the top of the dropbox"

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx, libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Related with https://issues.redhat.com/browse/MGMT-19914
Followup of #2805
=> Operators redesign followup - 2

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAIRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenshiftAINvidiaRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/VirtualizationRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> MGMT-20044: Adding requirements and operators in bundle popover content - 2.38

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
=> MGMT-20056: When user selects CNV operator the MTV operator is also selected - 2.38

libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> MGMT-20053: If some operators are not supported, we don't select automatically - 2.38

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Related to https://issues.redhat.com/browse/MGMT-20096
=> MGMT-20096: Virtualization bundle is disabled when selecting LVMS operator

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> MGMT-20096: Virtualization bundle is disabled when selecting LVMS operator - 2.38

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
=> MGMT-20055: Bundle error helper text is unclear - 2.38

libs/ui-lib/lib/common/config/docs_links.ts
=> MGMT-20093: Solving problems with docs links - 2.38

libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Related to https://issues.redhat.com/browse/MGMT-20107
Disable one of the Openshift AI bundles if the other is selected:
=> MGMT-20107: Disable one of the Openshift AI bundles if the other is selected.

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx, libs/ui-lib/lib/cim/components/helpers/versions.ts, libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
https://issues.redhat.com/browse/MGMT-20082
https://issues.redhat.com/browse/MGMT-20083
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2861
=> MGMT-20082: Deploying 4/5 nodes control plane is blocked

libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx, libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2868
=> MGMT-19753: Mismatch in available options in CPU Architecture dropdown menu on Standalone cluster details page and Infraenv create Page

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
https://issues.redhat.com/browse/MGMT-20182
=> MGMT-20182: Day2 - host not shown in the UI session that generated it, but is shown in another session

libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts, libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mce-operator.cy.ts, libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts, libs/ui-lib-tests/cypress/views/forms/Operators/OperatorsForm.ts, libs/ui-lib-tests/cypress/views/operatorsPage.ts, libs/ui-lib/lib/common/config/docs_links.ts, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AmdGpuCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/KmmCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OscCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx, libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/VirtualizationRequirements.tsx, libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
https://issues.redhat.com/browse/MGMT-20217
=> MGMT-20217: Assisted Operators Review

libs/ui-lib-tests/package.json, libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts, libs/ui-lib/package.json, yarn.lock
https://issues.redhat.com/browse/ACM-17263
BP of https://github.com/openshift-assisted/assisted-installer-ui/pull/2776
=> ACM-17263: Add a host using BMC form should have a validation for BMC address

libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
=> MGMT-20182: Day2 - host not shown in the UI session that generated it, but is shown in another session - 2.38

libs/ui-lib/lib/cim/components/helpers/versions.ts
https://issues.redhat.com/browse/MGMT-20762
=> MGMT-20762: Show all available versions is ignoring basic version format v2.12

libs/ui-lib/lib/cim/components/helpers/versions.ts
https://issues.redhat.com/browse/MGMT-20770
=> MGMT-20770: Show all available versions is ignoring basic version format v2.11

libs/ui-lib/lib/common/config/docs_links.ts
https://issues.redhat.com/browse/MGMT-20258
=> MGMT-20258: The link to OpenShift networking documentation opens to 404 error

libs/locales/lib/en/translation.json, libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx, libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
cherry-pick of https://github.com/openshift-assisted/assisted-installer-ui/pull/3019
=> [releases/v2.14-cim] MGMT-20898: In disconnected Standalone cluster installation ClusterImageSet is not getting populated in AgentClusterInstall

libs/ui-lib/lib/common/components/operators/test.tsx
backport of #3018 
* Adding new categories for operators
* Remove unnecessary field category from opSpecs
=> MGMT-20483: Adding new categories for operators - 2.42

libs/ui-lib-tests/cypress/views/clusterDetails.ts, libs/ui-lib/lib/common/components/ui/formik/TextAreaField.tsx
This is manual cherry-pick of https://github.com/openshift-assisted/assisted-installer-ui/pull/3138
=> [releases/v2.15-cim] MGMT-21261: keep link to pull secret visible
